open-learning-exchange/myplanet

- app/src/main/AndroidManifest.xml
Fixes #73  
App is now called "Planet Learning" in both App Drawer and Recent Apps menu.
**Screenshot 1**
**Screenshot 2**
**Screenshot 3**
> App now called "Planet Learning" in both App Drawer and Recent Apps menu

- app/src/main/java/org/ole/planet/myplanet/library/AdapterLibrary.java
- app/src/main/java/org/ole/planet/myplanet/library/LibraryDetailFragment.java
- app/src/main/java/org/ole/planet/myplanet/library/MyLibraryFragment.java
- app/src/main/java/org/ole/planet/myplanet/mymeetup/MyMeetupDetailFragment.java
- app/src/main/java/org/ole/planet/myplanet/survey/AdapterSurvey.java
- app/src/main/java/org/ole/planet/myplanet/teams/MyTeamsDetailFragment.java
- app/src/main/java/org/ole/planet/myplanet/utilities/Constants.java
Only problem with this is where I have my comment
If uncommented, it throws exception when attempting to open library. Without it, it still shows the rating number on library.
However, the same code works on the library detail (clicking on a resource)
With only difference being that it uses `getActivity()` in contrast to `context` on the commented line
(`getActivity()` is not accepted on commented line)
> Expands beta functionality (fixes #410)

- README.md
Fixes #721 
Add a step/tip on myplanet's README page. This tip will tell new interns to sync the myplanet project with gradle files before trying to run the takeout app on Android Studio. This is important since the app will not run otherwise.
https://github.com/open-learning-exchange/myplanet/tree/add_sync_tip
> Add tip to Planet's README.md for new interns (fixes #721)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
- app/src/main/res/values/versions.xml
Fixes #1782 
The navigation menu opens up once by default when the user first logs in so that they know the menu is there. 
Example screenshot: 
* works on tablets and phones without layout issues
> Drawer Opens by Default on Login (fixes #1782)

- app/build.gradle
- app/src/main/res/values/strings.xml
- app/src/main/res/values/versions.xml
Fixes #1804 
In Planet, the user is suggested what units to use when adding an examination as seen below: 
Now in the myPlanet application, the units should match as seen below:
> Add Units to Examination (fixes #1804)

- app/build.gradle
- app/src/main/res/layout/activity_become_member.xml
- app/src/main/res/values/versions.xml
fixes #1812
Changed level spinner background to primary color. Any other color can be used if this one is not suitable.
> Make Level More Apparent on Become a Member Screen (fixes #1812)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java
- app/src/main/res/values/versions.xml
fixes #1836 
Before, the user would be able to exit out of the examination losing all of their data. This may lead to accidental data loss if the user does not mean to exit out of the examination. 
Now, the user receives an alert when exiting out of an exam asking if they are sure of this decision.
> Alert Before Leaving Health Examination (fixes #1836)

- app/build.gradle
- app/src/main/res/layout/activity_become_member.xml
- app/src/main/res/layout/fragment_feedback.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/versions.xml
Changed the layout of buttons to the color scheme used throughout the app in dialogs. Moved dismissive buttons like **Cancel** to the left.
> Fix button layout (fixes #1927)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.java
- app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/JoinedMemberFragment.java
- app/src/main/res/values/versions.xml
- Removed the "make leader" option from the team member card when the user is the leader of the displayed team.
- Fixed typo refactored "AdapterJoinedMemeber" to "AdapterJoinedMember.
"
> Remove "make leader" option for the team leader (fixes #1892)

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceFragment.java
- app/src/main/res/values/versions.xml
- app/src/main/res/xml/file_paths.xml
fixes issue #2160
which was an error thrown when adding a resource by capturing image caused the app to crash 
click red menu icon -> click add resource button -> click capture image to experience crash
before fix
after fix 
click red menu icon -> click add resource button -> click capture image
> addresource: switch to FileProvider for video capture (fixes #2160)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.java
- app/src/main/res/values/versions.xml
Fixes #2195 
error that occurs when adding a pdf resource is handled and the app no longer crashes but shows the user an error message
> adding error handling for pdf resource addition (fixes #2195)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/MainApplication.java
- app/src/main/res/values/versions.xml
Fixes #2178 
To address this issue, it is necessary to revert the recent code changes made to the MainApplication class and restore the original code that encompassed the omitted functionality. By reverting to the previous version of the code, we can ensure that the application functions as intended and that the crucial features are reinstated.
> revert to MainApplication (fixes #2178)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.java
- app/src/main/res/values/versions.xml
fixes #2315
In this pull request
call autosync worker class on the main thread to prevent null exception error
make initial sync call on app launch
> sync: automatic instead of crashing (fixes #2315)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.java
- app/src/main/res/values/versions.xml
fixes #2381
used a RealmChangeListener in the second parameter of executeTransactionAsync.
The RealmChangeListener triggered the UI update only after the transaction had successfully completed, ensuring that the data queried was the latest
> feedback: refactor update list (fixes #2381)

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/res/values/versions.xml
> manifest: remove duplicate `FileProvider` (fixes #2395)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java
- app/src/main/res/values/strings.xml
This is a minor typo fix when checking the version. 
I initially noted this when I was logging in and there  was a `snackbar` with a typo error. 
So this PR will address the fix. 
Also I created a string resource instead of using a raw string
> login: improve check version (fixes #2474)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java
- app/src/main/res/layout/fragment_course_step.xml
> courses: better course step display (fixes #2771)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java
> resources: more stability (fixes #2805)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java
- app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-so/strings.xml
- app/src/main/res/values/strings.xml
fixes #1952
When filtering courses, add background text "No courses matched filter" when no courses are returned
> courses: text when filter results empty (fixes #1952)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/model/RealmOfflineActivity.kt
fixes #3089
this data ensures that offline logins are recorded in realm to show accurate number of visits
> actions: better `RealmOfflineActivity` (fixes #3089)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
> sync: only init icon at login (fixes #3187)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
fixes #3235
this pr check initialization of realm before closing realm and also alows the use of alternative urls
```
local ip        [http://192.168.x.y]
tunnel port  [http://tunnel.ole.org:abcde]
ssl proxy     https://planet.community.ole.org
```
> sync: enabling tunneled and proxied urls (fixes #3235)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/utilities/JsonUtils.kt
fixes #3260
this pr addresses `unsupportedOperationException` by enhance the getString method to explicitly check whether the JsonElement is a JsonPrimitive and is suitable for conversion to a string
> all: safer non-string json (fixes #3260)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
fixes #3261
this pr replaces deprecated `stop()` with `interrupt()` which is a more cooperative approach, where the thread is signalled to stop at the next convenient moment
> sync: `.interupt` to stop threads (fixes #3261)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/datamanager/ApiInterface.kt
- app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
- app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
- app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
fixes #3369
this pr adds a feature if the app notices a learner trying to sync to a different server it clears the app data to prevent mixup of data from different servers in the couchDb
[cleardata.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/328773b6-4d57-4b89-a51a-ecea37371048)
> sync: clear app data (fixes #3369)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.kt
- app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
fixes #3419
this pr ensures that a new transaction is not started if one is already active in the given chat Realm instance
> chat: smoother transaction for realm (fixes #3419)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/datamanager/ApiInterface.kt
- app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
fixes #3402 
this pr removes unnecessary header in get configuration api call which was causing an unathorizes error preventing sync
> sync: smoother configuration call (fixes #3402)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/viewer/CSVViewerActivity.kt
- app/src/main/java/org/ole/planet/myplanet/ui/viewer/ImageViewerActivity.kt
- app/src/main/java/org/ole/planet/myplanet/ui/viewer/MarkdownViewerActivity.kt
- app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
- app/src/main/java/org/ole/planet/myplanet/ui/viewer/TextFileViewerActivity.kt
(fixes #3499)
removed file extension from resource names for images, csv, markdown, pdf, and text 
There are no markdown or text files to test for resources which is why they are not imaged.
> resources: show only filename (fixes #3499)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
fixes #2354 
omitted the `crash log uploaded` message after successful sync using the sync icon.
> sync: update success message (fixes #2354)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/viewer/CSVViewerActivity.kt
- app/src/main/java/org/ole/planet/myplanet/ui/viewer/ImageViewerActivity.kt
- app/src/main/java/org/ole/planet/myplanet/ui/viewer/MarkdownViewerActivity.kt
- app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
- app/src/main/java/org/ole/planet/myplanet/ui/viewer/TextFileViewerActivity.kt
- app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt
fixes #3509 
Added a function `extractFileName` to `FileUtils.kt` which will extract the filename regardless of filetype. Currently implemented in csv, image, markdown, pdf, and text files.
> resources: smoother filename extraction (fixes #3509)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/resources/AdapterResource.kt
- app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
- app/src/main/res/layout/fragment_library_detail.xml
fixes #3543
only show if value is not empty
central placement of buttons even with longer resource titles
> resources: smoother details view (fixes #3543)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
fixes #3617 
updated overridePendingTransition in deletePost() to overrideActivityTransition
[delete_post.webm](https://github.com/open-learning-exchange/myplanet/assets/112584985/9a43a8d5-e54b-4825-b495-315d7216ad2a)
> actions: less warnings is more (fixes #3617)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
fixes #3611 
updated getParcelableExtra(string) to getParcelableExtra(string, class)
left setWifiEnabled alone since there is no workaround for the deprecation
> actions: less warnings is more (fixes #3611)

- app/build.gradle
- app/src/main/res/layout/fragment_member_detail.xml
> teams: circular member images (fixes #3623)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityPagerAdapter.kt
- app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt
fixes #3667 
`import com.borax12.materialdaterangepicker.date.DatePickerDialog` currently still uses deprecated fragmentManager and does not support the newer version supportFragmentManager yet.
I left fragmentManager in for now. 
Repository for material date range picker: https://github.com/heysupratim/material-daterange-picker
> actions: less warnings is more (fixes #3667)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
- app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
- app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
fixes #3728
Updated `MyDownloadService.kt` to use `WorkManager` instead of deprecated `IntentService`
Modified `Utilities.kt` and `DialogUtils.kt` to use new `MyDownloadService.kt`
> sync: smoother downloads (fixes #3728)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
- app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
- app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
- app/src/main/res/drawable/baseline_check_24.xml
- app/src/main/res/layout/row_chat_history.xml
> chat: mark shared (fixes #3734)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
- app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
fixes #3753
[Screen_recording_20240702_152053.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/1bfc14d4-ddec-48b2-b0bc-7f2682d6b078)
> dashboard: default system behavior (fixes #3753)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt
fixes #3772
`ACTION_INSTALL_PACKAGE` deprecated
now using `android.content.pm.PackageInstaller` instead
modified `getImagePath()` to address error using `getColumnIndex()`: `Value must be ≥ 0 but getColumnIndex can be -1`
`DATA` is also deprecated starting from API level 29, changed it to use `DocumentFile` instead.
> actions: less warnings is more (fixes #3772)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
fixes #3810
`launched from foreground`
`fresh launch`
> all: log launches (fixes #3810)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.kt
- app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
- app/src/main/java/org/ole/planet/myplanet/ui/resources/AdapterResource.kt
- app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
- app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
- app/src/main/java/org/ole/planet/myplanet/utilities/CustomSpinner.kt
- app/src/main/res/layout/fragment_survey.xml
- app/src/main/res/layout/row_survey.xml
fixes #3898 
By default, every time "Order By Title" is first selected it sorts A-Z, but when reselecting it again, it becomes Z-A. Also, sort by date options originally sorted by name. I changed this to sort by createdDate, but without the creation date showing, it can sometimes be confusing what date it is sorting by, especially if you have dates showing for completing the survey. What do you all think about showing the creation date (for example, Created on: ...)?
> surveys: smoother sorting (fixes #3898)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
- app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerParentFragment.kt
- app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
fixes #3893 
when navigating to surveys from the home bell, a popup for myLibrary downloads would show
[Screen_recording_20240719_110536.webm](https://github.com/user-attachments/assets/0db45ce3-3a5b-409a-8ce2-9fc3966cb371)
> surveys: smoother check (fixes #3893)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
fixes #3915
this pr will prevent the AndroidRuntimeException from being thrown when you start the activity
> all: better non-activity context handling (fixes #3915)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.kt
fixes #3951
in this pr the onResume and onPause methods are added to manage the playback state. The video playback will pause when the activity is paused and resume when the activity is resumed. This ensures that the video doesn’t continue playing in the background when the activity is not in the foreground.
> resources: smoother video play management (fixes #3951)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-so/strings.xml
- app/src/main/res/values/strings.xml
fixes #4023
Updated the word "زيارة" so it fits arabic standards:
- used as " زيارات" for number in range 3 to 10.
- used as "زيارة" for the rest of the numbers
> all: smoother arabic strings (fixes #4023)

- app/build.gradle
- app/src/main/res/layout/row_course.xml
- app/src/main/res/layout/row_library.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/colors.xml
Added a new colour for empty ratings in dark and light mode.
Changed row_library to be consistent with row_course.
fixes-  #4223
> resources: smoother ratings dark mode (fixes #4223)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
- app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
Moved the logic of Base Fragment stack pop after double back is pressed.  (fixes #4397)
- We were poping base fragment on single back press, which would clear the fragment stack displaying white screen.
https://github.com/user-attachments/assets/489f783d-6afe-43de-a778-4b6bdfc8152d
> dashboard: smoother close (fixes #4397)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
-  fixes #4417
- Fetches RealmStepExam data based on the name of survey
- Opens a AdapterMySubmission for that particular stepExam id.
https://github.com/user-attachments/assets/8fc99ed6-8f92-4ed5-8425-2b6148800b3b
> all: clickable survey notifications (fixes #4417)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
- app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
Fix: #3955 
Case 1: more than 1 file to download - disable `Finish` button
https://github.com/user-attachments/assets/921ad77c-1eb0-4afa-8a62-9f1060866a1e
Case 2: only 1 file to download - `Finish` button visible 
https://github.com/user-attachments/assets/61d6b7dc-dcc2-4c6c-80bd-a32f1080fb25
> all: smoother download (fixes #3955)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
- app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
- fixes #4532 
- Now for the button, we check if an entry from the current user exists with id of exam and course id
- While submitting we priortize the use of examId+@+courseId  , instead of the earlier id + examId
- All step exams have a course id and an exam id
[Take, Retake Test.webm](https://github.com/user-attachments/assets/a33ab2d8-d262-4ede-9820-5a1b894bbae6)
> courses: smoother retake test (fixes #4532)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
- fixes #4608
- Introduced a new function for checking existing submissions of questions and surveys, removed repeated logic.
[Record Survey Resolve.webm](https://github.com/user-attachments/assets/56982071-4531-4774-9375-2b1389689641)
> courses: smoother survey retake (fixes #4608)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
- app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
- app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
> sync: smoother background thread (fixes #4638)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
> courses: smoother tests dark mode (fixes #4646)

- app/build.gradle
- app/src/main/res/layout/alert_create_team.xml
- fixes #4665
- added background color as hintColor
> teams: smoother team edit dark mode (fixes #4665)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
fixes #4663
change 
using a try-finally block to ensure that the realm instance is always closed
> all: smoother realm handling (fixes #4663)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
- app/src/main/res/layout/item_team_list.xml
- fixes #4666 
- Combined edit team and waiting icon behavior.
[teamListAlignment.webm](https://github.com/user-attachments/assets/6ea6d06f-225c-43c9-96d4-e8cc2f6ed2fb)
> teams: smoother list icons (fixes #4666)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
- fixes #4757
-  if submission id has stepexam id @ course id, I am extracting stepexam id from it to get the step exam object
> all: smoother surveys status (fixes #4757)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.kt
- fixes #4788
- Previously the position element was being initialized on view Creation which would change the list size
- Now the position is fetched dynamically onClick instead of initializing at the onCreation.
[Fixed crash of accept reject.webm](https://github.com/user-attachments/assets/f77417e8-7871-4b48-a58e-529f83096053)
> teams: smoother joining (fixes #4788)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
- app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.kt
> all: less build: warnings is more (fixes #4820)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
fixes #4861
Added SupervisorJob to prevent coroutine cancellation from affecting siblings
Added proper coroutine error handling with try-catch
Kept Main thread operations as brief as possible
> sync: smoother exceptions (fixes #4861)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
- app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-so/strings.xml
- app/src/main/res/values/strings.xml
> dashboard: smoother translations (fixes #4923)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
- fixes #4949 
- teams list initially is sorted on creation
- on searching team name users team are also sorted
> teams: smoother list (fixes #4949) 

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
fixes #4958
leveraged the Activity's context through activity reference instead of requireContext() to prevent crashes when context is not added
> resources: smoother download dialog (fixes #4958)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/utilities/ServerUrlMapper.kt
fixes #5009
replaced the restrictive regular expression with a more robust and reliable method to extract the base URL using Uri.parse
> sync: smoother cloudcommunity mapping (fixes #5009)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt
- app/src/main/res/layout/fragment_finance.xml
- fixes #5007
- hiding filter elementds when no data
- visible no data message
> teams: smoother finances default (fixes #5007)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
- app/src/main/res/layout/add_note_dialog.xml
> chat: smoother share note dark mode (fixes #5119)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
- app/src/main/res/values/strings.xml
#5132 
Add CANCEL button in survey dialog next to OK button
> dashboard: smoother survey reminder cancel (fixes #5132)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/enterprises/ReportsFragment.kt
fixes #5142 
hide the export csv button when the list is empty. 
https://github.com/user-attachments/assets/a5708f4d-3acc-4ea2-874e-5c39aca5e5c4
> enterprises: smoother csv export (fixes #5142)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
- app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
- app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
fixes #5226 
this pull request fixes the search both in courses and library
https://github.com/user-attachments/assets/b27022df-c782-496e-abdb-a33725408d61
https://github.com/user-attachments/assets/720ca39f-1b5e-4ee2-bbf9-35e638416373
> resources: smoother search (fixes #5226)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/community/HomeCommunityDialogFragment.kt
- app/src/main/res/layout/fragment_news.xml
- fixes #5169
- implemented bottom sheet as to override its default implementation to block the scrollable on smaller screens
- Test community  bottom sheet with / without sync
- Testing community section 
- device: pixel , size: 5' , api: 35
[small screen community.webm](https://github.com/user-attachments/assets/0413dce9-cada-4a6b-84ea-a10d8ed97650)
- device size: 6.6 inch screen
[bottom sheet behaviour.webm](https://github.com/user-attachments/assets/3bf76163-d61e-49ac-920c-b8f020d00753)
> login: smoother voices bottom drawer (fixes #5169)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
- fixes #5090 
- no of days since last sync are 20116 when we clear data. 
- If no of days are within 356 then show dialog or else do not
1) Initial Sync 
[initial sync.webm](https://github.com/user-attachments/assets/06f0c40d-5cd6-4735-a076-ac4d223107e9)
2) Clear Data Sync
[clear_data_sync.webm](https://github.com/user-attachments/assets/174b667e-9ffb-4ed3-9bc8-14e860e58887)
> login: smoother clearing dialog (fixes #5090)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
fixes #5256
this pr makes the getMinApk process faster with about 5 seconds due to impelmenting concurrent execution (parallel  server checks instead of sequential) and minimizes UI freezing by isolating IO operations from Main.
> sync: smoother cloudcommunity check (fixes #5256)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
- app/src/main/res/layout/expandable_list_grand_child_item.xml
- app/src/main/res/layout/grand_child_recyclerview_dialog.xml
> teams: smoother chat share dark mode (fixes #5281)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
fixes #5298
This pr ensures realm instance is always available during team selection realm transactions
> teams: smoother selections (fixes #5298)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
- app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
- app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
fixes #5300
this pr does not show file not found error for downloads triggered during sync and also creates log with of the file with the error
> sync: smoother error handling (fixes #5300)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
- app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
fixes #5307
pr resolves issue by
- Opening a new Realm instance on the background thread
- Close it after the transaction completes
- Ensure the callback is posted on the main thread
> sync: smoother realm threads (fixes #5307)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
fixes #5318
this was a stacktrace during the sync where we have some downloads in the background so you can initiate a sync and check logcat if you see the log, also test if you are able to download a resource in courses and resources
> sync: smoother downloads execution (fixes #5318)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
- app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
- app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
- app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
- app/src/main/res/layout/fragment_user_information.xml
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-so/strings.xml
- app/src/main/res/values/strings.xml
fixes #5348
Focus on getting the gender and age post survey, hide other fields but can still be filled
[Screen_recording_20250225_174940.webm](https://github.com/user-attachments/assets/7d18d86b-67ad-490f-a684-ac26bbe1fee7)
> teams: smoother survey submissions (fixes #5348)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
fixes #5484
other two missing buttons are as a result of issue in https://github.com/open-learning-exchange/myplanet/issues/5486#issue-2920463267
> teams: smoother survey submission (fixes #5484)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
fixes #5479 
initial ordering is preserved after the text in the search bar is cleared 
https://github.com/user-attachments/assets/7d57f2ad-2fe7-4713-943e-b6e6c1dd4b72
> teams: smoother search (fixes #5479)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
fixes #5478 
survey order by title was case sensitive all the survey's with lowercase were shown at the end of the list.
> teams: smoother survey order title (fixes #5478)

- app/build.gradle
- app/src/main/res/layout/fragment_chat_history_list.xml
Changes the checkbox and text to lighter color in dark mode.
Note*: This issue got fixed before and it happened again.
fixes #5499
> chat: smoother search dark mode (fixes #5499)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
fixes #5676
uses a serverAvailabilityCache (ConcurrentHashMap) to store server availability status with timestamps and checks if there's a cached result less than 30 seconds old before making a network request which helps reduce network overhead
Users get faster responses when the cache is valid, rather than waiting for network calls every time
> sync: smoother caching (fixes #5676)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
fixes #5686
Priority groups:
1. User is team leader first
2. User is team member second
3: User is not a member
all groups sub sorting with descending numver of visits
[Screen_recording_20250415_144955.webm](https://github.com/user-attachments/assets/90087097-4f42-440c-a7ff-cadfe4d6a9f9)
> teams: smoother members priority sorting (fixes #5686)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ne/strings.xml
- app/src/main/res/values-so/strings.xml
- app/src/main/res/values/strings.xml
fixes #5702
the app was crashing if the user previously declined the audio permission and than tried to create the audio resource.
Now if the user has denied the permission before, they would be negvigated to the settings where they can change the permissions.
https://github.com/user-attachments/assets/926d01ee-afaa-4158-949f-db652ee1d886
> resources: smoother recording audio permissions (fixes #5702)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
fixes #5652 
before this pr the empty start and end time for event created on myplanet had wrong placeholders for planet.
> teams: smoother calendar event creation (fixes #5652)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
- app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
- app/src/main/res/layout/fragment_take_exam.xml
fixes #5831
Enable back and forth navigation to allow user to edit/confirm responses before finishing survey. 
[Screen_recording_20250515_162136.webm](https://github.com/user-attachments/assets/9f4831fc-ad75-472e-99fa-d9f105775959)
> teams: smoother survey navigation (fixes #5831)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
fixes #5398
notification sound will only be heard at the completion of all downloads that were on queue
attempts to resolve this on https://github.com/open-learning-exchange/myplanet/pull/5410
> all: smoother downloads notifications (fixes #5398)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
fixes #6014
show message of inactive providers. Scenario testable on planet uriur
[Screen_recording_20250619_134507.webm](https://github.com/user-attachments/assets/a69020e9-cbdb-468c-bb61-540932543584)
> chat: smoother provider availability (fixes #6014)

- app/build.gradle
- gradle.properties
This change addresses several issues to fix the local build environment and significantly improve build performance.
Key changes:
- Add `local.properties` to define the Android SDK path, fixing the "SDK location not found" error.
- Enable the JVM's Parallel Garbage Collector for Gradle to improve performance.
- Refactor the `generateVersionsXml` task to be compatible with Gradle's configuration cache.
These changes result in a successful build and a dramatic reduction in build times. The incremental build time was reduced from ~5 minutes to just a few seconds.
> Fix and optimize Android build environment

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
fixes #7402
1. Moved database operation off main thread: Replaced synchronous beginTransaction()/commitTransaction() with executeTransactionAsync() to prevent the 2.5-second UI freeze.
2. Fixed thread access violations: Extracted data from RealmObjects (model and item) on the main thread before the async block, since Realm objects can't be accessed across
threads.
> resources: smoother opening (fixes #7402)

- app/build.gradle
- app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
- app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
fixes #7498
```
- Moved userModel access to main thread before the async transaction
- Eliminated the createUser(realm) call that was causing thread safety issues
- Directly create and populate RealmOfflineActivity in the background transaction using extracted data
```
> login: smoother offline asyncing (fixes #7498)
