open-learning-exchange/myplanet

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt

chat: smoother api interaction (fixes #3388)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseMemberFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/TeamCourseFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
app/src/main/res/layout/fragment_life.xml
app/src/main/res/layout/fragment_my_course.xml
app/src/main/res/layout/fragment_my_library.xml
app/src/main/res/layout/fragment_news.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

all: source driven notification (fixes #3389)

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterMyProgress.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterProgressGrid.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterSteps.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseProgressActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesPagerAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/MyProgressFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/resources/AdapterResource.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/AdapterTeamCourse.kt
app/src/main/res/layout/activity_course_progress.xml
app/src/main/res/layout/fragment_course_detail.xml
app/src/main/res/layout/fragment_course_step.xml
app/src/main/res/layout/fragment_my_progress.xml
app/src/main/res/layout/fragment_take_course.xml

courses: more consistent naming (fixes #3395)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/DatabaseService.kt
app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt

fixes #3398
this pr add initialization and default configuration in init and add realm log for better realm error logging as advised by realm team
https://github.com/realm/realm-java/issues/7879#issuecomment-2069630928

all: new realm initialization (fixes #3398)

---

app/build.gradle
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #3403
this pr ensures all string files match in terms of number of strings and positioning

all: translations streamlined (fixes #3403)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.kt
app/src/main/java/org/ole/planet/myplanet/ui/community/LeadersFragment.kt

community: display leaders (fixes #1807)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt

fixes #3243
this pr attempts to log a better error message for crash

all: better realm log (fixes #3243)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmMeetup.kt
app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.kt
app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityPagerAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/AdapterMeetup.kt
app/src/main/res/layout/fragment_enterprise_calendar.xml
app/src/main/res/layout/item_meetup.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

community: show events on calendar (fixes #3407)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.kt
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt

chat: show only mine (fixes #3409)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt

chat: smoother context flow (fixes #3411)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/res/layout/dialog_server_url_.xml

sync: better ssl config (fixes #3415)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/res/layout/dialog_server_url_.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

sync: add clear data button (fixes #3416)

---

app/build.gradle
app/src/main/AndroidManifest.xml

fixes #3128
[Screen_recording_20240429_141644.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/f5be4dc4-d4aa-412e-8f9f-6843c381925c)

chat: reactive virtual keyboard (fixes #3128)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmAchievement.kt

mylife: stabler achievements save (fixes #3429)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/AdapterResource.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt

resources: date is now long (fixes #3422)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt

courses: date is now long (fixes #3423)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
app/src/main/res/layout/fragment_feedback_list.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

accessibility: improve content labelling (fixes #3436)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmAchievement.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmApkLog.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmCertification.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmCourseActivity.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmCourseProgress.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmFeedback.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealthPojo.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmMyLife.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmMyPersonal.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmRemovedLog.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmResourceActivity.kt
app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.kt
app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/AdapterMyPersonal.kt
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterHealthExamination.kt
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt

fixes #3443
this pr refactor some realm models to use simpler getters and setters

all: simpler `get`s and `set`s (fixes #3443)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

fixes #3447
https://github.com/open-learning-exchange/myplanet/assets/64019708/c5ca33e4-1f6f-459b-9e61-425987fb8873

sync: never as i18n message (fixes #3447)

---

app/build.gradle
app/src/main/AndroidManifest.xml

fixes #3450
`pdf`
https://github.com/open-learning-exchange/myplanet/assets/64019708/287af214-7a1e-48e5-b619-6761b96278c3
`audio`
https://github.com/open-learning-exchange/myplanet/assets/64019708/6c286efd-af9b-4e5e-89ee-76eef074eef8
`video`
https://github.com/open-learning-exchange/myplanet/assets/64019708/e5c4ad58-0192-4185-a8c1-1292369afc0c

all: smoother resourses when orientation changes (fixes #3450)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
app/src/main/java/org/ole/planet/myplanet/service/AudioRecorderService.kt
app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt
app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/MyActivityFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.kt

actions: less warnings is more (fixes #3459)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/java/org/ole/planet/myplanet/utilities/Constants.kt
app/src/main/java/org/ole/planet/myplanet/utilities/LocaleHelper.kt

fixes #3456
this pr also reduces number of clicks to change language
https://github.com/open-learning-exchange/myplanet/assets/64019708/c221d28c-7b82-40e7-ab3a-7f57daff0642

login: button shows apps language (fixes #3456)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt

courses: accurate progress success (fixes #3463)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt

fixes #3461
https://github.com/open-learning-exchange/myplanet/assets/64019708/12ab2d10-2a83-4cd0-8369-81e85360a30f

all: smoother back press (fixes #3461)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

login: show only active teams (fixes #3266)

---

app/build.gradle
app/src/main/res/layout/fragment_take_course.xml

fixes #3467
https://github.com/open-learning-exchange/myplanet/assets/64019708/b6c673dc-c6b4-41a8-b913-60d88eaecd6f

courses: smoother step details (fixes #3467)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

sync: smoother realm handling (fixes #3473)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

fixes #3475
https://github.com/open-learning-exchange/myplanet/assets/64019708/29410779-5996-4384-a82b-69dca3384a76

login: sync before guest (fixes #3475)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

sync: even better realm handling (fixes #3479)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt

sync: revive crash logs (fixes #3491)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
app/src/main/res/layout/fragment_take_course.xml

courses: show title once (fixes #3492)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/viewer/CSVViewerActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/viewer/ImageViewerActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/viewer/MarkdownViewerActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/viewer/TextFileViewerActivity.kt

resources: show only filename (fixes #3493)

---

app/build.gradle
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #3497 
Changed the strings.xml files for English, Spanish, French, Somali for the specific config menu keywords "Sync Now" "About" "Disclaimer" "Settings" "Logout" and made them all lowercase.

all: burger menu all lowercase (fixes #3497)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt

fixes #3501
https://github.com/open-learning-exchange/myplanet/assets/64019708/7208e7d0-d6d8-4596-a088-cf3fc2746383

dashboard: smoother internal mycourses sync (fixes #3501)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt

dashboard: smoother internal myteams sync (fixes #3506)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/java/org/ole/planet/myplanet/utilities/NetworkUtils.kt

fixes #3505
https://github.com/open-learning-exchange/myplanet/assets/64019708/b341a800-3d37-4d88-9afe-97feb936b150

dashboard: sync ability coded into avatars surround color (fixes #3505)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt

dashboard: smoother visits sync (fixes #3511)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt

fixes #3510
https://github.com/open-learning-exchange/myplanet/assets/64019708/94db013c-388f-4e7e-a3ce-20d72f54c409

courses: check missing resources only when joined (fixes #3510)

---

app/build.gradle
app/src/main/res/layout/row_library.xml

resources: better list display (fixes #3517)

---

app/build.gradle
app/src/main/res/layout/row_course.xml

courses: better ui (fixes #3516)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerParentFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseProgressActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.kt
app/src/main/java/org/ole/planet/myplanet/ui/mylife/LifeFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/submission/MySubmissionFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt

fixes #3518
this pr we us safe null operator `?.` instead of not null assertion `!!`

all: safer null handling (fixes #3518)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt

login: smoother transition to dashboard (fixes #3524)

---

app/build.gradle
app/src/main/res/layout/fragment_course_detail.xml

courses: smoother ui (fixes #3528)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt

dashboard: smoother realm writing (fixes #3540)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.kt

resources: cleaner video management (fixes #3537)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt

resources: improve toast messages (fixes #3530)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/viewer/AudioPlayerActivity.kt

resources: better audio name (fixes #3504)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityTabFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/BaseTeamFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt

community: stabler guest access (fixes #3551)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #3550 
https://github.com/open-learning-exchange/myplanet/assets/59347000/05c0b682-740a-4135-95ea-35936a44390c

chat: for learners only (fixes #3550)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
app/src/main/res/layout/row_course.xml

courses: more responsive details (fixes #3553)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt

fixes #3547 
https://github.com/open-learning-exchange/myplanet/assets/59347000/0cd7f88d-70a4-4b5c-b3a4-8bc72db8abd9

courses: steps only for learners (fixes #3547)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt

fixes #3549 
[issue# 3549.webm](https://github.com/open-learning-exchange/myplanet/assets/112584985/bb195633-b129-419f-8aab-4fdb77787bd9)

teams: only learner can join & create

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt

sync: divide for smoother login (fixes #3562)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/viewer/AudioPlayerActivity.kt
app/src/main/res/layout/activity_audio_player.xml

fixes #3548 
after fix it displays the name listed in library:

resources: show also audio titles (fixed #3548)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt

fixes #3563
https://github.com/open-learning-exchange/myplanet/assets/64019708/c42e8a0e-71f2-413e-9675-40c36de4b5d3

mycourses: show downloadable courses resources (fixes #3563)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt

fixes issue #3552 
[issue #3552.webm](https://github.com/open-learning-exchange/myplanet/assets/112584985/7291dcb9-8fca-47e0-8ed1-2be36d473164)

mycourses: show buttons only when populated (fixes #3552)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #3569
[issue #3569.webm](https://github.com/open-learning-exchange/myplanet/assets/112584985/8303abae-6025-4d95-a2f3-bf0bdb8a639c)
Needs translations for the new string.

mycourses: text changes based on selections (fixes #3569)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt

courses: only learners can join (fixes #3568)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
app/src/main/java/org/ole/planet/myplanet/utilities/Markdown.kt
app/src/main/res/layout/fragment_services.xml

fixes #2256
https://github.com/open-learning-exchange/myplanet/assets/64019708/13f1715f-cb02-412f-918b-7bea01f9fcec

community: default text if empty (fixes #2256)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/BaseTeamFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt

fixes #3577
https://github.com/open-learning-exchange/myplanet/assets/64019708/e07848b6-906a-4f08-bb8d-58078b81db3b

teams: use right data (fixes #3577)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt

fixes #3574 
[issue #3574.webm](https://github.com/open-learning-exchange/myplanet/assets/112584985/027db017-3f84-4d21-a70e-e6b85fbd8eea)

mylibrary: context-based activated remove button (fixes #3574)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
app/src/main/res/layout/row_news.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

news: show shared chats (fixes #3582)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

login: refactor (fixes #3595)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt

Fixes #3604 
updated ACTION_INSTALL_PACKAGE to Intent.ACTION_VIEW

actions: less warnings is more (fixes #3604)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt

fixes #3609 
updated getSerializable(string) to getSerializable(string, class)

actions: less warnings is more (fixes #3609)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
app/src/main/java/org/ole/planet/myplanet/utilities/CameraUtils.kt

all: use `android.hardware.camera2.*` (fixes #3619)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/FileUploadService.kt
app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt

actions: less warnings is more (fixes #3627)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt

dashboard: smoother lifecycle management (fixes #3629)

---

.github/workflows/android-release.yml
app/build.gradle

actions: better discord success message (fixes #3633)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt

sync: trim lite version (fixes #3656)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.kt

feedback: smoother dialog (fixes #3632)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt

actions: less warnings is more (fixes #3626)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/MyActivityFragment.kt

actions: less warnings is more (fixes #3640)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityPagerAdapter.kt

actions: less warnings is more (fixes #3665)

---

.github/workflows/android-build.yml
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/AndroidManifest.xml.lite
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt

actions: less warnings is more (fixes #3654)

---

app/build.gradle

actions: only one language bundle (fixes #3678)

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt

teams: smoother plan (fixes #3690)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt

dashboard: safer fragment transactions (fixes #3693)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt

courses: smoother list (fixes #3702)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt

teams: stabler resources list (fixes #3719)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt

fixes #3698 
[issue #3698.webm](https://github.com/open-learning-exchange/myplanet/assets/112584985/1fa40db5-b8bf-4fbd-bd61-45d04b90a92a)

login: smoother language selection (fixes #3698)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/ApiClient.kt

actions: less warnings is more (fixes #3722)

---

.github/workflows/android-release.yml
app/build.gradle

actions: smoother manual release (fixes #3712)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/submission/MySubmissionFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
app/src/main/res/layout/fragment_my_submission.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

surveys: smoother empty list (fixes #3724)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseDialogFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/rating/RatingFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/CollectionsFragment.kt
app/src/main/res/layout/fragment_feedback.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/styles.xml

fixes #3729 
Found the code for the deprecated theme [here](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/res/res/values/themes_holo.xml).
Found the code for the dimens related to the theme [here](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/res/res/values/dimens.xml).

all: smoother dialogs (fixes #3729)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
app/src/main/res/layout/fragment_chat_history_list.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #3725 
Test Instructions:
Add "filteredHistoryList.clear()" before line 71 of ChatHistoryListFragment.kt.

chats: smoother empty history (fixes #3725)

---

LICENSE
app/build.gradle

all: add LICENSE (fixes #3751)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/helpwanted/HelpWantedFragment.kt
app/src/main/java/org/ole/planet/myplanet/utilities/JsonParserUtils.kt

fixes #3749 
also fixed the same issue in HelpWantedFragment.kt

all: less warnings is more (fixes #3749)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

fixes #3755
[Screen_recording_20240702_173047.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/33f0295d-e90f-4b50-9ad0-d3ef5251e798)

settings: smoother clear data (fixes #3755)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/TeamListAdapter.kt
app/src/main/res/layout/activity_login.xml

fixes #3745
[issue #3745.webm](https://github.com/open-learning-exchange/myplanet/assets/112584985/88a4e3ac-f7fc-496f-be4f-39929569c0a1)

login: smoother fast login list (fixes #3745)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

actions: less warnings is more (fixes #3699)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/callback/ProgressBroadcastReceiver.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt

actions: less warnings is more (fixes #3759)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/helpwanted/HelpWantedFragment.kt

actions: less warnings is more (fixes #3764)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt

fixes #3645
test using roboscripts choose this as test device

resources: safer transactions  (fixes #3645)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.kt
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite

fixes #3784
[Screen recording 2024-07-05 16.56.17.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/62e428e9-c737-4bdd-a09e-37964b07f2c5)

chat: smoother refresh (fixes #3784)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt

courses: smoother steps (fixes #3789)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/BaseTeamFragment.kt

actions: less warnings is more (fixes #3795)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt

all: ensure compatibility (fixes #3774)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt

dashboard: stabler fragments (fixes #3770)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt

login: smoother team list (fixes #3771)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmNotification.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

actions: smoother translation files (fixes #3793)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/AdapterNotification.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

dashboard: smoother texts (fixes #3816)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

all: log syncs (fixes #3819)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

settings: smoother reset (fixes #3822)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt

mylife: stabler list (fixes #3821)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt

sync: smoother large data (fixes #3855)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.kt
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt

fixes #3832
[Screen_recording_20240715_104841.webm](https://github.com/user-attachments/assets/72125054-8160-470f-85e9-dbe8205e18ba)

chat: smoother most recently used list (fixes #3832)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
app/src/main/java/org/ole/planet/myplanet/utilities/VersionUtils.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

teams: smoother messages (fixes #3592)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

mylife: smoother dictionary texts (fixes #3835)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/ExpandableListAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt

community: smoother news texts (fixes #3859)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/onBoarding/OnBoardingActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/AdapterResource.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/CollectionsFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

resources: smoother texts (fixes #3861)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt

community: smoother news view (fixes #3828)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.kt

teams: better permissions (fixes #3813)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt

fixes #3834 
https://github.com/user-attachments/assets/6c53b493-fc67-497a-b506-e1321cdb6265

community: more reactive news (fixes #3834)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt

fixes #3833
[Screen_recording_20240716_114810.webm](https://github.com/user-attachments/assets/98a2e02c-42df-466a-a33c-6f7b8796c3db)

surveys: overview on completion (fixes #3833)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/AboutFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/submission/AdapterMySubmission.kt
app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

sync: smoother texts (fixes #3864)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/BaseTeamFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/TeamCourseFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/JoinedMemberFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MemberDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/AdapterTeamResource.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/AdapterTask.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

teams: smoother texts (fixes #3869)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt

fixes #3871
[enterprise fix.webm](https://github.com/user-attachments/assets/30d96383-c072-422b-8937-8cf65a7f590a)

teams: smoother messages (fixes #3871)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt

courses: stabler filter (fixes #3858)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt

fixes #3882
[Screen_recording_20240718_082941.webm](https://github.com/user-attachments/assets/7bfe0f8d-8020-4c34-9d68-4c57edde7155)

login: save by learners username (fixes #3882)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt

courses: ratings only by learners (fixes #3876)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/TeamListAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

learner: smoother profile texts (fixes #3879)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/viewer/CSVViewerActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/viewer/ImageViewerActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/viewer/MarkdownViewerActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/viewer/TextFileViewerActivity.kt

resources: smoother viewer texts (fixes #3901)

---

app/build.gradle
app/src/main/res/layout/fragment_vital_sign.xml

mylife: smoother myhealth (fixes #3894)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
app/src/main/java/org/ole/planet/myplanet/utilities/Constants.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref.xml

settings: courses always (fixes #3907)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/utilities/Constants.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref.xml

settings: always achievements (fixes #3909)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt
app/src/main/java/org/ole/planet/myplanet/utilities/Constants.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref.xml

settings: always auto update (fixes #3908)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
build.gradle

fixes #3886
- use kotlin serialization instead of gson for more efficient memory usage and speed

sync: smoother serialization (fixes #3886)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt

teams: show name and type (fixes #3918)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
app/src/main/res/xml/pref.xml

settings: dark mode off by default (fixes #3929)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt

teams: smoother strings (fixes #3926)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseActivity.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
app/src/main/java/org/ole/planet/myplanet/base/BaseMemberFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerParentFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt

all: less base warnings is more (fixes #3958)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/callback/OnHomeItemClickListener.kt
app/src/main/java/org/ole/planet/myplanet/callback/OnMyLifeItemSelected.kt
app/src/main/java/org/ole/planet/myplanet/callback/ProgressBroadcastReceiver.kt
app/src/main/java/org/ole/planet/myplanet/callback/UploadAttachmentListener.kt

all: less callback warnings is more (fixes #3961)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
app/src/main/res/values/styles.xml

fixes #3935 
[Screen_recording_20240726_103333.webm](https://github.com/user-attachments/assets/75deb1f8-5d46-4c11-bfa9-b7e540791558)

settings: smoother languages in toolbar (fixes #3935)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/ApiClient.kt
app/src/main/java/org/ole/planet/myplanet/datamanager/FileUploadService.kt
app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.kt
app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt

all: less datamanager warnings is more (fixes #3970)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt

fixes #3980
[Screen_recording_20240731_204302.webm](https://github.com/user-attachments/assets/9ce598a7-d724-401f-b1c5-d712bec6f0a6)

teams: smoother creation and search (fixes #3980)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.kt
app/src/main/java/org/ole/planet/myplanet/service/AudioRecorderService.kt
app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt
app/src/main/java/org/ole/planet/myplanet/service/StayOnlineWorker.kt
app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.kt
app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

all: less service warnings is more (fixes #3983)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt

fixes #3987
[Screen_recording_20240801_174658.webm](https://github.com/user-attachments/assets/8145f88d-5f9e-4561-85ca-9643a5d5ed96)

community: smoother news with shared chats (fixes #3987)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFilterFragment.kt
app/src/main/res/layout/fragment_library_filter.xml

fixes #3985
having trouble setting the width of the filter to be consistent

resources: smoother filter layout (fixes #3985)

---

app/build.gradle
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

all: consistent left menu (fixes 3991)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
app/src/main/res/layout/fragment_my_submission.xml
app/src/main/res/layout/fragment_take_exam.xml
app/src/main/res/layout/item_radio_btn.xml
app/src/main/res/layout/row_mysurvey.xml
app/src/main/res/layout/row_survey.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values-night/styles.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

surveys: smoother dark mode (fixes #3995)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
app/src/main/res/layout/add_meetup.xml
app/src/main/res/layout/alert_task.xml
app/src/main/res/layout/fragment_team_task.xml
app/src/main/res/layout/my_library_alertdialog.xml
app/src/main/res/layout/row_member_request.xml
app/src/main/res/layout/row_task.xml
app/src/main/res/layout/row_team_resource.xml
app/src/main/res/values-night/styles.xml
app/src/main/res/values/styles.xml

teams: smoother dark mode (fixes #3993)

---

app/build.gradle
app/src/main/res/layout/row_news.xml

chat: smoother dark mode (fixes #4019)

---

app/build.gradle
app/src/main/res/layout/fragment_course_step.xml
app/src/main/res/layout/fragment_rating.xml
app/src/main/res/layout/row_steps.xml

courses: smoother dark mode (fixes #3999)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
app/src/main/res/xml/pref.xml

all: default dark mode to follow system (fixes #4026)

---

app/build.gradle
app/src/main/res/layout/fragment_feedback_list.xml
app/src/main/res/layout/row_feedback.xml

feedback: smoother columns (fixes #4028)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/res/layout/dialog_server_url_.xml

login: only one team list (fixes #4097)

---

app/build.gradle
app/src/main/res/layout/row_life.xml

mylife: smoother dark mode rows (fixes #4090)

---

app/build.gradle
app/src/main/res/values/strings.xml

mycourses: better case consistency (fixes #4079)

---

app/build.gradle
app/src/main/res/drawable/custom_border.xml
app/src/main/res/layout/fragment_my_library.xml

resources: smoother filter dark mode (fixes #4088)

---

app/build.gradle
app/src/main/res/layout/fragment_collections.xml

fixes #4087
[Screen_recording_20240812_100208.webm](https://github.com/user-attachments/assets/ce3438b6-eab9-42bc-a74e-1aec7eeb37b4)

resources: smoother dark mode filter (fixes #4087)

---

app/build.gradle
app/src/main/res/layout/fragment_feedback.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml

fixes #4118
[Screen_recording_20240812_112650.webm](https://github.com/user-attachments/assets/919ea345-3d26-4795-bb54-15e4463228f8)

teams: smoother dark mode feedback (fixes #4118)

---

app/build.gradle
app/src/main/res/layout/fragment_collections.xml
app/src/main/res/layout/fragment_library_filter.xml

resources: smoother filter dark mode (fixes #4110)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
app/src/main/res/layout/fragment_vital_sign.xml
app/src/main/res/layout/row_examination.xml

mylife: smoother myhealth dark mode (fixes #4091)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

sync: more planet servers (fixes #4131)

---

app/src/main/res/layout/report_list_item.xml

enterprises: smoother dark mode reports (fixes #4083)

---

app/build.gradle
app/src/main/res/layout/fragment_news.xml

fixes #4178
[Screen_recording_20240816_103529.webm](https://github.com/user-attachments/assets/e3df14a2-eb9f-4374-80db-7a3854d47800)

teams: add message dark mode (fixes #4178)

---

app/build.gradle
app/src/main/res/layout/row_feedback.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml

feedback: smoother rows dark mode (fixes #4162)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt

resources: cleaner title (fixes #4176)

---

app/build.gradle

all: less build warning is more (fixes #4175)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
app/src/main/res/layout/fragment_user_information.xml

surveys: user information dark mode (fixes #4180)

---

app/build.gradle
app/src/main/res/layout/fragment_team.xml
app/src/main/res/layout/layout_search.xml

all: smoother search bar (fixes #4174)

---

app/build.gradle
app/src/main/res/layout/fragment_user_information.xml

surveys: smoother birthday dark mode (fixes #4185)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
app/src/main/res/layout/fragment_user_information.xml
app/src/main/res/layout/spinner_item.xml

surveys: smoother learner level (fixes #4188)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/AdapterTask.kt

teams: smoother dark mode tasks (fixes #4190)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt

all: smoother dialogs (fixes #4205)

---

app/build.gradle
settings.gradle

all: update `settings.gradle` (fixes #4214)

---

.github/workflows/android-release.yml
app/build.gradle

fixes #4208 
put link between `<>` to avoid link preview taking too much space and cluttering the channel.

actions: smoother discord notification (fixes #4208)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
app/src/main/java/org/ole/planet/myplanet/utilities/CameraUtils.kt

fixes #4238
[Screen_recording_20240823_153354.webm](https://github.com/user-attachments/assets/f427b276-0cde-4a14-b8ab-2786dd9df676)

courses: smoother exam retakes (fixes #4238)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.kt

mylibrary: less build warnings is more (fixes #4224)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt

courses: smoother mycourses dark mode (fixes #4229)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt

sync: smoother dialog (fixes #4242)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt
app/src/main/res/layout/alert_my_personal.xml

mylife: smoother personals dark mode files (fixes #4232)

---

app/build.gradle
app/src/main/res/layout/fragment_my_submission.xml

Added textColor in my_submission_fragment. 
fixes #4222

mylife: smoother submission dark mode (fixes #4222)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
app/src/main/res/layout-large-land/card_profile_bell.xml
app/src/main/res/layout-normal-land/card_profile_bell.xml
app/src/main/res/layout-xlarge-land/card_profile_bell.xml
app/src/main/res/layout/card_profile.xml
app/src/main/res/layout/card_profile_bell.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

dashboard: update visits (fixes #4247)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/AdapterMyPersonal.kt

mylife: smoother personals dark mode dialog (fixes #4250)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerParentFragment.kt

all: less build warnings is more (fixes #4236)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt

sync: smoother network check (fixes #4256)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt

fixes #3900
[Screen_recording_20240827_151917.webm](https://github.com/user-attachments/assets/b45b4949-87f7-4f47-8f68-40e9e86438aa)

teams: smoother tasks refreshing (fixes #3900)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
app/src/main/res/layout-large-land/activity_login.xml
app/src/main/res/layout-night/activity_login.xml
app/src/main/res/layout-normal-land/activity_login.xml
app/src/main/res/layout-xlarge-land/activity_login.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref.xml

settings: smoother language dark mode (fixes #4179)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
app/src/main/res/layout/alert_create_team.xml

teams: smoother create dark mode (fixes #4262)(fixes #4263)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #4277
[Screen_recording_20240828_182704.webm](https://github.com/user-attachments/assets/604c4b4c-15a6-4149-b702-a63feee7c693)

resources: smoother guest mode (fixes #4277)

---

app/build.gradle
app/src/main/res/drawable-anydpi/ic_download.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml

Download icon compatible with darkmode 
fixes #4270

resources: smoother download icon (fixes #4270)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt

Hide 'add story' button in community tab when a guest has logged in. (fixes #4276 )

teams: smoother messages guest mode (fixes #4276)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt

dashboard: smoother profiles (fixes #4261)

---

app/build.gradle
app/src/main/res/layout/fragment_finance.xml
app/src/main/res/layout/fragment_news.xml

communities: smoother guest dark mode (fixes #4281)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt

fixes #3831
[Screen_recording_20240829_134757.webm](https://github.com/user-attachments/assets/43c29cd8-27c6-434f-9021-100e1424451a)

teams: smoother message images (fixes #3831)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #4290 
[Screen_recording_20240829_154703.webm](https://github.com/user-attachments/assets/57a3230c-3bc8-487e-bbea-306886ff3d60)

all: smoother guest conversion to member (fixes #4290)

---

app/build.gradle
app/src/main/res/layout/fragment_discussion_list.xml

teams: smoother chat dark mode (fixes #4292)

---

app/build.gradle
app/src/main/res/layout/fragment_chat_history_list.xml

teams: new chat dark mode (fixes #4293)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite

changed the popup style to match the popup thought application.
fixes #4294

dashboard: smoother only member (fixes #4294)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt

teams: smoother members dark mode (fixes #4300)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/res/layout/dialog_server_url_.xml

login: smoother sync dark mode (fixes #4306)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt
app/src/main/res/layout/fragment_course_detail.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

courses: smoother translation (fixes #4307)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/TaskNotificationWorker.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterCalendar.kt
app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.kt

teams: smoother calendar translations (fixes #3936)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
app/src/main/res/layout/alert_input.xml

teams: smoother message reply (fixes #4313)

---

app/build.gradle
app/src/main/res/values/strings.xml

settings: strings case consistency (fixes #4315)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt

fixes #4317
[Screen_recording_20240902_192511.webm](https://github.com/user-attachments/assets/f3d4f615-f638-452e-ab0e-910380748f10)

mylife: smoother guest (fixes #4317)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt

resources: smoother mylibrary dark mode (fixes #4322)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt

login: smoother settings error dark mode (fixes #4319)

---

app/build.gradle
app/src/main/res/drawable-anydpi/ic_edit.xml

teams: smoother message reply icon (fixes #4320)

---

app/build.gradle
app/src/main/res/xml/pref.xml

fixes #4334
was mistakenly removed in this rebase https://github.com/open-learning-exchange/myplanet/pull/3850/commits/e68bc5ad9c45c37705f697d6ecdf4fb26b1ca108#diff-e07db3da8edbb3986b4a47a5ca2e99d720f94e7c7eccd420c0208052ecdbf006

settings: download sync files switch (fixes #4334)

---

app/build.gradle
app/src/main/res/values-ar/strings.xml

sync: smoother errors strings (fixes #4333)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt

fixes #4325
[Screen_recording_20240904_185238.webm](https://github.com/user-attachments/assets/47b352a2-eb16-4040-b648-c2537ad5e877)

dashboard: smoother pending surveys list (fixes #4325)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/BaseTeamFragment.kt

teams: smoother base (fixes #4259)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref.xml

Fixes #4302 
https://github.com/user-attachments/assets/d1e83585-f025-49a4-b1d2-38e386f4bf01

settings: smoother translate strings (fixes #4302)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/enterprises/ReportsFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/TeamCourseFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/JoinedMemberFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt

fixes #4310
[Screen_recording_20240905_150923.webm](https://github.com/user-attachments/assets/4f7ad56d-7214-4daf-8acc-5724589acb78)

teams: smoother news images reply (fixes #4310)

---

app/build.gradle
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

resources: smoother calendar (fixes #4328)

---

app/build.gradle
app/src/main/res/layout/report_list_item.xml
app/src/main/res/layout/row_task.xml

enterprises: smoother reports dark mode (fixes #4364)

---

app/build.gradle
app/src/main/res/layout/row_task.xml

teams: smoother task checkboxes (fixes #4396)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt

teams: smoother empty tasks (fixes #4413)

---

app/build.gradle
app/src/main/res/layout/fragment_dictionary.xml

mylife: smoother dictionary dark mode  (fixes #4409)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

fixes #4403
[Screen_recording_20240917_151257.webm](https://github.com/user-attachments/assets/a239964c-9f4f-4d0c-8bb7-fbc2ff892509)

sync: smoother `planet` check (fixes #4403)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
app/src/main/java/org/ole/planet/myplanet/utilities/LocaleHelper.kt

fixes #4348
[langs.webm](https://github.com/user-attachments/assets/e8e20ddf-2af5-4d6a-b574-539fb0f48932)

login: smoother translations (fixes #4348)

---

app/build.gradle
app/src/main/res/layout-night/app_bar_bell.xml
app/src/main/res/layout/app_bar_bell.xml

dashboard: more responsive (fixes #4420) 

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/MyActivityFragment.kt

Fixes: #4408 
Description to support darkmode and better description position.

dashboard: smoother myactivity dark mode (fixes 4408)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/MyActivityFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

dashboard: smoother myactivity translations (fixes #4406)

---

app/build.gradle
app/src/main/res/layout/edit_other_info.xml
app/src/main/res/layout/fragment_community.xml

Delete button was missing tint . So added same tint across application. (fixes #4438)

resources: smoother delete button (fixes #4438)

---

app/build.gradle
app/src/main/res/layout/fragment_course_detail.xml

(fixes #4435)
Rating Bar is consistent across app

resources: smoother rating dark mode (fixes #4435)

---

app/build.gradle
app/src/main/res/layout/fragment_chat_history_list.xml

(fixes #4434)
Added TextColor for darkmode

chats smoother search dark mode (fixes #4434)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

Fixes: #4440 
https://github.com/user-attachments/assets/243d4142-211d-4224-89dd-a2e759adb924

login: smoother manual settings (fixes #4440)

---

app/build.gradle
app/src/main/res/layout/dialog_server_url_.xml

fixes #4445
[synced.webm](https://github.com/user-attachments/assets/f2dec177-f914-4524-ade1-6d96d5f11108)
roboscript autotest
https://github.com/user-attachments/assets/663c3547-4106-4417-81d5-b1deefb1bac6

sync: smoother settings (fixes #4445)(fixes #4448)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt
app/src/main/res/layout/activity_add_examination.xml
app/src/main/res/layout/activity_add_my_health.xml
app/src/main/res/layout/activity_feedback_detail.xml
app/src/main/res/layout/alert_manager_login.xml
app/src/main/res/layout/alert_my_personal.xml
app/src/main/res/layout/alert_reference.xml
app/src/main/res/layout/fragment_add_link.xml
app/src/main/res/layout/fragment_edit_achievement.xml

Edit text consistent across app   (fixes #4443)

resources: smoother edit text dark mode (fixes #4443)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
app/src/main/res/layout/item_ai_response_message.xml
app/src/main/res/layout/item_user_message.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #4450
**`press and hold to copy`**
https://github.com/user-attachments/assets/c81e06f8-eb00-41af-8ee6-65b2dd537ca8

chat: copy messages (fixes #4450)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt

chat: smoother context attachment (fixes #4476)

---

app/build.gradle
app/src/main/res/layout/row_reference.xml

Added day night colors in row_reference.  (fixes #4489)

mylife: smoother references dark mode (fixes #4489)

---

app/build.gradle
app/src/main/res/layout/row_team_resource.xml

teams: smoother resources icon dark mode (fixes #4490)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt

all: smoother notifications (fixes #4457)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite

fixes #4498   #4481
[Screen_recording_20240927_162530.webm](https://github.com/user-attachments/assets/26694c0e-a7d8-4b25-8a03-27b264ddaea3)

all: responsive notifications (fixes #4498)(fixes #4481)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.kt
app/src/main/res/layout/row_life.xml

dashboard: smoother mylife arranging (fixes #4428)

---

app/build.gradle
app/src/main/res/layout/fragment_add_resource.xml

Added darkmode compatible changes.  Open for color scheme suggesions. ( fixes #4491)

dashboard: smoother add resource dialog (fixes #4491)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/AudioRecorderService.kt

dashboard: stabler audio recorder (fixes #4470)

---

app/build.gradle
app/src/main/res/layout/dialog_server_url_.xml

- fixes #4451
- changed width to wrap content
- Removed layout weight
- added padding between text and switch
https://github.com/user-attachments/assets/02ce84bf-74e3-42da-8fa1-e2385d946807

login: smoother configuration (fixes #4451)

---

app/build.gradle
app/src/main/res/layout/fragment_edit_achievement.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

mylife: smoother myachievements strings (fixes #4504)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmApkLog.kt

fixes #4511 
`new login`
`from background launch`
`sync log`

sync: smoother apk logs (fixes #4511)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite

Fixes: #4503 
https://github.com/user-attachments/assets/dba47321-51b5-45fc-8467-074e241b530c

all: smoother navigation (fixes #4503)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmApkLog.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
app/src/main/res/layout/fragment_chat_detail.xml

fixes #4286
[Screen_recording_20241001_182651.webm](https://github.com/user-attachments/assets/7394a370-fbed-4fe5-9211-fe60a76605c3)

all: smoother screen mode (fixes #4286)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt

Fixes: #4460 
https://github.com/user-attachments/assets/40820c2c-887d-407c-91a0-53fddb3136e7

courses: smoother download (fixes #4460)

---

app/build.gradle
app/src/main/res/layout/activity_audio_player.xml
app/src/main/res/values/styles.xml

Darkmode compatible audio player 
- fixes #4509

resources: smoother audio dark mode (fixes #4509)

---

app/build.gradle
app/src/main/res/layout/fragment_course_detail.xml

courses: smoother details (fixes #4522)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt
app/src/main/res/layout/alert_sound_recorder.xml

dashboard: smoother audio recording (fixes #4520)

---

app/build.gradle
app/src/main/res/layout/activity_add_resource.xml
app/src/main/res/values/strings.xml

- fixes #4508 
- Added asterisk on mandatory fields
- edit text bottom line is visible

dashboard: smoother add resources (fixes #4508)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityPagerAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
app/src/main/res/layout/fragment_news.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

teams: smoother voices (fixes #4513)

---

app/build.gradle
app/src/main/res/layout/fragment_achievement.xml
app/src/main/res/layout/fragment_edit_achievement.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

mylife: smoother myachievements translations (fixes #4530)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
app/src/main/res/layout/fragment_course_step.xml
app/src/main/res/values/strings.xml

fixes #4533 
[survey recording.webm](https://github.com/user-attachments/assets/bed4aaf5-9b6d-43fd-acfa-4afbd8ba8b5f)

courses: smoother step survey (fixes #4533)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt

fixes #4037
[darkmode.webm](https://github.com/user-attachments/assets/23b48db1-ce1d-4eb1-b8c8-efad02505ffa)

all: smoother system mode change (fixes #4037)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
app/src/main/res/drawable-anydpi/ic_eye.xml
app/src/main/res/values-night/styles.xml
app/src/main/res/values/styles.xml

- fixes #4527
- added negative button styling

courses: smoother open resource (fixes #4527)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
app/src/main/res/values-night/styles.xml
app/src/main/res/values/styles.xml

- dependent on changes from #4541 
- fixes #4528 
- added theme to CustomAlertDialog

courses: smoother mycourses leaving dark mode (fixes #4528)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt

fixes #4545
[Screen_recording_20241004_131408.webm](https://github.com/user-attachments/assets/5dd7a5a1-8acb-4f03-815d-c3d11257b6e6)

all: storage linked download notifications (fixes #4545)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
app/src/main/res/drawable/baseline_hourglass_top_24.xml

teams: smoother pending icon (fixes #4547)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt

resources: smoother mylibrary dark mode (fixes #4539)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt

courses: smoother mycourses dark mode (fixes #4553)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

- fixes #4554
- Changed the msg to leave instead of delete
- added multilang support

courses: smoother mycourses leaving (fixes #4554)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
app/src/main/res/layout/fragment_home_bell.xml
app/src/main/res/layout/fragment_my_library.xml

fixes #4558
[resources add.webm](https://github.com/user-attachments/assets/60bb4af5-9aa4-4776-a5dd-89d6aafd2ed0)

resources: smoother add button (fixes #4558)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
app/src/main/res/layout/fragment_home_bell.xml
app/src/main/res/layout/fragment_my_course.xml

fixes #4562
[progress.webm](https://github.com/user-attachments/assets/dffe52c6-b6d8-41af-8a91-4ec8019c7514)

courses: smoother mycourses progress (fixes #4562)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
app/src/main/res/layout/fragment_home_bell.xml

fixes #4560
[Screen_recording_20241007_181126.webm](https://github.com/user-attachments/assets/b9aa7e2e-c54d-44e3-b28e-ca77d6ca4af8)

all: only one survey button (fixes #4560)

---

app/build.gradle
app/src/main/res/layout/fragment_my_library.xml
app/src/main/res/layout/layout_search.xml

resources: smoother search (fixes #4536)

---

app/build.gradle
app/src/main/res/layout/fragment_my_course.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml

courses: smoother title (fixes #4542)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite

all: smoother notification current count (fixes #4572)

---

app/build.gradle
app/src/main/res/layout/fragment_my_library.xml

resources: smoother title (fixes #4565)

---

app/build.gradle
app/src/main/res/layout/fragment_team.xml
app/src/main/res/layout/item_team_list.xml

teams: smoother list (fixes #4577)

---

app/build.gradle
app/src/main/res/layout/fragment_my_course.xml

courses: smoother mycourses title (fixes 4567)

---

app/build.gradle
app/src/main/res/layout/fragment_library_detail.xml

resources: smoother detail (fixes #4580)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/MyActivityFragment.kt

dashboard: smoother myactivity (fixes #4569)

---

app/build.gradle
app/src/main/res/layout/fragment_feedback.xml

all: smoother feedback dark mode (fixes #4599)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

dashboard: smoother profile translation (fixes #4586)

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/AndroidManifest.xml.lite
app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt

fixes #4589
`how to test`
check if you are able to download files

sync: smoother download (fixes #4589)

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/AndroidManifest.xml.lite
app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt

all: smoother download service (fixes #4612)

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/AndroidManifest.xml.lite

all: smoother media selection (fixes #4614)

---

app/build.gradle
app/src/main/res/layout/fragment_member_detail.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

dashboard: smoother profile translation (fixes #4601)

---

app/build.gradle
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

Fixes: #4593 
Remove `user_name` string related build warnings.

actions: less build warnings is more (fixes #4593)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt

all: smoother notifications (fixes #4623)

---

app/build.gradle
app/src/main/res/layout/activity_login.xml

- fixes #4571 
- added constraintVerticalBias

login: smoother learner list (fixes #4571)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.kt

all: smoother feedback translation (fixes #4587)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/AdapterResource.kt
app/src/main/res/layout/row_library.xml

- fixes #4526 
- removed redundant icons
- less icons is better

resources: smoother mylibrary icons (fixes #4526)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt

all: smoother logout (fixes #4636)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite

all: smoother sidebar (fixes #4596)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmCourseActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt

courses: smoother activity background thread (fixes #4640) 

---

app/build.gradle
app/src/main/res/layout/activity_feedback_detail.xml

all: smoother feedback detail (fixes #4629)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt

- Using predefined theme with button colors to make dialogs consistent across app.

courses: smoother download dialog (fixes #4600)

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/AndroidManifest.xml.lite

fixes #4649
```
to test 
1. create, download and view different types of resources
```

all: smoother manifest permissions (fixes #4649)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/viewer/CSVViewerActivity.kt

resources: smoother csv dark mode (fixes #4652)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt
app/src/main/java/org/ole/planet/myplanet/utilities/DownloadUtils.kt
app/src/main/res/layout/fragment_services.xml

community: smoother services images (fixes #4654)

---

app/build.gradle
app/src/main/res/layout/activity_csvviewer.xml

resources: smoother csv dark mode (fixes #4656)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt

##Description
- fixes #4602 
- Added a companion object for Course Fragment
- Creates a new Course Fragment object for myCourses when clicked on joinCourse in OurCourses
- Guest mode changes are also applicable on this dialog
- Try joining multiple courses
[Navigation to myCourses.webm](https://github.com/user-attachments/assets/57a51d5f-65de-4708-8da6-36fd30bcda43)

courses: smoother mycourses joining (fixes #4602)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

Fixes: #4630 
`Note: changes will be reflected after merging` -  https://github.com/open-learning-exchange/myplanet/pull/4628

all: smoother feedback messages (fixes #4630)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt

Fixes: #4651 
https://github.com/user-attachments/assets/3c088636-4757-4e20-a7a4-8636a0b20408

resources: smoother upload (fixes #4651)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

- fixes #4661 
- change dependency pr: #4660

courses: smoother mycourses joining translations (fixes #4661)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt

- fixes #4632
- added dialog dismiss logic which was missing
[Fixes library download issue.webm](https://github.com/user-attachments/assets/fab89ea3-5423-4d15-8e0a-b9849413c833)

resources: smoother download (fixes #4632)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt

courses: smoother steps (fixes #4605)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt
app/src/main/res/layout/activity_add_resource.xml

- fixes #4674 
- navigate to library detail on addition of a resource.
[Working add resource navigation.webm](https://github.com/user-attachments/assets/7d0ea9dc-8313-4d9f-915b-2a4312683ec4)

resources: smoother post creation (fixes #4674)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt

courses: smoother cancel joining (fixes #4678)

---

app/build.gradle
app/src/main/res/values/strings.xml

- fixes #4683 
- Removed redundant char

resources: smoother details

---

app/build.gradle
app/src/main/res/layout/dialog_server_url_.xml

login: smoother settings dark mode (fixes #4694)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/java/org/ole/planet/myplanet/utilities/SharedPrefManager.kt

fixes #4696
[sync.webm](https://github.com/user-attachments/assets/822d5477-4b33-4d36-b7ec-e3111015c85a)

login: smoother manual sync settings (fixes #4696)

---

app/build.gradle
app/src/main/res/layout-large-land/activity_login.xml
app/src/main/res/layout-night/activity_login.xml
app/src/main/res/layout-normal-land/activity_login.xml
app/src/main/res/layout-xlarge-land/activity_login.xml
app/src/main/res/layout/activity_login.xml

- fixes #4689
- added elevation and stroke color

login: smoother language button (fixes #4689)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt

resources: smoother record audio translation (fixes #4691)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

- fixes #4699 
- removed an empty item from level array 
- added adapter to handle the spinner in fragment

dashboard: smoother profile edit dark mode (fixes #4699)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt

- fixes #4692 
- added language context manager

resources: smoother add translations (fixes #4692)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite

all: smoother main menu (fixes #4664)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
app/src/main/res/layout/fragment_team.xml

teams: smoother list (fixes #4714)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CourseStepFragment.kt
app/src/main/java/org/ole/planet/myplanet/utilities/Markdown.kt
app/src/main/res/layout/dialog_zoomable_image.xml

fixes #4713
https://github.com/user-attachments/assets/2211c5bd-576e-4218-b760-9065c6cd0236

courses: smoother markdown pictures (fixes #4713)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt

- fixes #4698
This check gets default parentCode and planetCode for the guests to view the voices.
- From login (prev user guest)
- Guest Login community

community: smoother voices visibility (fixes #4698)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt

courses: smoother mycourses list (fixes #4741)

---

app/build.gradle
app/src/main/res/layout/row_course.xml

courses: smoother details title (fixes #4740)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt

resources: smoother downloads (fixes #4747)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt

fixes #4739
[Screen_recording_20241105_170058.webm](https://github.com/user-attachments/assets/c4a2dc5d-c758-45d3-a2ca-f2329f757de6)

courses: smoother labeling (fixes #4739)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt

fixes #4750
[Uploading news zoom.webm…]()

voices: smoother zooming images (fixes #4750)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt

- fixes #4711 
-  userId was null

surveys: smoother list (fixes #4711)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

fixes #4759
test with the sync in the login if progressDialog is shown

sync: smoother progress (fixes #4759)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt

surveys: smoother list date (fixes #4712)

---

app/build.gradle
app/src/main/res/drawable/baseline_storage_24.xml

login: smoother icon dark mode (fixes #4737)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt

teams: smoother leaving (fixes #4764)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt
app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt.lite
app/src/main/java/org/ole/planet/myplanet/service/StayOnlineWorker.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/AboutFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DisclaimerFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/helpwanted/HelpWantedFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/onBoarding/OnBoardingAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

all: less is more (fixes #4766)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt

login: smoother errors dark mode (fixes #4324)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt

fixes #4738
to test clear app data do a fresh sync after login go straight to community to see if it crashes when opened

sync: smoother downloads (fixes #4738)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

sync: smoother workload (fixes #4779)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt

- fixes #4756 
- fixed the stepCounter
[Uploading fixed steps.webm…]()

courses: smoother steps counting (fixes #4756)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt

- fixes #4785
- creating new list to avoid concurrent modification exception.
- To test sync and check logs.

sync: smoother concurrent access (fixes #4785)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

- fixes #4800
- Added checks and toast
[removed all users.webm](https://github.com/user-attachments/assets/32538108-157e-446e-b10a-1832e558f20e)

teams: smoother members remove (fixes #4800)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt

- fixes #4802 
[cannot remove leader.webm](https://github.com/user-attachments/assets/3ad5128c-f295-41b4-b420-add20e49683b)

teams: smoother members removal (fixes #4802)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
app/src/main/res/values/strings.xml

teams: smoother last member (fixes #4814)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
app/src/main/res/layout/fragment_team_detail.xml

- fixes #4815
[Join Button.webm](https://github.com/user-attachments/assets/d8139e33-e01b-43ea-984d-2199e855c8d8)

teams: smoother joining (fixes #4815)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt

- fixes #4838
-  This dialog is difficult to recreate.

login: smoother upgrade dark mode (fixes #4838)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt

sync: smoother downloads (fixes #4837)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt

- fixes #4833
https://github.com/user-attachments/assets/cc3683fe-71de-41bf-bf86-7e73542fbb63

surveys: smoother numbers (fixes #4833)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt

- fixes #4844
- Same theme applied all over application

all: smoother dialogs (fixes #4844)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #4851
[Screen_recording_20241210_154620.webm](https://github.com/user-attachments/assets/ff8ae52e-69fe-49e6-a636-0516b42def49)

chat: smoother sharing translations (fixes #4851)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

all: smoother challenge (fixes #4865)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/AdapterResource.kt

- fixes #4860
- listner on description
[clickable library description.webm](https://github.com/user-attachments/assets/6ab21717-e3e7-47b3-9850-cea8b88542b7)

resources: smoother list details (fixes #4860)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite

login: smoother avatar check (fixes #4872)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt

login: smoother earth check (fixes #4875)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt
app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt.lite

login: smoother permissions check (fixes #4873)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite

- fixes #4900 
- added correct type for survey notification
[pending survey notification.webm](https://github.com/user-attachments/assets/fa108341-8579-45cb-9fba-e134d95d2989)

all: smoother pending survey notifications (fixes #4900)

---

app/build.gradle
app/src/main/res/layout/activity_markdown_viewer.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml

all: smoother markdown dark mode (fixes #4903)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt

all: smoother notification navigation (fixes #4883)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
app/src/main/res/layout/alert_input.xml

- fixes #4920
- added view to xml for smoother addons

teams: smoother message dialog (fixes #4920)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

sync: smoother download error handling (fixes #4919)

---

app/build.gradle
app/src/main/res/layout/edit_profile_dialog.xml

dashboard: smoother profile edit (fixes #4939)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt

login: smoother theme dialog (fixes #4946)

---

app/build.gradle
app/src/main/res/layout/fragment_news.xml

- fixes #4933
[voices button.webm](https://github.com/user-attachments/assets/54985c80-7c81-4b34-8e37-cb14df137f99)

teams: smoother voices button (fixes #4933)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite

all: extend december challenge (fixes #4952)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite

fixes #4966 
[Screen_recording_20250108_222813.webm](https://github.com/user-attachments/assets/98df06ae-0201-454e-85e5-d4933e31e83f)

all: smoother navigation icons (fixes #4966)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite

all: smoother navigation community icon (fixes #4968)

---

app/build.gradle
app/src/main/res/layout/fragment_reports.xml

enterprises: smoother reports button (fixes #4972)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt

fixes #4979
only one instance of the dialog is necessary
https://github.com/user-attachments/assets/e69bff71-3652-4662-91d2-16288bc793bd

resources: smoother dialog (fixes #4979)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

fixes #4977
mini sync for login data so even if user fails to sync the login activity will be synced to db

sync: smoother login data upload (fixes #4977)

---

app/build.gradle
app/src/main/res/layout/fragment_course_detail.xml
app/src/main/res/values/styles.xml

courses: smoother resources button (fixes #4971)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt

resources: smoother downloads (fixes #5012)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmCourseActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt

courses: smoother joining (fixes #5013)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt

courses: smoother filter dark mode (fixes #5041)

---

app/build.gradle
app/src/main/res/layout/fragment_my_submission.xml

courses: smoother submissions headings (fixes #5033)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt

sync: smoother myhealth dialog dark mode (fixes #5048)

---

app/build.gradle
app/src/main/res/layout/alert_create_team.xml

teams: smoother create dialog (fixes #5063)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt

mylife: smoother myhealth background sync (fixes #5065)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt

fixes #5046 
This pull should fix all the broken navigation links in dashboard
https://github.com/user-attachments/assets/b03c9361-e453-482a-97c5-cc2eab301f87

all: smoother navigation links (fixes #5046)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
app/src/main/res/layout/fragment_my_library.xml

resources: smoother tag text (fixes #5055)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt

fixes #5073 
[Screen_recording_20250120_215603.webm](https://github.com/user-attachments/assets/b57aaf8d-a7c9-414e-978f-99c55f299703)

teams: smoother search (fixes #5073)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/ExpandableListAdapter.kt
app/src/main/res/layout/chat_share_dialog.xml

chat: smoother sharing dark mode (fixes #5078)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref.xml

settings: less is more (fixes #5092)

---

app/build.gradle
app/src/main/res/values/styles.xml

mylife: smoother myhealth records (fixes #5111)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/java/org/ole/planet/myplanet/utilities/ServerUrlMapper.kt

sync: smoother planet uriur (fixes #5093)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt

courses: smoother exams submissions (fixes #5104)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml
gradle.properties

remove palmbay from the configuration dialog. Palmbay is the last one and it is gone.

sync: less config is more (fixes #5085)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt

courses: smoother joining (fixes #5109)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/callback/OnHomeItemClickListener.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite

fixes #5070 
https://github.com/user-attachments/assets/3de0998a-d046-411f-b3f6-37ef7582b6fe

all: smoother navigation highlight (fixes #5070)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt

sync: smoother not found dark mode (fixes #5100)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite

- fixes #5122
[topBar visibility.webm](https://github.com/user-attachments/assets/84bd7ac3-e7fe-425d-9a5b-715bff33a3e7)

all: smoother navigation hide (fixes #5122)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt

fixes #5106
https://github.com/user-attachments/assets/022f8736-3bc4-4160-a590-fd7743980b30

dashboard: smoother profile info (fixes #5106)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt

dashboard: smoother survey reminder guest (fixes #5133)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt

sync: smoother check server dark mode (fixes #5131)

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/AndroidManifest.xml.lite

login: smoother registration (fixes #5144)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt

- fixes #5121 
- local chip variable wrt news
[working chips.webm](https://github.com/user-attachments/assets/b19ac28d-2a2d-4930-8ecb-a20c86e2e7e9)

teams: smoother voices tags (fixes #5121)

---

app/build.gradle
app/src/main/res/layout-large-land/activity_login.xml
app/src/main/res/layout-night/activity_login.xml
app/src/main/res/layout-normal-land/activity_login.xml
app/src/main/res/layout-xlarge-land/activity_login.xml
app/src/main/res/layout/activity_login.xml

login: smoother input (fixes #5155)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

fixes #5182 
[Screen_recording_20250131_140938.webm](https://github.com/user-attachments/assets/fcf82fc5-d1ba-4a8d-8228-a1a57ea51d3e)

sync: smoother server selection (fixes #5182)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt

fixes #5118 
https://github.com/user-attachments/assets/0709fbc3-7d82-4d79-86b6-a75ae17f068e

mylife: smoother references dictionary (fixes #5118)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt

fixes #5168 
https://github.com/user-attachments/assets/046a1f4d-117b-4440-ad61-de227087227e

teams: smoother voices toast message (fixes #5168)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt

resources: smoother search (fixes #5164)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
app/src/main/java/org/ole/planet/myplanet/utilities/ServerUrlMapper.kt

resources: smoother downloads post check (fixes #5189)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/community/AdapterLeader.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt

community: smoother leaders profile (fixes #5117)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt

login: smoother register dark mode (fixes #5185)

---

app/build.gradle
app/src/main/res/values-es/strings.xml

login: smoother translations (fixes #5193)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt

courses: smoother mycourses navigation highlight (fixes #5031)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt

resources: smoother creation meta info (fixes #5170)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.kt
app/src/main/res/layout/row_joined_user.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

teams: smoother members detail (fixes #5154)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterHealthExamination.kt
app/src/main/res/layout/alert_examination.xml

mylife: smoother myhealth examination dark mode (fixes #5051)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
app/src/main/res/values-night/styles.xml
app/src/main/res/values/styles.xml

teams: smoother voices comment dialog (fixes #5173)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt

sync: smoother submissions (fixes #5210)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #5212 
https://github.com/user-attachments/assets/374a2f48-d924-4954-b17d-b02944e9ba22

mylife: smoother myhealth record edit (fixes #5212)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
app/src/main/java/org/ole/planet/myplanet/ui/chat/AiProviderModel.kt
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
app/src/main/res/layout/fragment_chat_detail.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

chat: smoother providers dynamically (fixes #5191)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt

teams: smoother surveys list (fixes #5218)

---

app/build.gradle
app/src/main/res/layout/card_profile_bell.xml

- fixes #5219
-  Added horizontal scroll view
[scrollable stars.webm](https://github.com/user-attachments/assets/1f747d55-e527-4afa-8d57-54a9ab164d3d)

dashboard: smoother badges (fixes #5219)

---

app/build.gradle
app/src/main/res/layout/activity_become_member.xml

login: smoother register dark mode (fixes #5198)

---

app/build.gradle
app/src/main/res/layout/dialog_server_url_.xml

fixes #5216 
https://github.com/user-attachments/assets/e19801fe-11b4-405d-a0c9-7a8cc0f38cd4

login: smoother settings pin (fixes #5216)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt

fixes #5244
Ensure transactions are properly closed and optimize database access in getLastVisit()

login: smoother profile visits (fixes #5244)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt

fixes #5246
Use background threads for transactions

courses: smoother joining and leaving (fixes #5246)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt

- fixes #5223
[level selection working.webm](https://github.com/user-attachments/assets/ec493f11-e207-4026-a85f-700dacad5022)

dashboard: smoother profile levels (fixes #5223)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

resources: smoother mylibrary language (fixes #5250)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/res/layout/dialog_server_url_.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

sync: smoother config fast beta (fixes #5234)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt

fixes #5174 
https://github.com/user-attachments/assets/f561a565-729c-429a-9d50-834018aad0db

resourses: smoother mylibrary adding dialog (fixes #5174)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
app/src/main/res/layout/fragment_survey.xml

fixes #5217 
https://github.com/user-attachments/assets/a475ce8a-7409-438a-b0d0-019ddfba9186

teams: smoother survey search (fixes #5217)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt

fixes #5258 
https://github.com/user-attachments/assets/e70c890d-de00-4861-b0cd-c170dd561043

chat: smoother search (fixes #5258)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/ExpandableListAdapter.kt
app/src/main/res/layout/chat_share_dialog.xml
app/src/main/res/layout/expandable_list_group.xml

chat: smoother share dark mode (fixes #5248)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt

fixes #5172 
https://github.com/user-attachments/assets/4d59c3c0-5d2d-48ae-a979-143b7fc5e72a

courses: smoother mycourses dialog (fixes #5172)

---

app/build.gradle
app/src/main/res/layout/row_my_progress_grid.xml

courses: smoother mycourses progress dark mode (fixes #5285)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt

mylife: smoother achievements resources dark mode (fixes #5279)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt

dashboard: smoother checks (fixes #5253)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/TakeCourseFragment.kt

courses: smoother joining (fixes #5269)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

- fixes #5275
[welcome back luffy.webm](https://github.com/user-attachments/assets/fd4bbf79-279c-4188-bf1f-b8519c55f939)

login: smoother welcome message (fixes #5275)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #5288
https://github.com/user-attachments/assets/5a8b1424-762c-4d2c-a513-a9b4505ed900

dashboard: smoother profile image options (fixes #5288)

---

app/build.gradle
app/src/main/res/layout/activity_add_examination.xml

mylife: smoother myhealth recording (fixes #5262)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt
app/src/main/res/layout/fragment_edit_achievement.xml

fixes #5267 
https://github.com/user-attachments/assets/abc0bb12-6730-44d4-9ad5-a38245f86d01

mylife: smoother myachievements title edit (fixes #5267)

---

app/build.gradle
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

mylife: smoother myachievements button translations (fixes #5266)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

resources: smoother mylibrary experience (fixes #5208)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

`san pablo sync time reduced by 5 minutes`
`planet learning sync time reduced by 3.9 minutes`

sync: smoother parallelization with coroutines (fixes #5313)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt

fixes #5276 
https://github.com/user-attachments/assets/42f083c5-cd09-4297-910c-355fb15d42d6

courses: smoother archive button (fixes #5276)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
app/src/main/res/layout/activity_add_examination.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #5264 
https://github.com/user-attachments/assets/d1eeac0a-54f4-4712-bef2-7866c5b71bcd

mylife: smoother myhealth examination input validation (fixes #5264)

---

app/build.gradle
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

all: smoother mypersonal toast notification (fixes #5270)

---

app/build.gradle
app/src/main/res/layout/dialog_server_url_.xml

login: smoother settings dialog (fixes #5311)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

login: smoother sync foreground stop (fixes #5328)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt

fixes #5315 
https://github.com/user-attachments/assets/75e43388-41a5-473c-a645-4e1e5bb77d81

resources: smoother navigation (fixes #5315)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

teams: smoother survey translations (fixes #5321)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListFragment.kt

chat: smoother history (fixes #5363)

---

app/build.gradle
app/src/main/res/layout/fragment_my_course.xml

- fixes #5386
[non resizing buttons.webm](https://github.com/user-attachments/assets/682249a5-9a71-43b5-bd85-c24d4d2ff8e6)

courses: smoother navigation buttons (fixes #5386)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt

fixes #5395 
to test:
- go to setting (the one before log in)
- manul
- sync

login: smoother settings error dialog (fixes #5395)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.kt
app/src/main/res/layout/row_member_request.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #5381
for a member who has requested to join a team they won't be able see the accept and request buttons like on planet

teams: smoother joining security (fixes #5381)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
app/src/main/res/layout/fragment_user_information.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

teams: smoother survey closing dialog (fixes #5401)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
app/src/main/res/layout/fragment_user_information.xml

teams: smoother surveys submission dark mode (fixes #5359)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt
app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt.lite

- fixes #5405
- On login if you deny access permissions, permissions denied toast wont be shown
- On courses -> no resources to download toast wont be shown
[no toast.webm](https://github.com/user-attachments/assets/ab3b90db-8af2-4183-9c37-8b67187068a4)

login: less toasts is more (fixes #5405)

---

app/build.gradle
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values/strings.xml

all: smoother settings texts (fixes #5368)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt

fixes #5404 
https://github.com/user-attachments/assets/f28947a6-bbe9-4529-9c6c-2dcf415d5bab

teams: smoother navigation details (fixes #5404)

---

app/build.gradle
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-so/strings.xml

all: smoother translations (fixes #5416)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt

 sync: smoother dialog (fixes #5418)

---

app/build.gradle
app/src/main/res/values/strings.xml

all: smoother feedback buttons (fixes #5413)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
app/src/main/res/xml/pref.xml

fixes #5425
[Screen_recording_20250306_173244.webm](https://github.com/user-attachments/assets/b4dea3d7-a836-499c-af78-339eaea9a510)

all: smoother settings beta sync (fixes #5425)

---

app/build.gradle
app/src/main/res/values/styles.xml

teams: smoother surveys filter dark mode (fixes #5451)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt

teams: smoother surveys list (fixes #5428)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt

resources: smoother bulk download (fixes #5454)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt

fixes #5393 
https://github.com/user-attachments/assets/6778fe65-0bab-4b05-a1f1-89460864557f

chat: smoother typing animation (fixes #5393)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.kt
app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
app/src/main/res/layout/row_survey.xml

teams: smoother surveys description (fixes #5461)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

login: smoother welcome toast (fixes #5430)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
app/src/main/res/layout/my_library_alertdialog.xml

resources: smoother download dialog (fixes #5465)

---

app/build.gradle
app/src/main/res/layout/fragment_disclaimer.xml

all: smoother disclaimer email (fixes #5480)

---

app/build.gradle
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

teams: smoother survey date filter (fixes #5491)

---

app/build.gradle
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

dashboard: smoother mysurveys translation (fixes #5372)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

- fixes #5332
[clear data issue fixed.webm](https://github.com/user-attachments/assets/9aa58c09-adde-4915-a4a0-4bd84e57376c)

sync: smoother dialog (fixes #5332)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt

courses: smoother leaving (fixes #5501)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt

teams: smoother survey recording (fixes #5474)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt

sync: smoother logs anr (fixes #5510)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt

fixes #5477 
https://github.com/user-attachments/assets/4a7808d7-a3c6-4a47-81fe-2068915d265e

teams: smoother survey search (fixes #5477)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt

teams: smoother task creation (fixes #5520)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt

sync:  smoother serialization (fixes #5544)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite

fixes #5542
to test after login check if notifications were created and if app crashes
5

all: smoother notifications (fixes #5542)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

login: smoother register (fixes #5532)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt

teams: smoother voices titles (fixes #5524)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
app/src/main/res/layout/row_news.xml

teams: smoother voices editing (fixes #5471)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt

fixes #5547 
https://github.com/user-attachments/assets/ad3b894b-572d-4242-afbb-8a86d64c4e0a

teams: smoother calendar (fixes #5547)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt

mylife: smoother mysurveys (fixes #5552)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite

all: smoother base container (fixes #5550)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt

all: smoother models (fixes #5558)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/community/HomeCommunityDialogFragment.kt

login: smoother public info (fixes #5576)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt
app/src/main/java/org/ole/planet/myplanet/utilities/LocaleHelper.kt
app/src/main/java/org/ole/planet/myplanet/utilities/Markdown.kt
app/src/main/java/org/ole/planet/myplanet/utilities/NetworkUtils.kt
app/src/main/java/org/ole/planet/myplanet/utilities/ServerUrlMapper.kt
app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt

fixes #5563 
There is one left in utilities.kt but the quick fix doesn't work.

all: smoother utilities (fixes #5563)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

fixes #5584
[Screen_recording_20250328_165716.webm](https://github.com/user-attachments/assets/1e00fd9c-76f1-4bf7-8730-ccf1d1bb3f2a)

sync: smoother dialog dismiss (fixes #5584)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmMeetup.kt
app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt
app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #5567 
https://github.com/user-attachments/assets/24ddd84a-ea90-46e0-9bc1-04ce15a65975

teams: smoother calendar events (fixes #5567)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatHistoryListAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterHealthExamination.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFilterFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/viewer/WebViewActivity.kt

fixes #5562 
There were two places that had a little problem but it solved.
From UserProfileFragment line 86. I changed String.toUri then did the safe (?.), the first one work fine.
The second one  from ChatDetailFragment line 364, I changed String.toUri then did the safe (?.), it caused an error on line 366 and failed to run the application so I changed it back to the previous version. 
Are these two okay?

all: smoother ui urls (fixes #5562)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt

sync: smoother foreground toast (fixes #5529)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #5579 
- Move Enterprises to under Teams
- Change Team to Teams

all: smoother navigation (fixes #5579)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt

dashboard: smoother profile form (fixes #5581)

---

app/build.gradle
app/src/main/res/layout/edit_profile_dialog.xml

dashboard: smoother profile buttons (fixes #5595)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt

mylife: smoother myhealth records (fixes #5590)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmAchievement.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmCertification.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmChatHistory.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmCourseProgress.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmExamQuestion.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmFeedback.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmMeetup.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealthPojo.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmOfflineActivity.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmRating.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmTag.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmTeamTask.kt
app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.kt
app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt

fixes #5598
solved 8 of the errors showing up one still remaining (WIP), Survey questions also synced  so learner is able to take part in survey

sync: smoother realm transactions (fixes #5598)

---

app/build.gradle
app/src/main/res/layout/fragment_news.xml

teams: smoother voices creation (fixes #5608)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt

fixes #5613 
https://github.com/user-attachments/assets/1183b247-2428-401e-a276-59c77043e226

teams: smoother list buttons (fixes #5613)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/JoinedMemberFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.kt

fixes #5626 
https://github.com/user-attachments/assets/051c1bc6-a7f5-406a-b97b-a4b5a710db98

teams: smoother members list (fixes #5626)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt

fixes #5619 
https://github.com/user-attachments/assets/cc070e83-ac57-47f6-8af9-cb1e5c334ec0

login: smoother community calendar (fixes #5619)

---

app/build.gradle
app/src/main/res/layout/add_meetup.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

teams: smoother calendar recurring frequency (fixes #5630)

---

app/build.gradle
app/src/main/res/layout/fragment_achievement.xml
app/src/main/res/layout/row_achievement.xml
app/src/main/res/layout/row_other_info.xml

mylife: smoother myachievements view (fixes #5600)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityPagerAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/enterprises/TeamCalendarFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
app/src/main/res/layout/fragment_enterprise_calendar.xml

teams: smoother calendar (fixes #5566)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt

fixes #5634
[Screen_recording_20250407_195041.webm](https://github.com/user-attachments/assets/a71e804b-843b-4634-ab68-17df7c2c9105)

sync: smoother configuration (fixes #5634)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
app/src/main/res/layout/fragment_vital_sign.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #5645 
when no records available

mylife: smoother myhealth records sparse (fixes #5645)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt

fixes #5622 
https://github.com/user-attachments/assets/145957ad-432f-4d26-84b2-70c2cecac465

teams: smoother finances records dates (fixes #5622)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt

login: smoother team handling (fixes #5663)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt
app/src/main/res/layout/fragment_plan.xml

teams: smoother plan edit (fixes #5614)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt

sync: smoother configuration beta enabled (fixes #5660)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt

teams: smoother event details (fixes #5651)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt

mylife: smoother myachievements view (fixes #5618)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt

teams: smoother chat delete dialog dark mode (fixes #5671)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmMeetup.kt
app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/AdapterMeetup.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt
app/src/main/res/layout/add_meetup.xml
app/src/main/res/layout/item_meetup.xml

teams: smoother calendar events creation (fixes #5611)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt

fixes #5624 
https://github.com/user-attachments/assets/0682c9b8-8668-457f-8bc8-07a0fe635796

teams: smoother finances records date order (fixes #5624)

---

app/build.gradle
app/src/main/res/layout/fragment_team_task.xml

fixes #5153 
Button texts change to white when click.

teams: smoother tasks filters light mode (fixes #5153)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
app/src/main/java/org/ole/planet/myplanet/utilities/ServerUrlMapper.kt

fixes #5694
this pr reverts the fast become member changes

login: revert fast register (fixes #5694)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
app/src/main/res/layout/activity_login.xml

login: smoother team list (fixes #5692)

---

app/build.gradle
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

teams: smoother event detail buttons (fixes #5705)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt

chat: smoother realm transaction (fixes #5714)

---

app/build.gradle
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

teams: smoother calendar event creation (fixes #5724)

---

app/build.gradle
app/src/main/res/layout/edit_profile_dialog.xml

dashboard: smoother profile dialog edit (fixes #5680)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt

teams: smoother calendar events creation (fixes #5726)

---

app/build.gradle
app/src/main/res/layout/item_meetup.xml

fixes #5732 
https://github.com/user-attachments/assets/c20095a7-a9dd-487b-bdc9-d74fb1521238

teams: smoother calendar event link (fixes #5732)

---

app/build.gradle
app/src/main/res/layout/fragment_team_detail.xml

login: smoother community (fixes #5734)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite

fixes #5741 
https://github.com/user-attachments/assets/7b30cf98-23b6-44e4-bdb8-3c47067edbc2

all: smoother navigation focus (fixes #5741)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt

fixes #5748 
https://github.com/user-attachments/assets/69944e1b-0231-410d-8111-722154297b4e

teams: smoother calendar event link validation (fixes #5748)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
app/src/main/res/layout/fragment_vital_sign.xml

mylife: smoother myhealth view (fixes #5737)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt
app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt

teams: smoother survey sync (fixes #5773)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt

teams: smoother guest user (fixes #5762)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt

courses: smoother guest mode (fixes #5763)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt

fixes #5683 
https://github.com/user-attachments/assets/e6496401-fb88-40c9-af60-bd131dec6109

teams: smoother calendar date (fixes #5683)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt

login: smoother team selection (fixes #5754)

---

app/build.gradle
app/src/main/res/layout/fragment_my_activity.xml

dashboard: smoother activity chart (fixes #5775)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt

fixes #5374 
https://github.com/user-attachments/assets/4bd30bb4-1aec-4324-9724-182a960fb58d

all: smoother logout (fixes #5374)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #5745
https://github.com/user-attachments/assets/105be7f3-1c4f-4140-9f92-912aec7c4121

resources: smoother camera permissions (fixes #5745)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.kt

mylife: smoother myhealth record birthday (fixes #5759)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt

fixes #5764 
https://github.com/user-attachments/assets/1e8d2437-8d0b-4bec-89a0-88d9162d8b86

teams: smoother calendar event creation (fixes #5764)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt

fixes #5755
[Screen_recording_20250424_150155.webm](https://github.com/user-attachments/assets/c6ad412b-ecee-46aa-87e2-d83ac40b6f7e)

login: smoother configuration server necessary (fixes #5755)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
app/src/main/java/org/ole/planet/myplanet/datamanager/ApiClient.kt
app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/utilities/ServerUrlMapper.kt

fixes #5779
improvements
1. parallel server checks 
2. faster non-responsive server detection

sync: smoother server check (fixes #5779)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt

teams: smoother voices replies (fixes #5790)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt

resources: smoother checks safe state (fixes #5793)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt

community: smoother voices guests replies (fixes #5795)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite

fixes #5806
[Screen_recording_20250502_161253.webm](https://github.com/user-attachments/assets/e2e9a755-2e22-4fba-aa49-7812c8a7db87)

resources: smoother view (fixes #5806)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt
app/src/main/res/layout-w600dp/fragment_team_detail.xml
app/src/main/res/layout/fragment_team_detail.xml

teams: smoother pager (fixes #5707)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt

fixes #5812
to test this adopt a survey then submit a response to the survey and sync to see if both actions are uploaded to planet

teams: smoother survey adoption (fixes #5812)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt

sync: smoother url handling (fixes #5820)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt

teams: smoother voices replies (fixes #5525)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamCalendarFragment.kt

teams: smoother calendar event date selection (fixes #5817)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

sync: smoother default normal (fixes #5846)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt

dashboard: smoother profile image capture (fixes #5797)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt
app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.kt
app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt

fixes #5854
2 min improvement on planet gt when tested on emulator.
sync time before: 10:57
after: 8:59

resources: smoother realm insertion (fixes #5854)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmMyLife.kt
app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.kt

fixes #5865
to test: After sync is complete go to mylife and attempt to drag the items to a different position
https://github.com/user-attachments/assets/86de556c-b7a0-406c-bf9f-a1ebd572dd7d

mylife: smoother position change (fixes #5865)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt

login: smoother dashboard (fixes #5873)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt

fixes #5875
[Screen_recording_20250520_192148.webm](https://github.com/user-attachments/assets/01286990-5132-455b-b98b-8382d8051b0a)

chat: smoother provider changing (fixes #5875)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt

fixes #5473
[Screen_recording_20250521_151221.webm](https://github.com/user-attachments/assets/789f024c-b7ad-4e50-82f3-704643bd01af)

teams: smoother survey submissions (fixes #5473)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
app/src/main/res/layout/row_news.xml

fixes #5472 
this should also close PR #5546

teams: smoother voices chat sharing (fixes #5472)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt

fixes #5518 
https://github.com/user-attachments/assets/e70697b2-953b-47d2-87c1-cf67d0d2e913

teams: smoother voices delete (fixes #5518)

---

app/build.gradle
app/src/main/res/layout/row_news.xml

teams: smoother voices profile image (fixes #5871)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/mymeetup/AdapterMeetup.kt
app/src/main/res/layout/item_meetup.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

teams: smoother calendar event details (fixes #5843)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt

teams: smoother voices profile images (fixes #5872)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt

courses: smoother exams submissions (fixes #5898)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #5844 
[Screen_recording_20250508_184558.webm](https://github.com/user-attachments/assets/8005e780-9abf-4fdb-ab91-a2201c6908bb)

sync: smoother settings server pinning (fixes #5844)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt

https://github.com/user-attachments/assets/56d1f723-59d1-484b-8c2b-06059e26904b

teams: smoother chat share voices (fixes #5886)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt
app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.kt

teams: smoother joining request (fixes #5903)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

login: smoother last sync time (fixes #5908)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt
app/src/main/res/values/strings.xml

resources: smoother back post adding (fixes #5819)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt

fixes #5945 
https://github.com/user-attachments/assets/d343fb38-0f7e-45b5-a022-515393baac11

teams: smoother voices member details (fixes #5945)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite
app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt

fixes #5915
https://github.com/user-attachments/assets/0d2188e9-86bd-42b2-bd5e-597f6c1d52f5

resources: smoother mylibrary (fixes #5915)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MemberDetailFragment.kt

fixes #5914 
https://github.com/user-attachments/assets/74608f6a-02e3-41b7-829c-acab4721a67c

dashboard: smoother myteams list (fixes #5914)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt

fixes #5984 
https://github.com/user-attachments/assets/65e9d786-fd48-4685-9235-1f5680e8346f

login: smoother username entry (fixes #5984)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmExamQuestion.kt
app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt

fixes #6018
[other fix.webm](https://github.com/user-attachments/assets/e0b40aea-cbab-45f8-96e0-876c0ec6674d)

teams: smoother survery choice other input (fixes #6018)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt

fixes #6037 
https://github.com/user-attachments/assets/d878f1e2-c38c-4268-9338-c8c42cb9958f

teams: smoother survey button next (fixes #6037)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt

fixes #6119
To test:
Attempt creating a member on planet uriur. On master, the user is unable to log in after creation. This branch fixes that, allowing successful login immediately after member creation.

login: smoother register server check (fixes #6119)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt

#6111
https://github.com/user-attachments/assets/27c27ff6-175c-45d1-956b-7ad354154527

dashboard: smoother profile editing birthday (fixes #6111) 

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt
app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

Fixes
-  if no language is picked, we show “N/A”
- Some hardcoded strings were replaced with proper string resources so they can be translated later.
- refactored checkNA function aswell
https://github.com/user-attachments/assets/c2d10dd9-6d75-4ef4-a2ae-6a9bd46b45f4

dashboard: smoother profile language (fixes #6122)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPage.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt

Refactor TeamPagerAdapter to use enum for pages and support for dynamic localization
https://github.com/user-attachments/assets/ee39221d-604c-40bc-97c8-8dc87027dc9e

teams: smoother translations (fixes #6123)

---

app/build.gradle
app/src/main/res/layout/fragment_user_information.xml
app/src/main/res/values-es/strings.xml

Fix: changed Linear layout to FlexboxLayout and capitalized text in Spanish

teams: smoother survey canceling (fixes #6125)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt

fixes #6145
To test with
becoming member on planet learning and uriur
Test is ai providers are displayed on planet learning

sync: smoother server check (fixes #6145)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt

login: smoother register autologin (fixes #6151)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/ExamSubmissionUtils.kt

fixes #6067 
I did fix this in #6149  but I think the changes got overridden during the merge.
https://github.com/user-attachments/assets/ed9124a4-042f-467d-bf92-bd78c244c8c3

teams: smoother survey single choice other (fixes #6067)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt
app/src/main/java/org/ole/planet/myplanet/utilities/SyncTimeLogger.kt

fixes #6170
To test 
1. watch out for the error in the logcat as described in issue
2. Check if resources were added to mylibrary

 sync: smoother resource transaction (fixes #6170)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

mylife: smoother myhealth examination canceling (fixes #6114)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
app/src/main/res/layout-w600dp/fragment_team_detail.xml
app/src/main/res/layout/fragment_team_detail.xml

fixes #6175 
should also fix #6155 
https://github.com/user-attachments/assets/25023cef-9dcd-4dae-9ce4-dc6a4db7235d

teams: smoother survey submissions (fixes #6175)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt

dashboard: smoother guest registration (fixes #6171)

---

app/build.gradle
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

courses: smoother voices labels (fixes #6276)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt

fixes #6285 
https://github.com/user-attachments/assets/6eb1dfef-5303-4a67-a794-ca2a03668e7d

chat: smoother auto-scrolling (fixes #6285)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt

fixes #6273 
To test: open survey and check they should be sorted by date(desc) by default.

teams: smoother survey sorting default (fixes #6273)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.kt

all: smoother `timeUtils.kt` date format (fixes #6386)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/utilities/NotificationUtil.kt
app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.kt

all: smoother notifications date parsing (fixes #6385)

---

app/build.gradle
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

fixes #6297
[Screen_recording_20250722_174317.webm](https://github.com/user-attachments/assets/ba93d479-ca8f-4b80-8ea0-9d34d0bf1785)

mylife: smoother myhealth recording (fixes #6297)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.kt

fixes #6350 
https://github.com/user-attachments/assets/1ce20b78-81b9-4b25-81f1-b55edfe75b1c

teams: smoother joining (fixes #6350)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt

dashboard: smoother profile birthday format (fixes #6412)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt

fixes #6479
[Screen_recording_20250725_144251.webm](https://github.com/user-attachments/assets/852c5481-bbd8-41f0-b30c-0c8ef75ba156)

community: smoother services (fixes #6479)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt

fixes #6461
https://github.com/user-attachments/assets/e1d45477-dd7a-4f34-a6da-2a2ba9c94bad

chat: smoother details (fixes #6461)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
app/src/main/res/layout/fragment_news.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

community: smoother voices searching filter (fixes #6553)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt

fixes #6537 
https://github.com/user-attachments/assets/0d3b70fa-2299-4bc8-b28b-cc75453dc9b2

teams: smoother chats (fixes #6537)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.kt

fixes #6518
[Screen_recording_20250731_162353.webm](https://github.com/user-attachments/assets/43ca60fd-91e1-40cd-a33b-04279776a67b)

sync: smoother register and logins (fixes #6518)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

teams: smoother plan changing (fixes #6604)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationsFragment.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

all: smoother notification acknowledgements (fixes #6602)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/AdapterTeamResource.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

teams: smoother resource removals (fixes #6607)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt

resources: smoother views (fixes #6605)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

teams: smoother survey adoptions (fixes #6606)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterReports.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ne/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

teams: smoother reports deletion (fixes #6618)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.kt
app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt

teams: smoother survey sorting (fixes #6658)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

sync: smoother uploading (fixes #6530)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/RealmNewsDiffCallback.kt

teams: smoother voices deletion (fixes #6690)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt

teams: smoother realm transactions (fixes #6795)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt

fixes #6961 
[Screen_recording_20250822_173217.webm](https://github.com/user-attachments/assets/d607e6f8-cc71-4e45-b2ee-7efbaea861b3)

teams: smoother member removing (fixes #6961)

---

app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourcesFilterFragment.kt
app/src/main/res/drawable/down_arrow.xml
app/src/main/res/drawable/outline_close_24.xml
app/src/main/res/drawable/outline_keyboard_arrow_up_24.xml
app/src/main/res/layout/fragment_library_filter.xml

fixes #6528
[Screen_recording_20250829_165133.webm](https://github.com/user-attachments/assets/90754028-8d4e-4817-bffe-7b7993385592)

resources: smoother filter dialog (fixes #6528)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/service/ServerReachabilityWorker.kt

fixes #7257
```
How to test
1. Switch off internet data/wifi
2. Adopt and record a survey
3. Switch internet back on
4. After some second of connection check planet for synced survey
```

sync: smoother survey uploading (fixes #7257)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt

myhealth: smoother examination adding (fixes #7236)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.kt

all: smoother `TimeUtils.kt` (fixes #7235)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt
app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.kt

mylife: smoother myhealth examination creation (fixes #2077)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/CoursesFragment.kt

courses: smoother filters (fixes #7319)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/DatabaseService.kt

sync: smoother resources transaction realm handling (fixes #7353)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt
app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt

sync: smoother uploading (fixes #7155)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt

fixes #7499 
https://github.com/user-attachments/assets/3c1cf55d-185c-49c7-a543-adc15c87a8f3

teams: smoother voices scrolling (fixes #7499)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.kt

fixes #7706
[Screen_recording_20250919_153748.webm](https://github.com/user-attachments/assets/46379c74-57e5-4d0e-a4bd-fa548cf19c37)

teams: smoother voices image uploading (fixes #7706)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt

fixes #7925
[Screen_recording_20250929_165048.webm](https://github.com/user-attachments/assets/74c80bee-7008-4bc1-ab2c-585a26c6dcfc)

teams: smoother survey sorting (fixes #7925)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt

fixes #7995
[Screen_recording_20250929_205055.webm](https://github.com/user-attachments/assets/61d2a6cf-18d4-4f5b-a102-34640fc50045)

teams: smoother task filtering (fixes #7995)

---

app/build.gradle
app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
app/src/main/java/org/ole/planet/myplanet/ui/courses/AdapterCourses.kt

fixes #8048
[Screen_recording_20251001_160104.webm](https://github.com/user-attachments/assets/dfda8f5c-52ea-4bbe-8a0a-28c87fb35471)

courses: smoother collection tag filtering (fixes #8048)
