open-learning-exchange/myplanet

app/src/main/res/layout/fragment_dashboard.xml, build.gradle
All the items on the dashboard (fragment_dashboard.xml) were listed as myLibrary, so changed them to their appropriate string values.
=> Correct names for items on user dashboard (#41)

app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml
* Repositioned the "gear" icon by giving it top and right margins on all login layouts.
* Increased width and height to have less blue padding (on small screens)
* Adjusted layout for wear round
=> adjusted_login_xmls (#42)

app/src/main/java/org/ole/planet/takeout/LoginActivity.java, app/src/main/java/org/ole/planet/takeout/SyncActivity.java, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/dialog_sync_feedback.xml, app/src/main/res/layout/spinner_item.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
* Adjusted TextInputLayout font size
* Adjusted portrait mode layout file (Made it bigger)
Two commits:
1. adjusted TextInputLayout font size (fixes #51)
2. adjusted login activity portrait mode (fixes #51)
=> Login screen adjustments (fixes #51)

.idea/misc.xml, app/src/main/res/layout/activity_login.xml
* Removed the duplicated attribute
=> fixed duplicated attr (fixes #60)

app/src/main/java/org/ole/planet/takeout/LoginActivity.java, app/src/main/res/drawable/ic_sync_black_16dp.xml, app/src/main/res/drawable/ic_sync_black_24dp.xml, app/src/main/res/drawable/ic_sync_black_36dp.xml, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml
* Adjusted width, height, padding and other attributes with(in) layouts that are related to "sync" and "gear" imagebuttons
=> changed sync to image button and made sync and settings buttons bigger (fixes #64)

app/build.gradle, app/src/main/java/org/ole/planet/takeout/Dashboard.java, app/src/main/java/org/ole/planet/takeout/DashboardFragment.java, app/src/main/java/org/ole/planet/takeout/Data/realm_UserModel.java, app/src/main/java/org/ole/planet/takeout/Data/realm_offlineActivities.java, app/src/main/java/org/ole/planet/takeout/LoginActivity.java, app/src/main/java/org/ole/planet/takeout/ProcessUserData.java, app/src/main/java/org/ole/planet/takeout/callback/OnHomeItemClickListener.java, app/src/main/java/org/ole/planet/takeout/datamanager/RealmService.java, app/src/main/java/org/ole/planet/takeout/userprofile/UserProfileDbHandler.java, app/src/main/java/org/ole/planet/takeout/userprofile/UserProfileFragment.java, app/src/main/java/org/ole/planet/takeout/utilities/Utilities.java, app/src/main/res/layout-large-land/fragment_dashboard.xml, app/src/main/res/layout-large/fragment_dashboard.xml, app/src/main/res/layout-normal-land/fragment_dashboard.xml, app/src/main/res/layout-normal/fragment_dashboard.xml, app/src/main/res/layout-small-land/fragment_dashboard.xml, app/src/main/res/layout-small/fragment_dashboard.xml, app/src/main/res/layout-xlarge-land/fragment_dashboard.xml, app/src/main/res/layout/fragment_dashboard.xml, app/src/main/res/layout/fragment_user_profile.xml, app/src/main/res/layout/row_stat.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Remaining : Total number of courses started and Total number of completed courses 
Can be done only after adding courses feature. 
For now :
=> User profile with offline statistics (Fixes #124)

app/src/main/java/org/ole/planet/takeout/DashboardFragment.java
fixes #149 
Please do give any suggestions if you think the size of the fragments is too big or small.
=> adjusting size of library and courses menu items (Issue #149)

app/src/main/java/org/ole/planet/takeout/Dashboard.java
Fixes #141 
Added logout capabilities when clicked from the navigation drawers
=> added logout feature (fixes #141)

.idea/misc.xml, app/src/main/java/org/ole/planet/takeout/AuthSessionUpdater.java, app/src/main/java/org/ole/planet/takeout/DashboardFragment.java, app/src/main/java/org/ole/planet/takeout/DownloadFiles.java, app/src/main/java/org/ole/planet/takeout/OfflineVisits.java
fixes #156 
Made Some adjustments to Dashboard Fragment. Specifically to Auth Session Methods, Download Methods, and Offline Visits Method.
=> Code Climate DashboardFragment Cleanup (Issue #156)

README.md
Includes:
- Basic info
- Setting up the repository in Android Studio
- Current features (needs to be updated continuously as newer features are added with screenshots)
- Tools
- Troubleshooting
=> Adding a README.md for the Takeout project

app/src/main/java/org/ole/planet/takeout/DashboardFragment.java, app/src/main/java/org/ole/planet/takeout/Data/realm_myTeams.java, app/src/main/java/org/ole/planet/takeout/service/SyncManager.java, app/src/main/res/layout-large-land/fragment_dashboard.xml, app/src/main/res/layout-large/fragment_dashboard.xml, app/src/main/res/layout-normal-land/fragment_dashboard.xml, app/src/main/res/layout-normal/fragment_dashboard.xml, app/src/main/res/layout-small-land/fragment_dashboard.xml, app/src/main/res/layout-small/fragment_dashboard.xml, app/src/main/res/layout-xlarge-land/fragment_dashboard.xml, app/src/main/res/layout/fragment_dashboard.xml
=> added my meetups list on dashboard (Fixes #186)

.idea/misc.xml, app/build.gradle, app/src/main/java/org/ole/planet/takeout/LoginActivity.java, app/src/main/java/org/ole/planet/takeout/service/SyncManager.java, app/src/main/java/org/ole/planet/takeout/service/TransactionSyncManager.java, app/src/main/res/values/strings.xml
=> version 1.8

app/src/main/java/org/ole/planet/takeout/Data/realm_myLibrary.java
check if resource has description field exist.. and if not insert N/A
=> check if resource has description field exist

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/AuthSessionUpdater.java, app/src/main/java/org/ole/planet/myplanet/CSVViewerActivity.java, app/src/main/java/org/ole/planet/myplanet/Dashboard.java, app/src/main/java/org/ole/planet/myplanet/DashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/Data/realm_myLibrary.java, app/src/main/java/org/ole/planet/myplanet/ImageViewerActivity.java, app/src/main/java/org/ole/planet/myplanet/MarkdownViewerActivity.java, app/src/main/java/org/ole/planet/myplanet/PDFReaderActivity.java, app/src/main/java/org/ole/planet/myplanet/TextFileViewerActivity.java, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.java, app/src/main/java/org/ole/planet/myplanet/callback/OnHomeItemClickListener.java, app/src/main/java/org/ole/planet/myplanet/library/AdapterLibrary.java, app/src/main/java/org/ole/planet/myplanet/library/LibraryDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.java, app/src/main/res/layout/fragment_library_detail.xml, app/src/main/res/values/strings.xml
=> Library detail and open library from list (Fixes #316)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/Data/realm_UserModel.java, app/src/main/java/org/ole/planet/myplanet/Data/realm_offlineActivities.java, app/src/main/java/org/ole/planet/myplanet/Data/realm_resourceActivities.java, app/src/main/java/org/ole/planet/myplanet/SyncActivity.java, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.java, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/courses/CourseDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/library/LibraryDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/userprofile/UserProfileDbHandler.java, app/src/main/res/values/strings.xml
=> Log user activities and minor fixes (Fixes  #337)

app/src/main/res/layout/fragment_home.xml
Simple position change for myMeetups and myTeams
=> switched positions for myMeetups and myTeams (fixes #357)

app/build.gradle, build.gradle
Updated dependencies on both build.gradle files. It was an error in XML. Potential to cause crashes during runtime
=> Updated support libraries (fixes #366)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/Data/realm_courseProgress.java, app/src/main/java/org/ole/planet/myplanet/Data/realm_submissions.java, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/courses/AdapterCourses.java, app/src/main/java/org/ole/planet/myplanet/courses/MyCourseFragment.java, app/src/main/java/org/ole/planet/myplanet/courses/TakeCourseFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/CustomViewPager.java, app/src/main/res/layout/row_course.xml, app/src/main/res/values/strings.xml
=> Show course progress in list and course view pager swipe turned off (Fixes #370)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/DashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.java, app/src/main/res/drawable/ic_more.xml, app/src/main/res/layout/item_library_home.xml, app/src/main/res/values/strings.xml, build.gradle
=> Open resource on dashboard item clicked and more button to open detail (Fixes #411)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java, app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.java, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java, app/src/main/res/values/strings.xml
Delete old resources from sdcard/ole folder before testing this .
=> Resource not opening issue fixed (Fixes #453)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/courses/CourseDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/courses/CourseStepFragment.java, app/src/main/res/layout/fragment_course_detail.xml, app/src/main/res/layout/fragment_course_step.xml, app/src/main/res/values/strings.xml
=> Markdown view in course and step description (Fixes #469)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java, app/src/main/res/values/strings.xml
=> User image issue fixed (Fixes #467)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/model/RealmApkLog.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.java, app/src/main/res/values/strings.xml
=> Save and upload crash log (Fixes #426)

app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
This will delete all the download resources from ole folder after user reinstall the app.
=> Clear internal storage on first run (Fixes #512)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmRating.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/res/values/strings.xml
Found some bug while uploading rating and fixed them. 
@leomaxi @lmmrssa 
Please comment if you found any issues in rating feature, then we can move rating to production from beta.
=> Rating upload bug fix (Fixes #509)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/BottomNavigationViewHelper.java, app/src/main/res/layout/fragment_my_course.xml, app/src/main/res/layout/fragment_my_library.xml, app/src/main/res/layout/fragment_survey.xml, app/src/main/res/menu/menu_topbar.xml, app/src/main/res/values/strings.xml
We can only add max 5 menu items in BottomNavigationView. 
i haven't added mylibrary and mycourses in topbar menu. Because of this restriction.
=> Added mylibrary and mycourses list (Fixes #525)

app/build.gradle, app/src/main/res/layout/layout_search.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
=> Shifts search icon left (fixes #532)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.java, app/src/main/res/values/strings.xml
=> Sets dashboard counts invisible if empty (fixes #539)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.java, app/src/main/res/drawable/white_line.xml, app/src/main/res/layout/fragment_take_course.xml, app/src/main/res/layout/row_course.xml, app/src/main/res/values-v21/styles.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
=> Course progress bar click and UI change (Fixes #537)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/values/strings.xml
=> Hide feature if user is inactive (Fixes #531)

app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java
=> Adjusts button text according to question number (fixes #553)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/callback/OnLibraryItemSelected.java, app/src/main/java/org/ole/planet/myplanet/callback/TagClickListener.java, app/src/main/java/org/ole/planet/myplanet/model/RealmTag.java, app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java, app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.java, app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.java, app/src/main/java/org/ole/planet/myplanet/ui/library/CollectionsFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/TagExpandableAdapter.java, app/src/main/res/drawable/ic_keyboard_arrow_down_black_24dp.xml, app/src/main/res/drawable/ic_keyboard_arrow_up_black_24dp.xml, app/src/main/res/layout/fragment_collections.xml, app/src/main/res/layout/fragment_my_library.xml, app/src/main/res/layout/layout_search.xml, app/src/main/res/layout/row_adapter_navigation_child.xml, app/src/main/res/layout/row_adapter_navigation_parent.xml, app/src/main/res/values/strings.xml
=> Changed tag cloud to tag list dialog (Fixes #552)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java, app/src/main/res/values/strings.xml
=> App freezes after first sync issue fixed (Fixes #560)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/values/strings.xml
=> Clears backstack on login (fixes #557)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.java, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java, app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.java, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java, app/src/main/res/values/strings.xml
=> Save file in id folder (Fixes #556)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/model/RealmApkLog.java, app/src/main/java/org/ole/planet/myplanet/model/RealmOfflineActivity.java, app/src/main/res/values/strings.xml
=> Added parent and planet code on apk log (Fixes #572)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/WebViewActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_web_view.xml, app/src/main/res/layout/content_web_view.xml, app/src/main/res/values/strings.xml
#235 
Created web view  for become a member .
But planet is redirecting 
[SERVER_URL]/eng/login/newmember
to 
[SERVER_URL]/eng/login/
=> Web view for become a member (Fixes #235)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/res/values/strings.xml
=> Change remove selected to archive course (Fixes #575)

app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.java, app/src/main/res/layout/fragment_my_course.xml, app/src/main/res/values/strings.xml
=> Change remove opt out to Delete my course (Fixes #577)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.java, app/src/main/res/layout/fragment_take_course.xml, app/src/main/res/values/strings.xml
=> Change buttons (Fixes #578)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/library/CollectionsFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/TagExpandableAdapter.java, app/src/main/res/values/strings.xml
=> Collection selected checkbox auto clear issue (Fixes #591)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/values/strings.xml
=> show message if there is no courses and resources (Fixes #586)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/survey/SendSurveyFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/CheckboxListView.java, app/src/main/res/layout/fragment_send_survey.xml, app/src/main/res/layout/my_library_alertdialog.xml, app/src/main/res/values/strings.xml
=> remove click event message (Fixes #587)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/values/strings.xml
=> Upload shelf :  sync from inside (Fixes #585)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.java, app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.java, app/src/main/res/values/strings.xml
=> mycourse mylibrary filter issue (Fixes #581)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.java, app/src/main/res/values/strings.xml
=> Displays full name under profile image (fixes #468)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/Constants.java, app/src/main/res/values/strings.xml
=> Achievement to beta 

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.java, app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/res/values/strings.xml
=> Don't show shelf items in our library and course list (Fixes #582)

app/build.gradle, app/src/main/res/layout/row_course.xml, app/src/main/res/layout/row_library.xml, app/src/main/res/values/strings.xml
=> checkbox selection issue fixed (Fixes #609)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmAchievement.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/res/values/strings.xml
=> Fixed achievement upload issue (Fixes #618)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.java, app/src/main/res/layout/row_library.xml, app/src/main/res/values/strings.xml
=> Show status image on resource list (Fixes #627) 

app/build.gradle, app/src/main/res/layout/my_library_alertdialog.xml, app/src/main/res/values/strings.xml
=> Resource dialog last item ui issue fixed (Fixes #619)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmAchievement.java, app/src/main/res/values/strings.xml
=> Fixed achievement sync issue (Fixes #626)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.java, app/src/main/res/values/strings.xml
=> Birth Date picker disable upcoming dates   (Fixes #640)

app/build.gradle, app/src/main/res/layout/edit_attachement.xml, app/src/main/res/values/strings.xml
=> Achievement : resources ui issue fixed (Fixes #633)

app/build.gradle, app/src/main/res/layout/fragment_edit_achievement.xml, app/src/main/res/values/strings.xml
=> Make user info read only in edit achievement (Fixes #642)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/utilities/Constants.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/pref.xml
=> Beta function switches

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.java, app/src/main/res/layout/card_profile_bell.xml, app/src/main/res/layout/fragment_home_bell.xml, app/src/main/res/values/dimens.xml, app/src/main/res/xml/pref.xml
`Trying to have a different theme that has user details on top.. Like old BeLL apps`
=> Dashboard UX theme switch ( Fixes #653 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/submission/AdapterMySubmission.java, app/src/main/java/org/ole/planet/myplanet/ui/submission/MySubmissionFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.java, app/src/main/res/layout/fragment_my_submission.xml, app/src/main/res/layout/row_mysurvey.xml, app/src/main/res/values/strings.xml
=> Pending survey (Fixes #656)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.java, app/src/main/res/layout/alert_reference.xml, app/src/main/res/values/strings.xml
=> Donot close reeference dialog if form is invalid (Fixes #661)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmExamQuestion.java, app/src/main/res/values/strings.xml
=> Exam question title fix (Fixes #657)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.java, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.java, app/src/main/res/values/strings.xml
=> Download resource from attachments (Fixes #659)

app/build.gradle, app/src/main/res/layout/activity_csvviewer.xml, app/src/main/res/layout/activity_exo_player_video.xml, app/src/main/res/layout/activity_image_viewer.xml, app/src/main/res/layout/activity_markdown_viewer.xml, app/src/main/res/layout/activity_pdfreader.xml, app/src/main/res/layout/activity_textfile_viewer.xml, app/src/main/res/values/strings.xml
=> content overlapping in resource viewer (Fixes #658)

app/build.gradle, app/release/output.json, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java, app/src/main/java/org/ole/planet/myplanet/model/MyPlanet.java, app/src/main/java/org/ole/planet/myplanet/service/GPSService.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/values/strings.xml
=> Upload GPS to my planet activities (Fixes #684)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/Constants.java, app/src/main/res/values/strings.xml
=> Keep session alive and double press to go back (Fixes #678)

.travis.yml, app/build.gradle, app/src/main/res/values/strings.xml
=> Generate sha256 (Fixes #686)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/layout/app_bar_bell.xml, app/src/main/res/layout/card_profile_bell.xml, app/src/main/res/layout/custom_tab.xml, app/src/main/res/layout/fragment_home_bell.xml, app/src/main/res/layout/home_card_library.xml, app/src/main/res/layout/home_card_meetups.xml, app/src/main/res/layout/home_card_mylife.xml, app/src/main/res/layout/item_library_home.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
@leomaxi  please provide icons
=> Bell theme update

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java, app/src/main/java/org/ole/planet/myplanet/model/MyPlanet.java, app/src/main/java/org/ole/planet/myplanet/service/AutoSyncService.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.java, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java, app/src/main/res/values/strings.xml
=> Download apk using local url (Fixes #728)

app/build.gradle, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/strings.xml
=> Hide keyboard on startup (Fixes #732)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java, app/src/main/res/values/strings.xml
=> Clean data based on min version (Fixes #735 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/service/AutoSyncService.java, app/src/main/res/layout/fragment_course_detail.xml, app/src/main/res/values/strings.xml
=> Autosync upload (Fixes #740)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/ui/library/CollectionsFragment.java, app/src/main/res/layout/fragment_my_library.xml, app/src/main/res/values/strings.xml
=> Collection filter maintain last checked status (Fixes #751)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/fragment_course_detail.xml, app/src/main/res/values/strings.xml
=> LoginActivity : crash fix on logout and invalid credential (Fixes #743 and #742)

app/build.gradle, app/src/main/res/layout/app_bar_bell.xml, app/src/main/res/values/strings.xml
=> Bell app theme : changed setting icon size (Fixes #747)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.java, app/src/main/res/layout/activity_pdfreader.xml, app/src/main/res/values/strings.xml
=> Pdf not loading issue (Fixes #749)

app/build.gradle, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml
=> language selection :  remove empty list item (Fixes #760)

app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml
=> sync now issue fixed (Fixes #762)

app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml, scripts/tag.sh
=> move version to different xml file (Fixes #770)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/values/versions.xml
=> Clear filter/tags on click clear button (Fixes #768)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/values/versions.xml
=> search modification (Fixes #765)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/values/versions.xml
=> Rating bar click issue fixed (Fixes #766)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.java, app/src/main/res/layout/home_card_mylife.xml, app/src/main/res/values/versions.xml
=> Open achievement from bell theme (Fixes #763)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmResourceActivity.java, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.java, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.java, app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/alert_guest_login.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/versions.xml
=> Added guest mode (Fixes #777)

app/build.gradle, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/values/versions.xml
=> Password field hint fixed (Fixes #785)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/values/versions.xml
=> Guest mode offline visit bug (Fixes #786 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.java, app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.java, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.java, app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java, app/src/main/res/layout/content_teams_detail.xml, app/src/main/res/values/versions.xml
=> My teams : show courses and joined members (Fixes #788)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/Constants.java, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/versions.xml
=> Select language from login activity(Fixes #794)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/versions.xml
=> Overlap icon issue in RTL fix (Fixes #801) (#798)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java, app/src/main/res/layout/content_team_detail_tab.xml, app/src/main/res/layout/fragment_my_teams_detail.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Team detail ui update (Fixes #799 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.java, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java, app/src/main/res/values/versions.xml
=> User-dob-formatted (connects #804)

app/build.gradle, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/versions.xml
=> Language color highlighted (connects #800)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/values/versions.xml
=> Bell home tab clickable from other pages (Fixes #783)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.java, app/src/main/res/values/versions.xml
=> File download : notification message fix (Fixes #802)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java, app/src/main/res/values/versions.xml
=> Checkbox selection fixed in courses(Connects #803)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/submission/AdapterMySubmission.java, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BaseAchievementFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.java, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java, app/src/main/res/values/versions.xml
=> Edit achievement : date format fix and refactor (Fixes #797) (#810)

app/build.gradle, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/versions.xml
=> App crash fix for mobile phone (Fixes #820)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/layout/layout_child_login.xml, app/src/main/res/values/versions.xml
=> Child mode password field bug fix (Fixes #822)

app/build.gradle, app/src/main/res/layout/activity_splash.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Changed child mode to easy mode (Fixes #825)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeam.java, app/src/main/res/layout/layout_user_list.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Child mode : search feature in user list (Fixes #818)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmNews.java, app/src/main/java/org/ole/planet/myplanet/model/RealmTag.java, app/src/main/java/org/ole/planet/myplanet/service/AutoSyncService.java, app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java, app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java, app/src/main/res/layout/activity_splash.xml, app/src/main/res/layout/alert_input.xml, app/src/main/res/layout/card_profile.xml, app/src/main/res/layout/fragment_news.xml, app/src/main/res/layout/layout_child_login.xml, app/src/main/res/layout/row_news.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Feature news and Sync news (Fixes #828)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.java, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.java, app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/alert_manager_login.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml, app/src/main/res/xml/pref.xml
Now we can add manager from setting.
=> Manage mode added (Fixes #830)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/values/versions.xml
=> Manager mode : app stuck issue fixed (Fixes #841)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/values/versions.xml
=> Search condition change (Fixes #838)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.java, app/src/main/res/values/versions.xml
=> Admin not allowed to login (Fixes #848)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/res/layout/row_news.xml, app/src/main/res/values/versions.xml
=> Edit / delete news only by owner (Fixes #850)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/model/RealmAchievement.java, app/src/main/java/org/ole/planet/myplanet/model/RealmFeedback.java, app/src/main/java/org/ole/planet/myplanet/model/RealmMessage.java, app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.java, app/src/main/java/org/ole/planet/myplanet/model/RealmNews.java, app/src/main/java/org/ole/planet/myplanet/model/RealmOfflineActivity.java, app/src/main/java/org/ole/planet/myplanet/model/RealmRating.java, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.java, app/src/main/java/org/ole/planet/myplanet/model/RealmTag.java, app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java, app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/feedback/AdapterFeedback.java, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/Constants.java, app/src/main/res/layout/fragment_feedback_list.xml, app/src/main/res/layout/row_feedback.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
#853
@leomaxi please provide some feedback
=> Feedback list(Fixes #853)

app/build.gradle, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml, gradle.properties
fixes: Changed spelling of Mangerial to manager.
=> changing mangerial to manager mode

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/values/versions.xml
=> Dashboard  null pointer exception fixed (Fixes #864)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.java, app/src/main/res/layout/home_card_mylife.xml, app/src/main/res/values/versions.xml
Checkout this branch as it fixes the issue #832
=> news-icon-works-bell fixes #832

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java, app/src/main/res/layout/content_team_detail_tab.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Added discussion in my teams (Fixes #871 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/library/CollectionsFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/layout/fragment_collections.xml, app/src/main/res/values/versions.xml
=> Collection :  unselect tag fix (Fixes)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceFragment.java, app/src/main/res/values/versions.xml, app/src/main/res/xml/provider_paths.xml
=> Video recorder crash fix (Fixes #880 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/values/versions.xml
#884
courses collection crash + library nodata text showing when filtered is cleared  fix
=> courses collection crash fix (Fixes #884)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/ui/feedback/AdapterFeedback.java, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.java, app/src/main/res/layout/activity_feedback_detail.xml, app/src/main/res/values/versions.xml
=> Added feedback detail (Fixes #882 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.java, app/src/main/java/org/ole/planet/myplanet/model/RealmNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java, app/src/main/res/layout/content_team_detail_tab.xml, app/src/main/res/layout/fragment_news.xml, app/src/main/res/layout/row_news.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> News reply feature (Fixes #881)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/layout/dialog_server_url_.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
Fixes #875 
Added a Radio button for protocol in the settings Fragment.
=> radio-buttons-protocol

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/viewer/WebViewActivity.java, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/versions.xml
@leomaxi  @lmmrssa i've fixed the layout issue. But after update of new planet the web app is not opening in browser too. So became a member page is showing blank page.
Not working in browser , with android 5.1 but working in android 6+
=> Become member button not visible issue fixed (Fixes #889)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/feedback/AdapterFeedback.java, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.java, app/src/main/res/drawable/bg_grey.xml, app/src/main/res/drawable/bg_primary.xml, app/src/main/res/drawable/custom_border.xml, app/src/main/res/layout/fragment_feedback_list.xml, app/src/main/res/layout/row_feedback.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml
=> Changed feedback list ui (Fixes #867)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java, app/src/main/res/layout/activity_reply.xml, app/src/main/res/layout/content_team_detail_tab.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
Created another page for showing reply .
=> Reply issues fix (Fixes #897)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.java, app/src/main/res/layout/card_profile.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Survey : change text and show no data message (Fixes #900)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/model/RealmApkLog.java, app/src/main/res/values/versions.xml
=> Added time in apk logs (Fixes #914)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/KeyboardUtils.java, app/src/main/res/layout/activity_dashboard.xml, app/src/main/res/layout/fragment_my_course.xml, app/src/main/res/layout/fragment_my_library.xml, app/src/main/res/layout/fragment_news.xml, app/src/main/res/values/versions.xml
Fixes #901 
Please have a look at the code. Everything works. Any suggestions for improvements are welcome. Thank you.
=> Auto hide Keyboard Fixes #901

app/build.gradle, app/src/main/res/layout/fragment_course_detail.xml, app/src/main/res/layout/fragment_library_detail.xml, app/src/main/res/values/versions.xml
=> Added Padding for library_detail fragment and course_detail fragment (Fixes #846)

app/build.gradle, app/src/main/res/layout/fragment_take_course.xml, app/src/main/res/values/versions.xml
=> Hide progress bar in course detail (Fixes #903)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/res/values/versions.xml
=> Edit delete news bug fix (Fixes #918)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.java, app/src/main/res/layout/home_card_mylife.xml, app/src/main/res/values/versions.xml
Fixes #899 
@rrijal53 @jeevast Please have a look.
=> Add toast bell dashboard N/A features Fixes #899

app/build.gradle, app/src/main/res/layout/bell_actionbar_items.xml, app/src/main/res/values/versions.xml
=> Make bell action bar scrollable

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.java, app/src/main/java/org/ole/planet/myplanet/ui/submission/AdapterMySubmission.java, app/src/main/java/org/ole/planet/myplanet/ui/submission/MySubmissionFragment.java, app/src/main/res/values/versions.xml
=> Fixed submission upload issue (Fixes #920)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.java, app/src/main/res/values/versions.xml
=> News : Delete and edit bug fix (Fixes #928)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.java, app/src/main/res/layout/app_bar_bell.xml, app/src/main/res/values/versions.xml
=> sync now from bell theme (Fixes #927)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/CheckboxListView.java, app/src/main/res/values/versions.xml
=> Disable download  is resource not selected(Fixes #931)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.java, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.java, app/src/main/java/org/ole/planet/myplanet/model/RealmNews.java, app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java, app/src/main/res/values/versions.xml
=> Team new field added + post team activity log (Fixes #934 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/layout/fragment_home_bell.xml, app/src/main/res/values/versions.xml
=> Add resource from bell theme (Fixes #940)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.java, app/src/main/res/values/versions.xml
This PR half fixes #916. click on MyLibrary, and Mycourse to open the fragments of it's own in bell dashboard
=> Bell theme link

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.java, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/res/layout/fragment_news.xml, app/src/main/res/values/versions.xml
=> Place holder when no news Fixes #908

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.java, app/src/main/res/layout/home_card_mylife.xml, app/src/main/res/values/versions.xml
Toast message for myLife,and myTeam is added. fixes #953
=> added-toast-messages fixes #953

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.java, app/src/main/res/values/versions.xml
=> Open profile fragment on profile image and name click (Fixes #952)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java, app/src/main/res/values/versions.xml
=>  Always enable download all button in resource dialog (Fixes #948)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/layout/app_bar_bell.xml, app/src/main/res/layout/bell_actionbar_items.xml, app/src/main/res/menu/menu_bell_dashboard.xml, app/src/main/res/values/versions.xml
Sync now, logout and settings moved to drop down.
=> Change menu bar scrolling Fixes #951

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/res/values/versions.xml
=> Empty list textview update for Our courses and our library Fix #949

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/Reference.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/references/ReferenceFragment.java, app/src/main/res/drawable/ic_dictionary.xml, app/src/main/res/layout/fragment_reference.xml, app/src/main/res/layout/row_reference.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Reference page (Fixes #944)

app/build.gradle, app/src/main/res/layout/home_card_mylife.xml, app/src/main/res/values-normal/dimens.xml, app/src/main/res/values/versions.xml
=> Bell theme : Fixed ui on small device (Fixes #943)

app/build.gradle, app/src/main/res/layout/fragment_achievement.xml, app/src/main/res/values/versions.xml
=> Achievement icon inside page Fixes #950

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.java, app/src/main/res/values/versions.xml
=> Show community name in profile (Fixes #980)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmFeedback.java, app/src/main/res/values/versions.xml
=> fixed feedback crash(Fixes #983)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/MyLife/LifeFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/layout/fragment_life.xml, app/src/main/res/values/versions.xml
A static page for myLife fragment is created, clicking on myLife icon on the bell-dashboard-theme leads to this myLife Fragment. partially solves #970
=> MyLife-fragment-creation

app/src/main/res/drawable/buttonblue.xml, app/src/main/res/drawable/buttongrey.xml, app/src/main/res/layout/activity_splash.xml, app/src/main/res/layout/alert_add_attachment.xml, app/src/main/res/layout/edit_attachement.xml, app/src/main/res/layout/edit_other_info.xml, app/src/main/res/layout/fragment_achievement.xml, app/src/main/res/layout/fragment_course_detail.xml, app/src/main/res/layout/fragment_course_step.xml, app/src/main/res/layout/fragment_edit_achievement.xml, app/src/main/res/layout/fragment_in_active_dashboard.xml, app/src/main/res/layout/fragment_library_detail.xml, app/src/main/res/layout/fragment_my_course.xml, app/src/main/res/layout/fragment_my_library.xml, app/src/main/res/layout/fragment_my_meetup_detail.xml, app/src/main/res/layout/fragment_my_teams_detail.xml, app/src/main/res/layout/fragment_rating.xml, app/src/main/res/layout/fragment_take_course.xml, app/src/main/res/layout/fragment_take_exam.xml, app/src/main/res/layout/fragment_user_information.xml, app/src/main/res/layout/row_achievement.xml, app/src/main/res/layout/row_survey.xml, app/src/main/res/values/styles.xml
Fixes #977
Buttons were spaced out to avoid cramp and added a radius so they look nicer.
=> Buttons spaced out and rounded (fixes #977)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java, app/src/main/res/values/versions.xml
=> Fixed message not showing issue in team detail(Fixes #1004)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.java, app/src/main/res/values/versions.xml
A silent photo is taken and stored in the device itself when the user navigates through courses.
=> course-security-photo fixes #994

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyPersonal.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/AdapterMyPersonal.java, app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/MyPersonalsFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/layout/alert_my_personal.xml, app/src/main/res/layout/fragment_my_personals.xml, app/src/main/res/layout/home_card_mylife.xml, app/src/main/res/layout/row_my_personal.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> My personals (Fixes #1011)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/CameraUtils.java, app/src/main/res/values/versions.xml
while clicking take test, the photo is automatically taken and stored in the device.
=> photo-during-exam fixes #1014

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/service/AudioRecorderService.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.java, app/src/main/res/drawable/ic_stop.xml, app/src/main/res/layout/activity_pdfreader.xml, app/src/main/res/values/versions.xml
#896 #1029 
Added in app audio recorder in PDFReader, Now need to save that audio in database and add feature to play that audio.
Please provide your feedback @leomaxi
=> Record audio from app (Fixes #1029 #896)

app/build.gradle, app/src/main/res/layout/fragment_take_course.xml, app/src/main/res/values/versions.xml
=> Takecourse title visibility

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyLife.java, app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.java, app/src/main/res/values/versions.xml
=> Change condition

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.java, app/src/main/res/values/versions.xml
=> Empty position my life crash fix

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java, app/src/main/res/values/versions.xml
=> Pictures only on take exams

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/callback/OnSelectedMyPersonal.java, app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/AdapterMyPersonal.java, app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/MyPersonalsFragment.java, app/src/main/res/layout/fragment_my_personals.xml, app/src/main/res/values/versions.xml
=> my personal show no data message (Fixes #1040)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/res/values/versions.xml
=> Team upload issue (Fixes #1054)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.java, app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.java, app/src/main/java/org/ole/planet/myplanet/ui/helpwanted/HelpWantedFragment.java, app/src/main/res/layout/fragment_help_wanted.xml, app/src/main/res/values/versions.xml
=> help wanted (Fixes #1067)

app/build.gradle, app/src/main/res/layout/fragment_team.xml, app/src/main/res/layout/item_team_list.xml, app/src/main/res/values/versions.xml
=> Differentiate heading from list myTeam

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/values/versions.xml
Double tap anywhere to open Reference Fragment
=> Double tap gesture Fixes #969

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterVitalSign.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddVitalSignActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/RealmVitalSign.java, app/src/main/res/layout/activity_add_vital_sign.xml, app/src/main/res/layout/alert_users_spinner.xml, app/src/main/res/layout/fragment_my_health.xml, app/src/main/res/layout/fragment_vital_sign.xml, app/src/main/res/layout/item_vital_sign.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
#1076
Need to create detail page to show all the report. Will be doing that in another PR
=> My health (Fixes #1076)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java, app/src/main/res/values/versions.xml
=> Fix course list with no tag error (Fixes #1095)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmTeamTask.java, app/src/main/java/org/ole/planet/myplanet/service/AutoSyncService.java, app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/AdapterTask.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/Constants.java, app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.java, app/src/main/res/layout/alert_task.xml, app/src/main/res/layout/fragment_team_task.xml, app/src/main/res/layout/row_task.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Team task (Fixes #1097)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.java, app/src/main/java/org/ole/planet/myplanet/ui/team/BaseTeamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/AdapterTeamCourse.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/TeamCourseFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/AdapterTeamResource.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.java, app/src/main/res/values/versions.xml
=> Only team creator owner will have X

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java, app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/values/versions.xml
=> First time sync bug (Fixes #1037)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.java, app/src/main/res/layout/fragment_team_resource.xml, app/src/main/res/values/versions.xml, build.gradle
=> Add resource in team (Fixes #1022)

app/build.gradle, app/src/main/res/layout/fragment_home.xml, app/src/main/res/values/versions.xml, build.gradle
=> dashboard bug fix (Fixes #1109)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmTeamTask.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/AdapterTask.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.java, app/src/main/res/layout/row_task.xml, app/src/main/res/values/versions.xml, build.gradle
=> Task assign (Fixes #1105)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/model/RealmApkLog.java, app/src/main/res/values/versions.xml
=> Added version name (Fixes #1124)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.java, app/src/main/res/values/versions.xml, app/src/main/res/xml/pref.xml
https://github.com/open-learning-exchange/myplanet/issues/1120
=> Course Beta on by default (Fixes #1120)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/datamanager/DatabaseService.java, app/src/main/java/org/ole/planet/myplanet/model/RealmApkLog.java, app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java, app/src/main/res/values/versions.xml
=> App stuck and realm instance leaked issue  fixed   (Fixes #1134 #1101)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.java, app/src/main/res/values/versions.xml
=> offline visits bug fix (Fixes #1135)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.java, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterSteps.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.java, app/src/main/res/layout/fragment_course_detail.xml, app/src/main/res/layout/row_steps.xml, app/src/main/res/values/versions.xml
=> course summary (Fixes #1099)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.java, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterSteps.java, app/src/main/res/values/versions.xml
=> no of questions bug fix (Fixes #1141)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/model/RealmTeamTask.java, app/src/main/java/org/ole/planet/myplanet/service/TaskNotificationService.java, app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.java, app/src/main/res/values/versions.xml
=> Task reminder (Fixes #1122)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeam.java, app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.java, app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/AdapterTeamCourse.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMemeber.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/JoinedMemberFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/AdapterTeamResource.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/AdapterTask.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1147
=> Assign task in teams

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.java, app/src/main/res/values/versions.xml
=> Added time picker in task (Fixes #1145)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.java, app/src/main/java/org/ole/planet/myplanet/ui/mylife/LifeFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/mylife/helper/ItemTouchHelperViewHolder.java, app/src/main/java/org/ole/planet/myplanet/ui/mylife/helper/SimpleItemTouchHelperCallback.java, app/src/main/res/values/versions.xml
=> My life open fragment

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterSteps.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CoursePagerAdapter.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.java, app/src/main/res/layout/fragment_course_detail.xml, app/src/main/res/layout/fragment_course_step.xml
https://github.com/open-learning-exchange/myplanet/issues/1049
=> Course fix

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.java, app/src/main/res/values/versions.xml
=> Enterprise not creating issue fix (Fixes #1155)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.java, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterFinance.java, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.java, app/src/main/res/layout/add_transaction.xml, app/src/main/res/layout/fragment_finance.xml, app/src/main/res/layout/row_finance.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Finance in enterprise (Fixes #1152)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.java, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterFinance.java, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.java, app/src/main/res/layout/fragment_finance.xml, app/src/main/res/layout/row_finance.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
#1165  https://github.com/open-learning-exchange/myplanet/issues/1167
=> Add transaction bug fix (Fixes #1165)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterFinance.java, app/src/main/res/layout/row_finance.xml, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1168
=> Ent-finances (Fixes #1168)

app/build.gradle, app/src/main/res/layout/fragment_finance.xml, app/src/main/res/values/versions.xml
=> Finance header change (Fixes #1170)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.java, app/src/main/res/layout/fragment_team_task.xml, app/src/main/res/values/versions.xml
=> Filter task (Fixes #1159)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.java, app/src/main/res/values/versions.xml
=> Sort transaction (Fixes #1173 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.java, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1178
=> Fix transaction date error (Fixes #1178)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/AdapterTask.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.java, app/src/main/res/layout/fragment_finance.xml, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1176
=> Enterprise total row (Fixes #1176)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.java, app/src/main/res/values/versions.xml
Dashboard differentiate enterprises from team with **Bold**
=> Dashboard differentiate enterprises from team

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMeetup.java, app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.java, app/src/main/java/org/ole/planet/myplanet/utilities/Constants.java, app/src/main/res/layout/add_meetup.xml, app/src/main/res/layout/fragment_enterprise_calendar.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
#1157
Looking for good calendar library for our use case , please suggest @leomaxi
=> Calendar Fragment in teams(Fixes #1157)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterFinance.java, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.java, app/src/main/res/layout/fragment_finance.xml, app/src/main/res/values/versions.xml
=> Filter transaction by date (Fixes #1192)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java, app/src/main/res/layout-large-land/activity_child_login.xml, app/src/main/res/layout-normal-land/activity_child_login.xml, app/src/main/res/layout-small-land/activity_child_login.xml, app/src/main/res/layout-xlarge-land/activity_child_login.xml, app/src/main/res/layout/activity_child_login.xml, app/src/main/res/layout/fragment_finance.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1189
`Debit alignment`
https://github.com/open-learning-exchange/myplanet/issues/1186
=> Child mode - team list fill space ( Fixes #1189 , Fixes #1186 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.java, app/src/main/res/values/versions.xml
=> fixed search issue  in team/enterprise list (Fixes #1183)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/AdapterTask.java, app/src/main/res/values/versions.xml
=> Task : Format deadline (Fixes #1182)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterFinance.java, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.java, app/src/main/res/layout/fragment_finance.xml, app/src/main/res/values/versions.xml
=> sort finance list(Fixes #1201)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmFeedback.java, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.java, app/src/main/res/layout/item_team_list.xml, app/src/main/res/values/versions.xml
=> Add feedback btn to both lists

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterVitalSign.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.java, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1219
show patient full name in myhealth
=> show patient name (Fixes #1219)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/Constants.java, app/src/main/res/layout/fragment_vital_sign.xml, app/src/main/res/values/versions.xml, app/src/main/res/xml/pref.xml
https://github.com/open-learning-exchange/myplanet/issues/1223
=> myHealth basic view (Fixes #1223)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealth.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.java, app/src/main/res/values/versions.xml
=> Update health record

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/utilities/AndroidDecrypter.java, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/pull/1203
=> CBC Encryption Implementation (Fixes #1128)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/values/versions.xml, app/src/main/res/xml/pref.xml
https://github.com/open-learning-exchange/myplanet/issues/1232
=> Make room for auto sync option

app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/ui/SplashActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/Constants.java, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml
=> Force weekly sync  (Fixes #1230 , Fixes #1229)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/layout/fragment_my_course.xml, app/src/main/res/layout/fragment_my_library.xml, app/src/main/res/values/versions.xml
=> Show current fragment Fixes #1244

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.java, app/src/main/res/layout/fragment_team_task.xml, app/src/main/res/values/versions.xml
#1181
@ChiragAwale  check this one, you need to use appcompat version of  library in which targetSdk is less than 28 i.e. https://github.com/nex3z/ToggleButtonGroup/releases/tag/v1.1.8
=> Change toggle button in task

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1248
=> fix last sync not showing on login page (Fixes #1248)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java, app/src/main/res/values/versions.xml
=> Support more extensions (Fixes #1240)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/AdapterTask.java, app/src/main/res/values/versions.xml
=> show task description (Fixes #1252)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmTag.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/library/CollectionsFragment.java, app/src/main/res/values/versions.xml
=> Collection issue fixed (Fixes #1242 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.java, app/src/main/res/layout/fragment_team_task.xml, app/src/main/res/values/versions.xml
=> show completed task in different list (Fixes #1220)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/mylife/LifeFragment.java, app/src/main/res/layout/row_life.xml, app/src/main/res/values/versions.xml
=> Adjust mylife Fixes #1185

app/build.gradle, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Fix title error Fixes #1227

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmTag.java, app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.java, app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java, app/src/main/java/org/ole/planet/myplanet/utilities/Constants.java, app/src/main/res/values/versions.xml
=> team visits fix (Fixes #1243)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/res/values/versions.xml
=> team log sync bug fix (Fixes #1264)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.java, app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.java, app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.java, app/src/main/res/drawable/ic_my_survey.xml, app/src/main/res/values/versions.xml, build.gradle
=> fix nation survey not syncing issue (Fixes #1262)

app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerParentFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/layout/fragment_my_course.xml, app/src/main/res/layout/fragment_my_library.xml
=> Sort resources Fixes #1268

app/build.gradle, app/src/main/res/layout/fragment_my_submission.xml, app/src/main/res/values/versions.xml
=> Disable multi line search my survey Fixes #1272

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1281
=> Change Discussion to Chats (Fixes #1281)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.java, app/src/main/java/org/ole/planet/myplanet/ui/mylife/AdapterMyLife.java, app/src/main/res/layout/item_my_life.xml, app/src/main/res/values/versions.xml
#1282
We have problem while uploading submissions , i m fixing that issue in another PR.
=> show survey count in dashboard(Fixes #1282)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1286
=> Member name list in myHealth (Fixes #1286)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/res/values/versions.xml
=> upload submision/survey result (Fixes #1289)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.java, app/src/main/res/values/versions.xml
=> Fix network on main thread issue (Fixes #1291)

app/build.gradle, app/src/main/res/layout/alert_health_list.xml, app/src/main/res/values/versions.xml
=> Disable line break myhealth search

app/build.gradle, app/src/main/res/layout/fragment_my_library.xml, app/src/main/res/values/versions.xml
=> Theme match

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.java, app/src/main/res/layout/fragment_send_survey.xml, app/src/main/res/layout/row_survey.xml, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1298
=> Remove send survey (Fixes 1298)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.java, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/survey/AdapterSurvey.java, app/src/main/res/values/versions.xml
=> Record take survey (Fixes #1283)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java, app/src/main/res/values/versions.xml
=> Pending survey list error fix (Fixes #1326)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterHealthExamination.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/RealmExamination.java, app/src/main/res/layout/activity_add_examination.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Added diagnosis note (Fixes #1322)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1329
=> Incorrect answer toast (Fixes #1329)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmApkLog.java, app/src/main/java/org/ole/planet/myplanet/model/RealmMyPersonal.java, app/src/main/java/org/ole/planet/myplanet/model/RealmOfflineActivity.java, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.java, app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.java
=> Add device name in logs (Fixes #1344 )

app/build.gradle, app/src/main/res/layout/item_home_my_team.xml, app/src/main/res/values/versions.xml
=> my team card size change (Fixes #1339 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/MyPlanet.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/NetworkUtils.java, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1364
=> custom device name in db (Fixes #1364)

app/build.gradle, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Change Android App name to myPlanet (fixes #1354)

app/build.gradle, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Update Eg. Ip address (Fixes #1352)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.java, app/src/main/java/org/ole/planet/myplanet/ui/community/AddLinkFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeam.java, app/src/main/res/layout/alert_add_link.xml, app/src/main/res/layout/fragment_add_link.xml, app/src/main/res/layout/fragment_community.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Show link in community (Fixes #1363 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt, app/src/main/res/layout/fragment_community.xml, app/src/main/res/values/versions.xml
=> Hide community update for normal user (Fixes #1377)

app/build.gradle, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1383
=> Change to FGM ( Fixes #1383 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt, app/src/main/res/values/versions.xml
=> Calendar start end equal date issue fixed (Fixes #1390)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt, app/src/main/res/values/versions.xml
=> show event detail on click (Fixes #1389)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.java, app/src/main/res/layout/bell_actionbar_items.xml, app/src/main/res/layout/card_profile_bell.xml, app/src/main/res/values/versions.xml
=> remove survey from tab (Fixes #1392)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.java, app/src/main/res/layout/item_home_my_team.xml, app/src/main/res/values/versions.xml
=> Fix width and button fixes #1366

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/values/versions.xml
=> both push and pull from sync button of login page (Fixes #1397)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> change team detail tabs text and order (Fixes #1398)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/callback/NotificationCallback.java, app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealth.java, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.java, app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/AdapterNotification.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java, app/src/main/res/values/versions.xml
=> sync key and iv from user db (Fixes #1371)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmTag.java, app/src/main/java/org/ole/planet/myplanet/ui/library/CollectionsFragment.java, app/src/main/res/values/versions.xml
=> Fixed duplicate collection issue (Fixes #1409)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/layout-large-land/activity_child_login.xml, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_child_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_child_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_child_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_child_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/versions.xml, app/src/main/res/xml/pref.xml
=> save username and password from setting (Fixes #1413)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.java, app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java, app/src/main/res/values/versions.xml
=> Batch resource sync (Fixes #1412)

app/build.gradle, app/src/main/res/layout/activity_add_examination.xml, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1424
=> fix vitals text input (Fixes #1424)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.java, app/src/main/res/values/versions.xml
=> Home notification button fix (Fixes #1423)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/layout/fragment_my_library.xml, app/src/main/res/values/versions.xml
=> collection title issue fixed (Fixes #1416)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceFragment.java, app/src/main/res/values/versions.xml
=> fixed image path issue (Fixes #1406)

app/src/main/java/org/ole/planet/myplanet/model/RealmAnswer.java, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java
https://github.com/open-learning-exchange/myplanet/issues/1434
https://github.com/open-learning-exchange/myplanet/issues/1435
=> Survey data fix (Fixes #1434 ,  Fixes #1435)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.java, app/src/main/res/values/versions.xml
=> Tab order fix in team detail (Fixes #1444)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmitPhotos.java, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1451
=> Fix photo submission metadata (Fixes #1451)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt, app/src/main/res/layout/calendar_day.xml, app/src/main/res/layout/fragment_enterprise_calendar.xml, app/src/main/res/values/versions.xml
=> change calendar view (fixes #1391)

app/build.gradle, app/src/main/res/layout/fragment_take_exam.xml, app/src/main/res/values/versions.xml
=> change take survey (Fixes #1457)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java, app/src/main/java/org/ole/planet/myplanet/model/MyPlanet.java, app/src/main/java/org/ole/planet/myplanet/service/AutoSyncService.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java, app/src/main/res/values/versions.xml
=> Upload usages logs to db (Fixes #1440)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java, app/src/main/res/layout/fragment_course_step.xml, app/src/main/res/values/versions.xml
If there are no test questions, make the `TAKE TEST` button invisible. Fixes #1351
=> update method hideTestIfNoQuestion (fixes #1351)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.java, app/src/main/res/values/versions.xml
=> update add course toast message (fixes #1461)

app/build.gradle, app/src/main/res/layout/card_profile_bell.xml, app/src/main/res/values/versions.xml
=> fix home page ui for small devices (Fixes  #1464 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt, app/src/main/res/layout/fragment_enterprise_calendar.xml, app/src/main/res/values-land/dimens.xml, app/src/main/res/values-normal/dimens.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/versions.xml
=> fix calendar ui (Fixes #1462)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java, app/src/main/res/values/versions.xml
=> markdown highlighter

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.java, app/src/main/res/values/versions.xml
=> sort chat list (Fixes #1469)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/layout-large-land/activity_child_login.xml, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_child_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_child_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_child_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_child_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/versions.xml
=> add device name in login (Fixes #1372)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/values/versions.xml
=> disable open reference page on double click (Fixes #1180)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/MyPlanet.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/VersionUtils.java, app/src/main/res/values/versions.xml
#1476
change id and upload myplanet activities in old format
=> Change build id to android id in myplanet activities (Fixes #1476)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.java, app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterHealthExamination.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/RealmExamination.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/AndroidDecrypter.java, app/src/main/res/values/versions.xml
=> fix health sync and show self examination (Fixes #1473)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerParentFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/layout/fragment_my_library.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
implemented spinner, sort by upload date and remove order by date button from library fragment
=> Sort by date (Fixes #1485)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/res/layout/row_news.xml, app/src/main/res/values/versions.xml
=> Change News list ui (Fixes #1492)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.java, app/src/main/res/values/versions.xml
=> change layout manager on orientation change (Fixes #1496)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.java, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/res/layout/fragment_community.xml, app/src/main/res/values/versions.xml
=> remove our news from dashboard and fix show reply issue (Fixes #1503)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmStepExam.java, app/src/main/res/values/versions.xml
=> Add missing fields in submission (Fixes #1509)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/community/AdapterLeader.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityPagerAdapter.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/LeadersFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMemeber.java, app/src/main/res/values/versions.xml
=> added community leader list (Fixes #1515)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityPagerAdapter.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/HomeCommunityDialogFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/ReplyActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/layout/fragment_community.xml, app/src/main/res/layout/fragment_team_detail.xml, app/src/main/res/values/versions.xml
=> Added community fragment in login page (Fixes #1524)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/base/BaseActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/AboutActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DisclaimerActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt, app/src/main/res/layout/activity_news_detail.xml, app/src/main/res/layout/content_news_detail.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/versions.xml
=> News detail (Fixes #1525)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityPagerAdapter.kt, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/res/layout/fragment_news.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Add news from community (Fixes #1523 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.java, app/src/main/res/values/versions.xml
=> Added markdown view (Fixes #1529  )

app/build.gradle, app/src/main/res/layout/row_news.xml, app/src/main/res/values/versions.xml
=> change news list layout  (Fixes #1540)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.java, app/src/main/res/layout/content_team_detail_tab.xml, app/src/main/res/layout/fragment_team_detail.xml, app/src/main/res/layout/row_member_request.xml, app/src/main/res/values/styles.xml
Version 6.82 - removed comments, updated buttons and switched calendar/task to mimic planet
=> update enterprise - fixes #1541 and #1543

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.java, app/src/main/res/values/versions.xml
=> fix manager login issue (Fixes #1533)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityPagerAdapter.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt, app/src/main/res/layout/button_single.xml, app/src/main/res/layout/fragment_services.xml, app/src/main/res/values/versions.xml
=> add services fragment (Fixes #1536 )

app/build.gradle, app/src/main/res/layout/button_single.xml, app/src/main/res/layout/fragment_services.xml, app/src/main/res/values/versions.xml
=> services ui change (Fixes #1552)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.java, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.java, app/src/main/res/values/versions.xml
=> only manager or leader can add update finance (Fixes #1537)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/layout-large-land/activity_child_login.xml, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_child_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_child_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_child_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_child_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/versions.xml
=> add open community from login (Fixes #1559)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/res/layout/row_news.xml, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1564
=> Read News text (Fixes #1564)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityTabFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/HomeCommunityDialogFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.java, app/src/main/res/layout/fragment_team_detail.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/versions.xml
=> Add leave button in team detail (Fixes #1542)

app/build.gradle, app/src/main/res/layout/fragment_library_detail.xml, app/src/main/res/values/versions.xml
=> fix library detail button alignment (Fixes #1568)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/res/values/versions.xml
=> hide edit delete btn in login (fixes #1569)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/res/values/versions.xml
=> remove old image when creating new story (Fixes #1566)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/survey/SendSurveyFragment.java, app/src/main/res/values/versions.xml
=> change parent id to examId@CourseId (Fixes #1573)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/values/versions.xml, app/src/main/res/xml/pref.xml
=> Enable news image beta by default (Fixes #1578)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmAnswer.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java, app/src/main/res/values/versions.xml
=> fixed submission answer isue (Fixes #1581 )

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/base/BaseActivity.java, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.java, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterMyProgress.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterProgressGrid.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseProgressActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/MyProgressFragment.kt, app/src/main/res/layout/activity_course_progress.xml, app/src/main/res/layout/row_my_progress_grid.xml, app/src/main/res/values/versions.xml
=> Course score card (Fixes #1582)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/layout/fragment_my_library.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Library Sort By UX

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.java, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/AdapterMyPersonal.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BaseAchievementFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.java, app/src/main/res/values/versions.xml
used trim() to clear white space on user entries
=> Remove whitespace - Fixes #1597

app/build.gradle, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout/fragment_take_course.xml, app/src/main/res/layout/item_my_life.xml, app/src/main/res/values/versions.xml
=> fix ui issue (Fixes #1602)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/survey/SendSurveyFragment.java, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1609
=> Survey data error

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseNewsAdapter.java, app/src/main/java/org/ole/planet/myplanet/model/RealmNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/res/layout/row_news.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> share news with community (Fixes #1592)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.java, app/src/main/res/layout/alert_create_team.xml, app/src/main/res/values/versions.xml
=> public team/enterprise (Fixes #1601)

app/build.gradle, app/src/main/res/layout/fragment_take_exam.xml, app/src/main/res/values/versions.xml
=> change exam ui (fixes #1611)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/service/AutoSyncService.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.java, app/src/main/res/layout/activity_course_progress.xml, app/src/main/res/layout/row_my_progress_grid.xml, app/src/main/res/values/versions.xml
=> My progress ui change (Fixes #1615)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterCalendar.java, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterFinance.java, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.java, app/src/main/res/layout/fragment_team_detail.xml, app/src/main/res/values/versions.xml
I have replaced the text My Planet with myPlanet and bolded the text in the enterprise menu.
fixes #1560
=> Changed text to myPlanet and bolded the title (fixes #1560)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmAnswer.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java, app/src/main/res/values/versions.xml
=> fix survey data (Fixes #1624 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1625
=> Fix app crash (Fixes #1625)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java, app/src/main/res/values/versions.xml
=> Course / survey issue fixed (Fixes #1628 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.java, app/src/main/java/org/ole/planet/myplanet/model/RealmNews.java, app/src/main/java/org/ole/planet/myplanet/service/SyncManager.java, app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.java, app/src/main/res/values/versions.xml
=> Sync in bulk(Fixes #1477)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/versions.xml
=> Manager login change (Fixes #1589)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmCourseActivity.java, app/src/main/java/org/ole/planet/myplanet/service/AutoSyncService.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.java, app/src/main/res/values/versions.xml, build.gradle
=> upload course activities (Fixes #1629 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.java, app/src/main/res/values/versions.xml
=> bug fix : team visits (Fixes #1634)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.java, app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMemeber.java, app/src/main/res/values/versions.xml
=> fixed team visit (Fixes #1638)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt, app/src/main/res/layout/activity_news_detail.xml, app/src/main/res/layout/content_news_detail.xml, app/src/main/res/layout/image_slider_layout_item.xml, app/src/main/res/values/versions.xml
=> show multiple image in detail page (Fixes #1641)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java, app/src/main/res/values/versions.xml
=> retake button in course (Fixes #1650)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt, app/src/main/res/layout/activity_news_detail.xml, app/src/main/res/values/versions.xml
=> resize image (Fixes #1657 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/model/RealmSearchActivity.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmTag.java, app/src/main/java/org/ole/planet/myplanet/service/AutoSyncService.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.java, app/src/main/res/values/versions.xml
=> save resource search activity (Fixes #1658 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/layout/app_bar_bell.xml, app/src/main/res/layout/card_profile_bell.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/versions.xml
=> open drawer (Fixes #1645)

app/build.gradle, app/src/main/res/layout/fragment_home_bell.xml, app/src/main/res/values/versions.xml
=> change fab icon (Fixes #1666 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/Constants.java, app/src/main/res/values/versions.xml
=> load local images and fix image not loading issue (Fixes #1673) (#1671)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1646
=> Hide "Take Test" for non course members (Fixes #1646)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.java, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/values/versions.xml
=> Upload later and skip min version  (Fixes #1681 )

app/src/main/res/layout/fragment_rating.xml, app/src/main/res/values/styles.xml
=> Rating bar color (Fixes #1679)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/values/versions.xml
=> added community in drawer (Fixes #1680)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmNews.java, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/res/values/versions.xml
=> fix crash because of empty view in object (Fixes #1691)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.java, app/src/main/res/values/versions.xml
=> reply showing in news list (Fixes #1693)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/res/values/versions.xml
=> hide add label in login page (Fixes #1696)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt, app/src/main/res/values/versions.xml
=> wrap text around image (Fixes #1693)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealthPojo.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.java, app/src/main/res/values/versions.xml
=> health profile issue (Fixes #1704)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.java, app/src/main/java/org/ole/planet/myplanet/service/AutoSyncService.java, app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt, app/src/main/res/values/versions.xml
=> create member offline (Fixes #1702)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt, app/src/main/res/values/versions.xml
=> fixed dob issue (Fixes #1711 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java, app/src/main/res/values/versions.xml
=> validate email (Fixes #1714 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt, app/src/main/res/values/versions.xml
=> bug fix : enterprise not showing (Fixes #1716)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerParentFragment.java, app/src/main/res/values/versions.xml
=> hide course with empty title (Fixes #1741 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt, app/src/main/res/values/versions.xml
=> sync health alert(Fixes #1732)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealth.java, app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealthPojo.java, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.java, app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.java, app/src/main/res/values/versions.xml
=> sync health bug fixes (Fixes #1740)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java, app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealthPojo.java, app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.java, app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/RealmExamination.java, app/src/main/java/org/ole/planet/myplanet/utilities/AndroidDecrypter.java, app/src/main/res/layout/row_examination.xml, app/src/main/res/values/versions.xml
=> bug fix : health data fix (Fixes #1754)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt, app/src/main/res/values/versions.xml
=> Become member dob validation + hide buttons for normal user (Fixes #1760  #1759)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/versions.xml
=> feedback button in login (Fixes #1755)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/JsonUtils.java, app/src/main/res/layout/activity_add_examination.xml, app/src/main/res/values/versions.xml
=> Examination validation (Fixes #1758)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealthPojo.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt, app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.java, app/src/main/res/values/versions.xml
=> add new fields (Fixes #1750)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/MyPlanet.java, app/src/main/res/values/versions.xml
=> bug fix :  total used (Fixes #1774)

app/build.gradle, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/versions.xml
fixes #1776 
The phone login screens had a messed up layout where the logo/text would be crammed. I edited an XML file to constrain the layout so that it would not cram the logo/text together.
=> Fixed Login Page on Phone Screens (fixes #1776)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealth.java, app/src/main/java/org/ole/planet/myplanet/model/RealmMyHealthPojo.java, app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/JsonUtils.java, app/src/main/res/values/versions.xml
=> health bug fixes (Fixes #1772 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java, app/src/main/java/org/ole/planet/myplanet/service/TransactionSyncManager.java, app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.java, app/src/main/res/values/versions.xml
=> add health role in user db (Fixes #1771)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/layout/fragment_my_course.xml, app/src/main/res/values/versions.xml
=> sort fix library and course (Fixes #1794 #1793)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt, app/src/main/res/values/versions.xml
=> sort user in health (Fixes #1790)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java, app/src/main/res/values/versions.xml
=> save diagnosis notes (Fixes #1788)

app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterHealthExamination.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java
=> bugfix : accept decimal (Fixes #1801 #1799)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java, app/src/main/res/layout/fragment_user_profile.xml, app/src/main/res/values/versions.xml
User is now able to upload an image from their gallery for their profile image.
=> Allows for a User profile image (fixes #1730)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.java, app/src/main/res/values/versions.xml
=> fixed duplication user in search result (Fixes #1787)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/UserListArrayAdapter.kt, app/src/main/res/values/versions.xml
=> search by first name last name (Fixes #1800)

app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
=> change name format health (Fixes #1815)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.java, app/src/main/res/values/versions.xml
=> duplicate team after sync issue (Fixes #1838)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt, app/src/main/res/values/versions.xml
=> change team input message (Fixes #1834)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/res/values/versions.xml
=> bug fix : delete story (Fixes  #1839)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt, app/src/main/res/layout/fragment_vital_sign.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-land/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-normal/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> fab group (Fixes  #1828)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.java, app/src/main/res/layout/activity_become_member.xml, app/src/main/res/layout/bell_actionbar_items.xml, app/src/main/res/values/versions.xml
=> show team in drawer and top bar (Fixes #1848)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/UserListArrayAdapter.kt, app/src/main/res/values/versions.xml
=> fixed image issue in member list (Fixes #1844)

app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
=> fix missing app name (fixes #1849)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.java, app/src/main/res/values/versions.xml
=> user profile add field detail (Fixes #1862)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt, app/src/main/res/layout/fragment_vital_sign.xml, app/src/main/res/values/versions.xml
=> hide add member button for learner (Fixes #1865)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.java, app/src/main/res/values/versions.xml
=> bug fix : team resource not uploading (Fixes #1840 )

app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.java
=> leave team confirmation dialog (Fixes #1871)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/callback/TeamPageListener.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.java, app/src/main/res/values/versions.xml
=> bug fix add document not showing issue (Fixes #1887)

app/build.gradle, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
fixes #1873 
Before, the user would not be aware of the requirements to create a task. If they didn't fill out a certain field, their task would not be saved. 
I added (required) to the fields that were required.
=> Team Task Requirements (fixes #1873)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/layout/bell_actionbar_items.xml, app/src/main/res/layout/custom_tab.xml, app/src/main/res/values/versions.xml
=> refactor + change top navigation size (Fixes #1876)

app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterHealthExamination.java, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java, app/src/main/res/layout/alert_examination.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml
=> show health conditions  (Fixes #1900)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt, app/src/main/res/values/versions.xml
=> health worker add member fab issue fixed (Fixes #1896)

app/build.gradle, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
fixes #1894 
This PR adds (Systolic / Diastolic) to the hint of Blood Pressure.
=> Added format to Blood Pressure (fixes #1894)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.java, app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.java, app/src/main/res/layout/fragment_home_bell.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
Showing notification part is done, need to work on edit profile page.
=> Prompt if name is empty (Fixes #1895)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.java, app/src/main/res/layout/row_team_resource.xml, app/src/main/res/values/versions.xml
=> team document ui issue (fixes #1891)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.java, app/src/main/res/values/versions.xml
=> team member dialog fix (Fixes #1888)

app/build.gradle, app/src/main/res/layout/fragment_team_detail.xml, app/src/main/res/values/versions.xml
=> team tab ui (Fixes #1879)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/community/AddLinkFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeam.java, app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.java, app/src/main/java/org/ole/planet/myplanet/ui/team/BaseTeamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.java, app/src/main/res/values/versions.xml
=> create team on myplanet issue  (Fixes #1445)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/PlanFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.java, app/src/main/res/values/versions.xml
=> new team crash issue fixed (Fixes #1922)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryDetailFragment.java, app/src/main/res/layout/fragment_library_detail.xml, app/src/main/res/values/versions.xml
#1929
Library detail ui support for mobile device
=> library detail ui changes (Fixes #1929)

app/build.gradle, app/src/main/res/drawable/ic_filter.xml, app/src/main/res/layout/fragment_my_course.xml, app/src/main/res/values/versions.xml
=> filter button hide issue (Fixes #1931)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/res/drawable/ic_filter.xml, app/src/main/res/layout/fragment_my_course.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> Filter button hidden isssue (Fixes #1931)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt, app/src/main/res/values/versions.xml
fixes #1938 
Now submit button does not go back if the mandatory fields are empty.
=> Fix activity ending when mandatory fields are empty (fixes #1938)

app/build.gradle, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=> add trauma to health diagnosis list (Fixes #1936)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.java, app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.java, app/src/main/res/values/versions.xml
=> fixed next step navigation issue (Fixes #1947)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java, app/src/main/res/drawable/ic_send.xml, app/src/main/res/layout/activity_add_examination.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
=>  dynamic other diagnosis (Fixes #1949)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt, app/src/main/res/layout/alert_create_team.xml, app/src/main/res/values/versions.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Fix Create enterprise dialog (fixes #1961)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java, app/src/main/res/values/versions.xml
=> remove custom diagnosis issue (Fixes #1969)

app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.java
https://github.com/open-learning-exchange/myplanet/issues/1989
=> Ent leader cant remove himself (Fixes #1989)

app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java, app/src/main/res/drawable/login_file_upload_animation.xml
The following fix should stop the upload animation on frame one. Please help test the feature.
=> Resets the Sync Button to Frame 1 after (fixes #1926)

app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.java, app/src/main/res/layout/fragment_finance.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml
https://github.com/open-learning-exchange/myplanet/issues/1997
https://github.com/open-learning-exchange/myplanet/issues/1986
=> Handle archived record and negative balance caution  (Fixes #1997 , Fixes #1986)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.java, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1981
=> Remove "-" proceeding member name ( Fixes #1981 )

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/AdapterTask.java, app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
https://github.com/open-learning-exchange/myplanet/issues/1988
=> Task alert close instead of finish (Fixes #1988)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/SplashActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.java, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_splash.xml, app/src/main/res/values/versions.xml
=> Show available space on login screen (fixes #2008)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmTeamTask.java, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/AdapterTask.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.java, app/src/main/res/layout/row_task.xml, app/src/main/res/values/versions.xml
=> enterprise task bug fix (Fixes #1995)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/res/values/versions.xml
Fixes #1951
Now the user is asked before deleting the course and confirming that they do want to delete that course. Before, they could accidentally delete courses.
=> Delete Course Confirmation Dialog (fixes #1951)

.travis.yml, app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt
=> hide health sync dialog for guest user (Fixes #1975)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/callback/NotificationCallback.java, app/src/main/java/org/ole/planet/myplanet/model/RealmTeamTask.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/AdapterNotification.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt, app/src/main/res/values/versions.xml
=> show due tasks in notification (Fixes #2018)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.java, app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.java, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.java, app/src/main/res/values/versions.xml
=> hide leave button for team leader (Fixes #2031)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/values/versions.xml
=> Update last sync text on the Login screen after a sync (fixes #2050)

app/build.gradle, app/src/main/res/layout/item_team_list.xml, app/src/main/res/values/versions.xml
=> team ui fixed (Fixes #2056)

app/build.gradle, app/src/main/res/layout-w600dp/fragment_team_detail.xml, app/src/main/res/layout/fragment_team_detail.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/versions.xml
Fixes #1967 
Community sub tabs now fill the width of the screen for tablets.
=> Community tab layout

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt, app/src/main/res/values/versions.xml, app/src/main/res/xml/pref.xml
=> remove health from beta (Fixes #2068)

app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, build.gradle
=> Add language alert title (fixes #808)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/values/versions.xml
fixes #2048 
Should fix the "Add to myLibrary" button not turning white.
=> Makes "Add to My Library" Button turn White Even After Adding Resources (fixes #2048)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/values/versions.xml
fixes #2051 
Should fix the "Join Selected" button not turning white.
=> Fixes "Join Selected" Button Not Turning White after Joining Courses (fixes #2051)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/values/versions.xml, build.gradle
=> Fix animation not stopping on error (fixes #2030)

.github/workflows/android-release.yml, app/build.gradle, app/src/main/res/values/versions.xml
=> fix sha256 path (fixes #2096)

app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.java
=> pop up for course enrollment (fixes #2089)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.java, app/src/main/res/values/versions.xml
=> set passed if no exams (Fixes #2086)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java, app/src/main/res/values/versions.xml
=> course : open resource crash  and sync dialog issue fixed (Fixes #2101)

README.md
Add a link to Planet in the Readme.md
=> update `README.md` (fixes #2107)

.github/workflows/android-build.yml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/AutoSyncWorker.java, app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/StayOnLineWorker.java, app/src/main/java/org/ole/planet/myplanet/TaskNotificationWorker.java, app/src/main/java/org/ole/planet/myplanet/ui/SplashActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseProgressActivity.kt, app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.java, build.gradle, gradle/wrapper/gradle-wrapper.properties
fix #2108
Merge  2 commits GibsonRutairi pull request 
1. 5bb893231079986bb1a737c2fd3ef375d79a45da
2. 6fb077ae23837c8f7298e11522ea4fe97d4c9a65
which updated dependencies and added dagger hilt dependency Injection
My commit
1. 950c7c603015b0059788b9b1a2c8e565a50fad44
which upgrades the mainapplication to use workmanager instead of firebaseJobDispatcher which is not supported for android version 12+
2. 22e91387a5acc683456b62183dc673df5cce184e upgraded more dependencies
3. 806b86b2115670a10d96f4d31711fedcfe46e3a2 changed the android.yml to set up project using android JDK 11
=> revive build scripts of codebase (fixes #2108)

.github/workflows/android-release.yml, app/build.gradle, app/src/main/res/values/versions.xml
=> new release (fixes #2123)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.java, app/src/main/res/values/versions.xml
1. added MANAGE_ACCESS_STORAGE permission in the AndroidManifest
2. update permission activity to request for MANAGE_ACCESS_STORAGE permission on runtime
3. update fileUtil to create directory if does not exist
4. Sync activity to call requestAllPermissions method
=> enhanced permission for storage access (fixes 2122)

app/build.gradle, app/src/main/res/layout-large-land/activity_child_login.xml, app/src/main/res/layout-large-land/activity_login.xml, app/src/main/res/layout-normal-land/activity_child_login.xml, app/src/main/res/layout-normal-land/activity_login.xml, app/src/main/res/layout-small-land/activity_child_login.xml, app/src/main/res/layout-small-land/activity_login.xml, app/src/main/res/layout-xlarge-land/activity_child_login.xml, app/src/main/res/layout-xlarge-land/activity_login.xml, app/src/main/res/layout/activity_child_login.xml, app/src/main/res/values/versions.xml
=> show full title at login (fixes #2126)

.github/workflows/android-release.yml, app/build.gradle, app/src/main/res/values/versions.xml
=> new testing workflow (fixes #2150)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/res/values/versions.xml
=> manifest: notification permission added (fixes #2137)

.github/workflows/android-build.yml, .github/workflows/android-release.yml, app/build.gradle, app/src/main/res/values/versions.xml, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
fixes issue #2162
When testing the app on github actions android check CI the build fails and logs the error as shown below
after upgrading project  and jcplayer dependency. github actions android check CI the build again fails and logs a different error as shown below
After these upgrades android check CI builds successfully
=> upgrade to JDK 17 for jcplayer (fixes #2162)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt, app/src/main/res/values/versions.xml
Uninitialized resource list in resourceList causes app to crash after login. 
fixes #2165
=> notification: initialize resourceList (fixes #2165)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/values/versions.xml
=> navigation: update logo styling (fixes #2170)

app/build.gradle, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/versions.xml
fixes #2220
This pull request aims to standardize and synchronize the string files across our project repository, ensuring consistency and uniformity in the strings used throughout the application
=> string files standardization for consistency (fixes #2220)

app/build.gradle, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/versions.xml
this pull request contains french translations
fixes #2216
translation link
https://chat.openai.com/share/f194daa6-1c52-4934-8b45-3907ab938954
https://chat.openai.com/share/be516fdf-e0e6-46eb-b2b9-21a35147cc06
https://chat.openai.com/share/c5376d3c-05c9-447e-9389-a267cb7b1648
https://chat.openai.com/share/84e92c2b-5de7-432d-9aff-1a536bb90d46
=> adding French to strings (fixes #2216)

app/build.gradle, app/src/main/res/values-es/strings.xml, app/src/main/res/values/versions.xml
This pull request contains spanish translations
fixes #2233
translation link
https://chat.openai.com/share/562b3f00-7e7c-4a86-ba06-3f2602839353
=> adding more Spanish to strings (fixes #2233)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.java, app/src/main/res/values/versions.xml
fixes #2254 
Fix UI thread transaction issue with callback mechanism
This pull request addresses the UI thread transaction issue that occurs when executing Realm transactions on the main (UI) thread. To fix this issue, I have implemented a callback mechanism that allows passing necessary data to the background thread where the Realm transaction is executed. Once the transaction is completed, the UI is updated on the main thread.
=> feedback: no crashes with async method (fixes #2254)

app/build.gradle, app/src/main/res/layout/fragment_my_course.xml, app/src/main/res/values/versions.xml
fixes #2258
In this pull request, I have increased the padding for the button element to improve its appearance and touch target
=> myCourses: increase padding for leave button (fixes #2258)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/res/values/versions.xml
=> remove unused `REQUEST_INSTALL_PACKAGES` permission (fixes #2269)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java, app/src/main/res/values/versions.xml
=> remove `MANAGE_EXTERNAL_STORAGE` permission (fixes #2272)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/MainApplication.java, app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/AudioPlayerActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/CSVViewerActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/ImageViewerActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/MarkdownViewerActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/TextFileViewerActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.java, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java, app/src/main/res/values/versions.xml
fixes #2273
This pull request aims to enhance media accessibility by implementing accepted storage access permissions. The proposed changes ensures that users can seamlessly access media files, providing a smoother and more user-friendly experience
=> adding `READ_MEDIA_*` permissions (fixes #2273)

.gitignore, app/build.gradle, app/release/output.json, app/src/main/res/values/versions.xml
=> delete app release folder (fixes #2276)(fixes #2277)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java, app/src/main/res/drawable/baseline_arrow_back_24.xml, app/src/main/res/layout/activity_chat.xml, app/src/main/res/values/versions.xml
=> chat: refactor as an activity (fixes #2281)

app/build.gradle, app/src/main/res/layout/fragment_my_course.xml, app/src/main/res/values/versions.xml
=> mycourses: tiny changes (fixes #2044)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt, app/src/main/res/values/versions.xml
=> news: normalize word spacing (fixed #2079)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/values/versions.xml
=> login: enable keyboard only way (fixes #2283) 

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java, app/src/main/res/values/versions.xml
=> remove unused `PERMISSION_REQUEST_CODE_CAMERA` (fixes #2288)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.java, app/src/main/res/values/versions.xml
=> sync: increase stability by adding nullpointer exception (fixes #2298)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/MyPlanet.java, app/src/main/res/values/versions.xml
=> logs: remove gps fragments (fixes #2309)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.java, app/src/main/res/layout/row_joined_user.xml, app/src/main/res/values/versions.xml
=> team: display member image (fixes #2312)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/community/AdapterLeader.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/MyProgressFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt, app/src/main/res/values/versions.xml
=> remove unnecessary kotlin non null assertions (fixes #2332)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/community/HomeCommunityDialogFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterProgressGrid.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt, app/src/main/res/values/versions.xml
=> remove deprecated kotlin `getColor` (fixes #2334)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/UserListArrayAdapter.kt, app/src/main/res/values/versions.xml
=> remove unnecessary kotlin non-null receiver (fixes #2333)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt, app/src/main/res/values/versions.xml
=> remove unused kotlin parameters (fixes #2345)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/AddLinkFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityTabFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/HomeCommunityDialogFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/LeadersFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/MyProgressFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/MyActivityFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt, app/src/main/res/values/versions.xml
=> resolve deprecated onActivityCreated (fixes #2347)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/community/ServicesFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt, app/src/main/res/values/versions.xml
=> use unique variables to avoid name shadowing (fixes #2343)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterMyProgress.kt, app/src/main/res/values/versions.xml
=> courses: use HtmlCompat (fixes #2344)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterMyProgress.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterProgressGrid.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterSteps.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseProgressActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/MyProgressFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.java, app/src/main/res/values/versions.xml
=> courses: switch to viewbinding (fixes #2314)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.java, app/src/main/res/values/versions.xml
fixes #2357 
show message if user tries to submit an empty string
=> feedback: prevent empty submit (fixes #2357)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/community/AddLinkFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt, app/src/main/res/values/versions.xml
=> enterprises: use `lowercase()` (fixes #2335)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dictionary/DictionaryActivity.kt, app/src/main/res/values/versions.xml
=> addons: refactor dictionary activity (fixes #2365)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/helpwanted/HelpWantedFragment.java, app/src/main/res/values/versions.xml
=> addons: refactor helpwanted activity (fixes #2366)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/rating/RatingFragment.java, app/src/main/res/values/versions.xml
=> resources: refactor rating fragment (fixes #2368)

.github/workflows/android-release.yml, app/build.gradle, app/src/main/res/values/versions.xml
=> actions: automatic playstore upload (fixes #2386)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/viewer/CSVViewerActivity.java, app/src/main/res/values/versions.xml
=> resources: bump `com.opencsv:opencsv` to 5.8 (fixes #2406)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/res/values/versions.xml
=> actions: refactor `AndroidManifest.xml` (fixes #2423)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/rating/RatingFragment.java, app/src/main/res/layout/fragment_rating.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml
=> resources: no empty rating submission (fixes #2391)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/FileUploadService.java, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmitPhotos.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.java
=> courses: only one naming convention (fixes #2340)

app/build.gradle
=> actions: unbump `com.mikepenz:*-typeface` to uncrashing (fixes #2475)

app/build.gradle, build.gradle
=> actions: bump `minSdkVersion` in gradle to 21 (fixes #2454)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.java
=> actions: handle `nullException` for wifi switch (fixes #2480)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/references/ReferenceFragment.java
=> addons: refactor reference activity (fixes #2369)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.java
=> courses: refactor take exam module (fixes #2484)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/viewer/AudioPlayerActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/CSVViewerActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/ImageViewerActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/MarkdownViewerActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/TextFileViewerActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.java
=> resources: refactor viewer modules (fixes #2390)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterCalendar.java, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterFinance.java, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.java
=> enterprises: refactor module (fixes #2458)

.github/dependabot.yml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/ImageViewerActivity.java
=> resources: capture and add image (fixes #2370)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/service/AudioRecorderService.java, app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/AudioPlayerActivity.java
=> addons: record and add an audio to resources (fixes #2376)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatActivity.kt
=> chat: refactor towards more stability (fixes #2485)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatActivity.kt
=> chat: refactor and cleanup (fixes #2498)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java
=> sync: harden realm towards null exceptions (fixes #2506)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatActivity.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml
=> chat: prevent null exception crash (fixes #2510)

app/build.gradle
=> actions: remove `org.codehaus.jackson:jackson-mapper-asl` (fixes #2514)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/feedback/AdapterFeedback.java, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.java
=> feedback: refactor using viewbinding (fixes #2491)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.java
=> enterprises: only future dates for deadlines (fixes #2496)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java
=> enterprises: show only for community news (fixes #2495)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterMemberRequest.java
=> enterprises: show username when no fullname (fixes #2499)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/AdapterTeamCourse.java, app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.java, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AdapterOtherInfo.java, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.java
=> profile: implement viewbinding (fixes #2409)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/UserListArrayAdapter.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.java, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java
fixes #2516
this pull request removes picasso which contain com.squareup.okhttp3:okhttp
=> actions: use `com.bumptech.glide.Glide` instead of picasso (fixes #2516)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java
=> sync: close realm properly after sync (fixes #2518)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt
=> notification: initialize callback (fixes #2303)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeam.java
=> login: improve realm instance management (fixes #2526)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.java
=> login: stable realm while settings dialog (fixes #2532)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java
=> resources: more stability with optimized list (fixes #2544)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
=> login: better sync and realm handling (fixes #2541)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java, app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.java
fixes #2378
fix found at https://github.com/noties/Markwon/issues/307#issuecomment-712086119
=> resources: better markdown handling (fixes #2378)

app/build.gradle
=> home: unbump `flexbox` to 1.0.0 (fixes #2549)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
=> dashboard: survive a null user (fixes #2556)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.java
=> login: stabilize `WindowManager` (fixes #2553)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/layout/layout_search.xml
fixes #2547
add textwatcher to perform search as user is typing
=> resources: instant search (fixes #2547)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/viewer/MarkdownViewerActivity.java, app/src/main/res/layout/activity_markdown_viewer.xml, app/src/main/res/layout/fragment_course_detail.xml, app/src/main/res/layout/fragment_course_step.xml
=> courses: use `markwon` for all markdowns (fixes #2561)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseAdapterWithTag.java
=> actions: remove unused base `BaseAdapterWithTag` (fixes #2575)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/AboutFragment.kt
=> about: display app version (fixes #2550)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java
=> courses: improved `select all` responsiveness (fixes #2594)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.java
=> news: cleanup `NewsFragment` (fixes #2607) 

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/User.kt, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/UserListAdapter.java, app/src/main/java/org/ole/planet/myplanet/utilities/SharedPrefManager.kt
=> login: remember all returning users (fixes #2605)

app/build.gradle, app/src/main/res/layout/fragment_user_profile.xml
fixes #1813
Moved the add profile image button to the corner of the profile picture
=> profile: better edit picture button (fixes #1813)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.java, app/src/main/java/org/ole/planet/myplanet/utilities/SharedPrefManager.kt
=> news: more message stability (fixes #2609)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatAdapter.kt, app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatModel.kt, app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatRequestModel.kt
=> chat: new API structure (fixes #2612)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java
=> courses: improve stability (fixes #2620)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
=> login: refactor towards viewbinding (fixes #2611)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt
=> enterprises: refactor calendar towards viewbinding (fixes #2627)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseProgressActivity.kt
=> courses: refactor progress towards viewbinding (fixes #2626)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/viewer/WebViewActivity.java, app/src/main/res/layout/activity_web_view.xml
=> resources: refactor webview towards viewbinding (fixes #2623)

app/build.gradle, app/src/main/res/layout/activity_become_member.xml, app/src/main/res/layout/fragment_achievement.xml, app/src/main/res/layout/fragment_edit_achievement.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml
=> profile: accessibility enhancements (fixes #2632)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
=> settings: show only `cloud` services (fixes #2642)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java
=> courses: better code quality (fixes #2644)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
=> settings: refactor towards more stability (fixes #2649)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java
fixes #2640
rework the viewbinding to resolve the select all functionality
=> resources: select all fully working (fixes #2640)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
=> settings: new default server `planet learning` (fixes #2643)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
=> settings: more realm stability (fixes #2656)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
=> login: more realm stability (fixes #2664)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml
=> login: restrict diacritic characters (fixes #2659)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
=> settings: more realm stability (fixes #2670)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
fixes #2672
Condition left behind from a previous pr
=> login: remove unused code (fixes #2672)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
fixes #2677
remove guest from returning userList after signup
=> login: learner conversion cleanup (fixes #2677)

app/build.gradle, app/src/main/res/layout/activity_audio_player.xml, app/src/main/res/layout/activity_exo_player_video.xml, app/src/main/res/layout/activity_image_viewer.xml, app/src/main/res/layout/activity_pdfreader.xml, app/src/main/res/layout/content_web_view.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml
=> resources: more accessibility in viewer (fixes #2631)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java
=> courses: refresh myCourses on change (fixes #2684)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java
=> resources: refresh after myLibrary change (fixes #2682)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java, app/src/main/res/layout/dialog_server_url_.xml
=> settings: redesign configurations (fixes #2676)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
=> dashboard: show pending survey (fixes #2693)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt
=> dashboard: no health sync popup (fixes #2692)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.java
=> news: more stability (fixes #2697)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.java, app/src/main/res/layout/fragment_finance.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml
Add reset button for Date Filter
=> community: add date reset to finance (fixes #1982)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.java, app/src/main/res/layout/fragment_my_course.xml
=> courses: more responsive navigation (fixes #2704)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.java, app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.java, app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.java, app/src/main/res/layout/fragment_my_library.xml
=> resources: more responsive navigation (fixes #2706)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java, app/src/main/java/org/ole/planet/myplanet/utilities/CustomClickableSpan.java
=> courses: add webview for links (fixes #2708)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt, app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java, app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.java
=> resources: re-enable handling of apk (fixes #2711)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt, app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
=> actions: `REQUEST_INSTALL_PACKAGES` only on request (fixes #2716)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt, app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
=> actions: archive `REQUEST_INSTALL_PACKAGES` permission (fixes #2718)

app/build.gradle, app/src/main/AndroidManifest.xml
=> actions: comment `REQUEST_INSTALL_PACKAGES` in manifest (fixes #2720)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/LoginActivity.java
=> settings: more cloud switch stability (fixes #2722)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.java
=> courses: hide previous at test start (fixes #2735)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmCourseActivity.kt
=> courses: improve stability (fixes #2788)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.java, app/src/main/res/layout/fragment_course_detail.xml
=> courses: better empty data handling (fixes #2786)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt, app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
=> actions: reactivate `REQUEST_INSTALL_PACKAGES` permission (fixes #2790)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.java, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.java
fixes #2793
[Screen recording 2023-12-05 15.42.01.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/9cee794f-e3dc-4b3b-8f3a-67a6b334cae9)
=> courses: auto image size (fixes #2793)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java
=> dashboard: sync on user creation (fixes #2737)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.java
=> actions: refactor `Service` class (fixes #2818)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt, app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
=> actions: pause `REQUEST_INSTALL_PACKAGES` permission (fixes #2825)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java, app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java.lite
=> actions: refactor file permission handling (fixes #2879)

app/build.gradle, gradle.properties
fixes #3000
this pr increase the `-Xmx` value to allocate more maximum heap space for the Gradle daemon
=> actions: increase heap space (fixes #3000)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/AboutFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DisclaimerFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/MyActivityFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/AdapterNotification.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/notification/NotificationFragment.kt
fixes #3028
This pr focuses on resolving remaining warning messages to enhance code quality and maintainability
=> actions: less `dashboard` ui dir warnings (fixes #3028)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardFragment.kt
=> actions: initialize realm property (fixes #3051)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
=> teams: closing realm better (fixes #3061)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.kt
fixes #3062
this pr resolves null exception during course filter
=> courses: better filter (fixes #3062)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.kt, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt, app/src/main/java/org/ole/planet/myplanet/model/MyPlanet.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmCourseProgress.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java, app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.java
fixes #3066
this pr comments/remove out unused variables and parameters
=> actions: less warnings is more (fixes #3066)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite, app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt
fixes #3069
this pr 
- checks initializations before onDestroy is called 
- updates BaseContainerFragment and BaseContainerFragment.lite to have same lines
=> actions: proper initialization check (fixes #3069)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
=> login: init check during sync (fixes #3099)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt
fixes #3106
[Screen recording 2024-02-08 16.01.20.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/469e587d-6765-4703-86a2-bc777ee4acc3)
=>  teams: more join stability (fixes #3106)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/JoinedMemberFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/MembersFragment.kt, app/src/main/res/layout/row_member_request.xml
=> teams: more responsive (fixes #3117)

.github/workflows/android-release.yml
=> actions: switch to `dogi/upload-release-action` (fixes #3122)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
=> team: check fragment state (fixes #3121)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
=> team: more news stability (fixes #3148)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite, app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt, app/src/main/java/org/ole/planet/myplanet/callback/OnCourseItemSelected.kt, app/src/main/java/org/ole/planet/myplanet/callback/OnLibraryItemSelected.kt, app/src/main/java/org/ole/planet/myplanet/callback/TagClickListener.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.kt, app/src/main/java/org/ole/planet/myplanet/ui/library/CollectionsFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/library/TagExpandableAdapter.kt, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
=> courses: less warnings is more (fixes #3150)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
=> survey: allow partial completion (fixes #3136)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
=> survey: more stability (fixes #3120)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt, app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
fixes #3155
check for similar files and download only once and proceed to reuse it
[Screen recording 2024-02-23 18.22.35.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/c5975fbe-11f4-4d52-a40a-5ec6d7d29129)
=> resources: download once (fixes #3155)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/AdapterNews.kt
=> news: more stability (fixes #3154)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt, app/src/main/java/org/ole/planet/myplanet/utilities/NotificationUtil.kt
=> sync: more stable download (fixes #3160)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt
fixes #3175
[Screen recording 2024-02-29 21.10.03.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/e9973f2a-fba1-4ded-a2cf-226535f9d7db)
=> team: smoother sync (fixes #3175)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt
=> news: smoother sync (fixes #3180)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite, app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt
fixes #3178
[Screen recording 2024-03-01 16.13.53.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/0a2adb0b-a1a2-49eb-9ca7-d66d9a871975)
=> dashboard: more stability (fixes #3178)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
fixes #3199
this pr ensures a dialog pop up on the homepage for user to be notified of a pending survey
[Screen recording 2024-03-07 14.27.46.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/8c30d4e8-7b28-4635-8b9b-e7bcd1af75ce)
=> survey: popup after login (fixes #3199)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt, app/src/main/java/org/ole/planet/myplanet/utilities/NetworkUtils.kt
=> actions: less warnings is more (fixes #3211)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmCourseProgress.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BellDashboardFragment.kt
fixes #3213
[Screen recording 2024-03-08 19.23.05.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/27b95551-d962-4118-86d9-18b8fc3ae252)
=> courses: show completion stars (fixes #3213)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseActivity.kt, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite, app/src/main/java/org/ole/planet/myplanet/base/BaseMemberFragment.kt, app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt, app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt, app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt.lite
=> actions: better `Base` fragments and activities (fixes #3222)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt, app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragmentPlugin.kt, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterReports.kt, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/ReportsFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt, app/src/main/java/org/ole/planet/myplanet/utilities/SharedPrefManager.kt
fixes #3223
[Screen recording 2024-03-11 16.22.54.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/45a1ac96-e842-4f85-ab30-9fed8fc2ed5e)
=> enterprises: reports export as csv (fixes #3223)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmCourseProgress.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmRemovedLog.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterMyProgress.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterProgressGrid.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseDetailFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/CoursePagerAdapter.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseProgressActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseStepFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/MyProgressFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.kt
fixes #3232
`?.` (safe call operator) prevents null exceptions from being thrown when the expected value is null
=> courses: more stability through safe call operators (fixes #3232)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.java, app/src/main/java/org/ole/planet/myplanet/callback/SyncListener.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmMeetup.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmMyCourse.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmRemovedLog.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt, app/src/main/java/org/ole/planet/myplanet/service/AudioRecorderService.kt, app/src/main/java/org/ole/planet/myplanet/service/AutoSyncWorker.kt, app/src/main/java/org/ole/planet/myplanet/service/SyncManager.kt, app/src/main/java/org/ole/planet/myplanet/service/UploadManager.kt, app/src/main/java/org/ole/planet/myplanet/service/UploadToShelfService.kt, app/src/main/java/org/ole/planet/myplanet/service/UserProfileDbHandler.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt, app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
=> sync: more stability through safe call operators (fixes #3237)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseActivity.kt, app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.kt, app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt, app/src/main/java/org/ole/planet/myplanet/callback/OnHomeItemClickListener.kt, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt, app/src/main/java/org/ole/planet/myplanet/ui/chat/ChatDetailFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/myPersonals/MyPersonalsFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsDetailActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/survey/SendSurveyFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt, app/src/main/java/org/ole/planet/myplanet/utilities/DownloadUtils.kt, app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt
=> actions: less warnings is more (fixes #3251)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
=> actions: safe dismiss for dialog after download (fixes #3253)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyTeam.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmNews.kt, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/AdapterFinance.kt, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/FinanceFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeam.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/AdapterTeamList.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/MyTeamsDetailFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamPagerAdapter.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/teamCourse/AdapterTeamCourse.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/teamDiscussion/DiscussionListFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/AdapterTeamResource.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/TeamResourceFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/AdapterTask.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt, app/src/main/java/org/ole/planet/myplanet/utilities/DialogUtils.kt
=> teams: safer with call operators (fixes #3252)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseNewsFragment.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmApkLog.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmMyPersonal.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmOfflineActivity.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmSubmission.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmTeamLog.kt, app/src/main/java/org/ole/planet/myplanet/utilities/BottomNavigationViewHelper.kt, app/src/main/java/org/ole/planet/myplanet/utilities/CheckboxListView.kt, app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt, app/src/main/java/org/ole/planet/myplanet/utilities/JsonUtils.kt, app/src/main/java/org/ole/planet/myplanet/utilities/KeyboardUtils.kt, app/src/main/java/org/ole/planet/myplanet/utilities/LocaleHelper.kt, app/src/main/java/org/ole/planet/myplanet/utilities/NetworkUtils.kt, app/src/main/java/org/ole/planet/myplanet/utilities/NotificationUtil.kt, app/src/main/java/org/ole/planet/myplanet/utilities/Sha256Utils.kt, app/src/main/java/org/ole/planet/myplanet/utilities/TimeUtils.kt, app/src/main/java/org/ole/planet/myplanet/utilities/Utilities.kt
=> all: safer with call operators in `utilities` (fixes #3257) 

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/viewer/AudioPlayerActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/viewer/CSVViewerActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/viewer/ImageViewerActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/viewer/MarkdownViewerActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/viewer/PDFReaderActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/viewer/TextFileViewerActivity.kt
=> all: safer with call operators in `viewer` (fixes #3258)

app/build.gradle, app/src/main/res/layout/fragment_team.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml
=> all: update strings (fixes #3274)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/news/NewsFragment.kt
fixes #3281
this pr reverts from a change that causes a `nullPointerException`
=> enterprises: stabler news (fixes #3281)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseResourceFragment.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmRemovedLog.kt, app/src/main/java/org/ole/planet/myplanet/ui/feedback/AdapterFeedback.kt, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/library/AdapterLibrary.kt, app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/library/CollectionsFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryDetailFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFilterFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AdapterHealthExamination.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddExaminationActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/AddMyHealthActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/MyHealthFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/myhealth/UserListArrayAdapter.kt, app/src/main/java/org/ole/planet/myplanet/utilities/AndroidDecrypter.kt
fixes #3282
minimize usage of not-null assertion
=> all: more stable without `!!` (fixes #3282)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/DatabaseService.kt, app/src/main/java/org/ole/planet/myplanet/datamanager/MyDownloadService.kt
=> home: stabler mylife (fixes #3283)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ne/strings.xml, app/src/main/res/values-so/strings.xml, app/src/main/res/values/strings.xml
=> login: never synced (fixes #3296)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/BecomeMemberActivity.kt
=> login: stabler signup (fixes #3289)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
=> welcome: default fallback language english (fixes #3288)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/MainApplication.kt, app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/exam/TakeExamFragment.kt
=> courses: safer call operators in `ExamFragment`s (fixes #3290)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/ManagerSync.kt, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt, app/src/main/java/org/ole/planet/myplanet/model/RealmUserModel.kt
=> sync: safer call operator in `datamanager` (fixes #3298)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/TakeCourseFragment.kt
fixes #3313
[Screen recording 2024-03-27 13.18.53.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/f98b6f33-1a4e-4b52-8418-455e3734b82c)
=> courses: stabler steps count (fixes #3313)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/utilities/FileUtils.kt
=> sync: better storage access for resources (fixes #3086)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.kt
=> feedback: safer database (fixes #3311)

app/build.gradle, app/src/main/res/layout/fragment_take_course.xml, app/src/main/res/layout/fragment_team_detail.xml
=> courses: better layout (fixes #3312)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/res/layout/activity_login.xml
fixes #3328
[Screen_recording_20240402_194041.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/91a80fa8-042e-4c86-9996-d147a6648913)
=> login: handle configuration changes (fixes #3328)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
fixes #3324
[Screen_recording_20240402_193536.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/39025e03-1047-4fc5-8727-c40c5328cd82)
=> courses: stabler search (fixes #3324)

app/build.gradle
=> actions: grouping app dependencies (fixes #3327)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmMyLibrary.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/CommunityTabFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/HomeCommunityDialogFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/team/TeamDetailFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/userprofile/EditAchievementFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/viewer/WebViewActivity.kt
=>  actions: less warnings is more (fixes #3342)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
fixes #3344
[dimisses.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/1dc55a6c-149d-4553-9f55-43d8a099eba2)
=> sync: better progress dialog (fixes #3344)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt
=> all: cleaner `BaseRecyclerFragment` (fixes #3325)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/ProcessUserDataActivity.kt
=> sync: better download check (fixes #3348)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
=> sync: better check if community (fixes #3350)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/exam/UserInformationFragment.kt
=> courses: better `back` in exams (fixes #3356)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/model/RealmFeedback.kt, app/src/main/java/org/ole/planet/myplanet/ui/feedback/AdapterFeedback.kt, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackDetailActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackListFragment.kt
=> feedback: better async query (fixes #3340)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/feedback/FeedbackFragment.kt
=> feedback: safer call operator (fixes #3359)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite, app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
fixes #3371
this pr resolves the issue of the endless loop after creating member
=> sync: upload directly (fixes #3371)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/base/BaseRecyclerFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/course/CourseFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/dashboard/BaseDashboardFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/library/LibraryFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/submission/MySubmissionFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/survey/SurveyFragment.kt
=> actions: less warnings is more (fixes #3368)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt, app/src/main/java/org/ole/planet/myplanet/ui/community/HomeCommunityDialogFragment.kt, app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
=>  login: safer guest config (fixes #3355)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterMyProgress.kt
=> courses: better json in progress (fixes #3378)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterpriseCalendarFragment.kt, app/src/main/res/layout/fragment_enterprise_calendar.xml
=> enterprises: better calendar view (fixes #3377)

app/build.gradle, app/src/main/java/org/ole/planet/myplanet/ui/library/AddResourceFragment.kt
fixes #3385
https://drive.google.com/file/d/1gSghK9-RS1-u3McQjZ6adXzjlI6Mi-Rz/view?usp=sharing
=> resources: better add from storage (fixes #3385)
